### ISSUE TITLE
Issue making a migration including a linkset

### ISSUE THREAD

**Issue by delaneyj** [orientechnologies/orientjs#100]
Using the following in Node.js 4.1

```javascript
"use strict";
exports.name = "initial";

exports.up = function (db) {
    return db.class.create('User', 'V').then(User=> {
        return User.property.create({
            name: 'name',
            type: 'String'
        });
    }).then(()=> {
        return db.class.create('League', 'V').then(League=> {
            return League.property.create({
                name: 'name',
                type: 'String'
            }, {
                name: 'commissioner',
                type: 'link',
                linkedClass: 'User'
            }, {
                name: 'users',
                type: 'LinkSet',
                linkedClass: 'User'
            });
        })
    });
};

exports.down = function (db) {
    return Promise.all([
        db.class.drop('User'),
        db.class.drop('League')
    ]);
};
```

I see the League class and its name in the WebUI's schema editor, but not **commissioner** or **users**.  Is there something syntaxally that's missing here?  Not sure if its related to #98.

**Comment by delaneyj** [comment]
[The documentation on the method](https://github.com/orientechnologies/orientjs#adding-a-property-to-a-class) is not correct.  Per a conversation on gitter need to wrap the multiple properties in an array.  Also should probably cover the valid other options like `mandatory` and `notNull`

**Comment by maggiolo00** [comment]
As @delaneyj  said the documentation was wrong. 
You have to use an array of properties
I've fixed the doc 
see here
https://github.com/orientechnologies/orientjs
and
https://github.com/orientechnologies/orientjs/issues/65
