### ISSUE TITLE
 OIdentifiable record issue in where clause 

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientjs#101]
please refer to following link about this issue. anyway to solve this out?

https://github.com/orientechnologies/orientdb/issues/3812#issuecomment-142755519

**Comment by martingg88** [comment]
any update?

**Comment by maggiolo00** [comment]
@martingg88 
can you try the query 
```SQL
SELECT * FROM tmp WHERE (session_id = "dsdfsdz" AND creator = #16:11710 AND channel = "advertisement" AND func = "create_banner" ) LIMIT 1
```

**Comment by martingg88** [comment]
yes it work without quote around RID,

**Comment by martingg88** [comment]
but the problem is the orientjs will add the quote to rid at where clause..how to solve this?

**Comment by lvca** [comment]
Oh, sorry I didn't get it. Reopening as a bug. @maggiolo00 could address this on Monday.

**Comment by maggiolo00** [comment]
@martingg88  can you post your query  snippet using orientjs?

**Comment by martingg88** [comment]
var cd = {
        'session_id' : 'dsdfsdz',
        'creator' : '#16:11710',
        channel : "advertisement",
        func : "create_banner"
        };

      Tmp.getDB()
      .select()
      .from(Tmp.identity)
      .where(cd)
        .transform(oriento.transform())
        .all()
        .nodeify(function (err, results) {


        });

**Comment by maggiolo00** [comment]
@martingg88  can you try this in cd ?
```JAVASCRIPT
var cd = {
    'session_id' : 'dsdfsdz',
    'creator' : OrientDB.RID('#16:11710'),
    channel : "advertisement",
    func : "create_banner"
    };

  Tmp.getDB()
  .select()
  .from(Tmp.identity)
  .where(cd)
    .transform(oriento.transform())
    .all()
    .nodeify(function (err, results) {


    });
```

**Comment by martingg88** [comment]
not..i can't work at all. still the same issue. can you try at ur side?

**Comment by maggiolo00** [comment]
@martingg88  
What do you mean "it can't work at all"

```
var OrientDB = require('orientjs');
var rid = OrientDB.RID('#5:0')
```

in module orientjs the function RID() is exposed as api  
from file `recordid`

https://github.com/orientechnologies/orientjs/blob/master/lib/index.js

https://github.com/orientechnologies/orientjs/blob/master/lib/recordid.js

**Comment by martingg88** [comment]
{db=hotel} Error on using index tmp.entry in query 'SELECT * FROM tmp WHERE (session_id = "7ei22YUcn1zZjxs5IV5Cqh7
AvtLG50jB" AND creator = {"cluster": 16, "position": 0} AND channel = "advertisement" AND func = "create_banner" )
 LIMIT 1'. Probably you need to rebuild indexes. Now executing query using cluster scan
java.lang.ClassCastException: java.util.HashMap cannot be cast to com.orientechnologies.orient.core.db.record.OIde
ntifiable

**Comment by maggiolo00** [comment]
Ok 
@martingg88 
i'm on it which version of orientjs?

**Comment by martingg88** [comment]
2.0.0

**Comment by maggiolo00** [comment]
@martingg88  which version of OrientDB do you have?

**Comment by maggiolo00** [comment]
@martingg88  how did you insert the creator property?

Is the property declared in `tmp` schema?

**Comment by martingg88** [comment]
OrientDB 2.1.1. 

i use the following part for insert.

var OrientDB = require('orientjs');
var rid = OrientDB.RID('#5:0')

**Comment by martingg88** [comment]
any update?

**Comment by maggiolo00** [comment]
@martingg88 

i've executed this test with your configuration.

orientjs 2.0.0
OrientDB 2.1.1

https://gist.github.com/maggiolo00/d452198f923ecc03ef8c

And i didn't have your problem.

Can you help me replicate your issue?

**Comment by martingg88** [comment]
your script look weird to me. how can you insert #5:0 into link with no any record #5:0 exist in database?

**Comment by martingg88** [comment]
i was my mistake and sorry about that. 

I think the issue is coming from npm waterline library. 
waterline library is a generic interface that support major well-know databases (etc: mysql, postgresql and ..)  in the market. I believe waterline query method doesn't support recordid and that cause the issue. 

I think we can close this issue. 

Thanks.
