### ISSUE TITLE
expand bug

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientjs#103]
expand doesn't work for following query but it work on studio. 

i only get back @rid and @version = defined and the rest of data is missing. 

SELECT EXPAND(rid) FROM (SELECT inV().@rid as rid, DISTANCE(inV().out("locate")[0].lat, inV().out("locate")[0].lng, 3.1333, 101.3833) as distance FROM list WHERE DISTANCE(inV().out("locate")[0].lat, inV().out("locate")[0].lng, 3.1333, 101.3833) <= 10000 ORDER BY (distance ASC), (price ASC)) LIMIT 8

**Comment by luigidellaquila** [comment]
Hi @martingg88 

which version?

**Comment by martingg88** [comment]
2.1

**Comment by maggiolo00** [comment]
@martingg88 if you run that query in studio or console?

**Comment by martingg88** [comment]
work for studio

**Comment by martingg88** [comment]
no update?

**Comment by maggiolo00** [comment]
@martingg88 

can you post some script to reproduce this issue?

**Comment by martingg88** [comment]
sorry....i dont' have script now as i'm busy. please help to test at ur side. thanks.
