### ISSUE TITLE
Where can I find the 2.1 Version of Orientjs ?

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientjs#105]
I don't see the version 2.1 of orientjs on github. The master branch is 2.0.0 but on npm does exist version 2.1.0.

**Comment by maggiolo00** [comment]
hi @StarpTech 

i see 2.1.0 as latest release

https://www.npmjs.com/package/orientjs

**Comment by a-unite** [comment]
@maggiolo00, I believe Dustin was asking for GitHub repository/branch, it was on NPM already, but I also wasn't able to find it on GitHub.
@StarpTech looks, like it is there now: https://github.com/orientechnologies/orientjs/tree/2.1.x

**Comment by StarpTech** [comment]
@a-unite thanks
