### ISSUE TITLE
Unhandled rejection OrientDB.ConnectionError [ECONNREFUSED]

### ISSUE THREAD

**Issue by Conaws** [orientechnologies/orientjs#106]
I'm trying to change over my database from localhost to an instance set up on AWS and finding that orientjs is either failing silently or throwing this error. 

Unhandled rejection OrientDB.ConnectionError [ECONNREFUSED]: connect ECONNREFUSED 
    at Connection.<anonymous> (/****/node_modules/orientjs/lib/transport/binary/connection.js:168:14)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1250:8)
    at doNTCallback2 (node.js:430:9)
    at process._tickCallback (node.js:344:17)

In the host field for connect I'm providing the ip address of the server on AWS (I've enabled cross site scripting), and the credentials and ip work fine for access the studio from that instance.

I can't find any resources for web developers who are trying to use Orient in production, everything seems to just reference localhost.  Is there something I should be doing from within AWS?

**Comment by maggiolo00** [comment]
hi @Conaws 

can you provide your connection snippet?

**Comment by GreyEcologist** [comment]
Hey @maggiolo00 @Conaws facing the same issue, here's my snippet

```
'use strict';
var OrientDB = require('orientjs');

exports.handler = function(event, context) {
	var server = OrientDB({
	  host: 'xxx.xxx.xxx.xxx', //public ip address of the EC2 instance
	  port: 2424,
	  username: 'root',
	  password: 'password'
	});

	server.list()
	.then(function (dbs) {
	  console.log('There are ' + dbs.length + ' databases on the server.');
	});
};
```

**Comment by maggiolo00** [comment]
hi @GreyEcologist 

did you open the `2424` port on the EC2 instance?

**Comment by GreyEcologist** [comment]
@maggiolo00 Thanks for the quick reply. It looks open, I did the automated build via aws marketplace, so the security was automatically set up as below:

```
type: SSH
protocol: TCP
port range: 22
source: 0.0.0.0/0
```

**Comment by GreyEcologist** [comment]
and:
```
type: Custom TCP Rule
protocol: TCP
port range: 2480 - 2490
source: 0.0.0.0/0
```

**Comment by GreyEcologist** [comment]
@maggiolo00 Never mind! my bad, that worked! Thanks a bunch!

**Comment by maggiolo00** [comment]
@Conaws 
by opening the `2424` port you should solve it. I'm closing this.
If it's not solved please reopen it.
