### ISSUE TITLE
Gremlin API

### ISSUE THREAD

**Issue by phpnode** [orientechnologies/orientjs#11]
_From @danieljoppi on May 12, 2015 17:40_

Are there any plans to add Gremlin-compliant syntax fluent API?

_Copied from original issue: codemix/oriento#311_

**Comment by phpnode** [comment]
no plans but it would certainly be possible, would welcome a PR.

**Comment by maggiolo00** [comment]
Not valid anymore. It's better to use the official gremlin-js APIs

http://tinkerpop.apache.org/docs/current/reference/#gremlin-javascript
