### ISSUE TITLE
Distributed Support

### ISSUE THREAD

**Issue by maggiolo00** [orientechnologies/orientjs#111]
Improve the OrientDB Distributed Support. 
The driver now is able to get notification from the servers and the configuration of the cluster.
But it should use this information to reconnect to another server  in case of  broken connection.

**Comment by renanosf** [comment]
Is this working already? For me it's not reconnecting to another server

**Comment by maggiolo00** [comment]
hi @renanosf 

it is not published yet on npm. It will be in a few days

**Comment by maggiolo00** [comment]
@renanosf 

released with orientjs 2.1.11
Docs is here
https://github.com/orientechnologies/orientjs
