### ISSUE TITLE
Dealing with multiple connections and UPDATE failures

### ISSUE THREAD

**Issue by zero-** [orientechnologies/orientjs#112]
I'm trying to create edges between vertexes and I keep getting `OrientDB.RequestError: Cannot UPDATE the record #13:710 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v38 your=v37)` error due multiple connections.

My edge creation code is pretty much straight out of the documentation:
```
ODB.create('EDGE', 'eats_at')
       .from(user.rid)
       .to(place['@rid'].toString())
       .set({
            ts: timestamp
        })
        .one()
        .then(function (edge) {
              cb()
        })
        .error(cb)
```
User vertex has been created earlier and rid is at `user.rid` as `#22:222` format. `Place` is just fetched before making this query so `place` is the same object orientjs returns by default including `@rid`. I tried to convert it to string like user.rid (`#11:111`) to make it use the latest version in the db instead of what orientjs just returned but doesn't seem to work. Obviously in this case the point is not to update `user` or `place` themselves so I would like orientdb simply to get the latest version and append new link to that.

What would be the best way to deal with this?

**Comment by maggiolo00** [comment]
@zero- do you have a quick test to reproduce this issue?

#13:710 is a @rid of Place?

**Comment by zero-** [comment]
@maggiolo00 yes, #13:710 is a @rid of Place. Unfortunately I don't have a test for you because I didn't know if this is a bug or just something that requires a specific/undocumented way of using orientjs.

**Comment by maggiolo00** [comment]
could be that someone is updating the Place. 
Do you have high concurrency on the edge creation? or Place update?

**Comment by zero-** [comment]
Yes, high concurrency edge creation is the reason why this is happening. My problem is that how can I get orientjs to update the latest version instead of getting stuck with the previous ones. I don't specify any specific version to update (just a @rid) so I assumed it would automatically get the latest version based on @rid and update that.

**Comment by maggiolo00** [comment]
yes it gets the latest version but in an high concurrent environment some query could update the @version in the meantime that your query is running.
You can handle the concurrent modification in your application. Or you can use the script sql

to automatically retry if concurrent modification happens

http://orientdb.com/docs/2.1/SQL-batch.html

**Comment by zero-** [comment]
Ok, I'll take a look at those. Thanks.
