### ISSUE TITLE
group by SQL

### ISSUE THREAD

**Issue by warapitiya** [orientechnologies/orientjs#114]
is there way to execute a "group by" SQL in orientjs?

**Comment by maggiolo00** [comment]
@warapitiya how do you execute the select statement?

**Comment by warapitiya** [comment]
This is the orientjs select I wanted to execute:

```js
db
.select()
.from('(SELECT expand(something) FROM Japan WHERE @rid = @1:13)')
.order('timeStamp') // This is what I'm searching for
.all();
```

**Comment by maggiolo00** [comment]
@warapitiya 
there is be available the statement 
```.group('timestamp')```

**Comment by maggiolo00** [comment]
@warapitiya  have you tried it?

**Comment by maggiolo00** [comment]
hi @warapitiya 

did that solve your issue?

**Comment by warapitiya** [comment]
@maggiolo00 yes thanks :+1:
