### ISSUE TITLE
db migration 'then function' not working after creating class

### ISSUE THREAD

**Issue by shyamchandranmec** [orientechnologies/orientjs#120]
I am creating a migration script using

### orients migrate create something

The up function looks like this

 db.class.create('User', 'V')
    .then(function (User) {
        console.log("Created class User");
    })
}

The 'then' function is not getting executed. But the class is getting created. Is there anything missing?
I am using orientdb-community-2.1.6
Here is the link to stackoverflow: http://stackoverflow.com/questions/34130775/db-migration-in-orientdb-nodejs-orientjs

**Comment by maggiolo00** [comment]
hi @shyamchandranmec 

which version of orientjs are you using?

**Comment by shyamchandranmec** [comment]
@maggiolo00 2.1.6

**Comment by shyamchandranmec** [comment]
@maggiolo00  I have edited my previous comment.. I have added the orientjs version as well. Please note

**Comment by shyamchandranmec** [comment]
@maggiolo00 Any update on this?

**Comment by shyamchandranmec** [comment]
@maggiolo00 
 Is this a bug?

**Comment by maggiolo00** [comment]
hi @shyamchandranmec 

could be. Do you have an example script to reproduce it?

**Comment by shyamchandranmec** [comment]
@maggiolo00 

Here is the script.. This then function is not executed
db.class.create('User', 'V')
.then(function (User) {
console.log("Created class User");
})
}

**Comment by maggiolo00** [comment]
hi @shyamchandranmec 

i'm checking it

**Comment by maggiolo00** [comment]
hi @shyamchandranmec 

try this

```JAVASCRIPT
export.up = function(db){
   return db.class.create('User', 'V')
          .then(function (User) {
              console.log("Created class User");
          })
}
}
```

**Comment by maggiolo00** [comment]
hi @shyamchandranmec 

have you tried the above solution?

**Comment by shyamchandranmec** [comment]
Hi, @maggiolo00 

I replied to it that day itself.. But somehow my comment didn't get posted.. Might be some internet issues.. 

Here is my exports.up function.
exports.up = function (db) {
    console.log("Creating classes");
    createClassUser(db);
    createClassPost(db);
}


function createClassUser(db) {
    db.class.create('User', 'V')
        .then(function (User) {
            console.log("Created class User");
        })
}
This doesn't print the console.log().. But the same thing works for db.class.drop

function downCreateClassUser(db) {
    db.class.drop('User')
        .then(function () {
            console.log("Dropped class User")
        })
}
The return is missing. But I think It doesn't make much difference unless I need to chain the promise..

**Comment by maggiolo00** [comment]
If you miss the return. The migrate manager will exit before the console.log
can be called.

**Comment by shyamchandranmec** [comment]
@maggiolo00 I will try it out with the return...

**Comment by shyamchandranmec** [comment]
@maggiolo00  This works. Thanks
