### ISSUE TITLE
Using rid in urls

### ISSUE THREAD

**Issue by shyamchandranmec** [orientechnologies/orientjs#121]
This is not a bug. Just a doubt regarding the Rid property. 

I was trying to use the Rid in the restful url. But because of the hash symbol the browser is not sending the remaining part of the url to the server. Is there any way to change the rid from hash symbol to some other symbol?

**Comment by maggiolo00** [comment]
hi @shyamchandranmec 

you could encode the Rid parameter.

From JS

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent

**Comment by shyamchandranmec** [comment]
@maggiolo00  Thanks.. This works.
