### ISSUE TITLE
in() and out () functions in orientjs using query builder.

### ISSUE THREAD

**Issue by shyamchandranmec** [orientechnologies/orientjs#122]
Is there a way to access the 'In' and 'out' relationships using orientsjs version 2.1? Couldn't find it in the docs.

If yes please give some example.

**Comment by maggiolo00** [comment]
hi @shyamchandranmec 

access in which way?

**Comment by shyamchandranmec** [comment]
hi @maggiolo00 
 Access in query builder.

**Comment by maggiolo00** [comment]
hi @shyamchandranmec 

in / out are not supported in query builder

**Comment by shyamchandranmec** [comment]
@maggiolo00 
Okay. Thanks
