### ISSUE TITLE
.transform() not working with db.query

### ISSUE THREAD

**Issue by shyamchandranmec** [orientechnologies/orientjs#123]
I tried .transform with db.query.. its throwing error.

db.query(query, {
            params: params
        }).transform({
                "@rid": function (rid) {
                    return "something"
                }
            }).all()
            .then(.........

Error----------------

/node_modules/ioredis/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^

TypeError: Cannot read property 'toString' of undefined
    at ServerResponse.writeHead (_http_server.js:189:44)

**Comment by maggiolo00** [comment]
hi @shyamchandranmec 
db.query does not support transform. You have to create a query with the query builder.

**Comment by shyamchandranmec** [comment]
@maggiolo00 

Thanks
