### ISSUE TITLE
orientjs implementation of select expand

### ISSUE THREAD

**Issue by shyamchandranmec** [orientechnologies/orientjs#124]
select expand(IN('SOME_EDGE')) FROM SomeClass where @rid=:someId

Is there a orientjs implementation for the above query?  Couldn't find it in the docs.

**Comment by maggiolo00** [comment]
hi @shyamchandranmec 

have you tried this?

```
db.select("expand(IN('SOME_EDGE'))").from('#12:1').all()
.then(function (result) {
  console.log(result);
});
```

**Comment by shyamchandranmec** [comment]
@maggiolo00 

This works.. Thanks.
