### ISSUE TITLE
beginQuery, endQuery - How can I recognize the relation?

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientjs#127]
The commands are asynchronous. It is not possible to draw conclusions on the begin Query. I want to analyze my queries but in a environment with high traffic it is confusing. Thanks.

beginQuery:

```js
{ query: '<query>',
  mode: 's',
  fetchPlan: '',
  limit: -1,
  token: undefined,
  language: undefined,
  class: 'com.orientechnologies.orient.core.sql.OCommandSQL' }
```

endQuery schema:

```js
{ err: undefined,
  result:
   { status: { code: 0, sessionId: 45 },
     results: [ [Object], payloadStatus: 0 ] },
  perf: { query: 242 } }
```

I recommend:

1. Hash query + additonal parameter with the simple and fast FNVa Hash-Algorithm
2. Provide the id in both events.

or pass the params also to the endQuery event.

**Comment by maggiolo00** [comment]
Hi @StarpTech 

Implemented. See here

https://github.com/orientechnologies/orientjs/issues/200
