### ISSUE TITLE
The update fails with SQL error.

### ISSUE THREAD

**Issue by dmikov** [orientechnologies/orientjs#130]
I retrieve the record using 
let record = this.db.record.get(id);

then I try to save it back with 
this.db.update(id).set(record).scalar();

I get error related I think to @properties. That is a very unexpected behavior.

This is the error.
error from AppRepository.create { [OrientDB.RequestError: Error on parsing command at position #0: Error parsing query: 
UPDATE #11:80 SET @type = "d", @class = "Application", name = "Incident", description = "Security incident reported by IT", fields = [{"@type":"d","faker":"hacker.abbreviation","name":"attack","id":1,"fieldType":"text"},{"@type":"d","faker":"hacker.phrase","name":"attackDescription","id":2,"fieldType":"text"},{"@type":"d","faker":"random.arrayElement(['a','b','c','d'])","name":"severity","id":3,"fieldType":"text"},{"@type":"d","faker":"company.companyName","name":"source","id":4,"fieldType":"text"},{"@type":"d","faker":"internet.userName","name":"reported_by","id":5,"fieldType":"text"},{"@type":"d","faker":"commerce.department","name":"department","id":6,"fieldType":"text"},{"@type":"d","faker":"date.past","name":"occured","id":7,"fieldType":"date"},{"@type":"d","faker":"date.past","name":"reported","id":8,"fieldType":"date"},{"fieldType":"crossReference","direction":"both","applicationId":"#11:81","name":"computer"}], acronym = "IN", @rid = #11:80, @version = 1
Encountered " <RECORD_ATTRIBUTE> "@type "" at line 1, column 19.
Was expecting one of:
    <TO> ...
    <VALUES> ...
    <SET> ...
    <ADD> ...
    <PUT> ...
    <MERGE> ...
    <CONTENT> ...
    <REMOVE> ...
    <ORDER> ...
    <GROUP> ...
    <OFFSET> ...
    <RECORD> ...
    <LUCENE> ...
    <NEAR> ...
    <WITHIN> ...
    <EXCEPTION> ...
    <IN> ...
    <KEY> ...
    <IDENTIFIER> ...
    <QUOTED_IDENTIFIER> ...
    ]
  name: 'OrientDB.RequestError',
  message: 'Error on parsing command at position #0: Error parsing query: \nUPDATE #11:80 SET @type = "d", @class = "Application", name = "Incident", description = "Security incident reported by IT", fields = [{"@type":"d","faker":"hacker.abbreviation","name":"attack","id":1,"fieldType":"text"},{"@type":"d","faker":"hacker.phrase","name":"attackDescription","id":2,"fieldType":"text"},{"@type":"d","faker":"random.arrayElement([\'a\',\'b\',\'c\',\'d\'])","name":"severity","id":3,"fieldType":"text"},{"@type":"d","faker":"company.companyName","name":"source","id":4,"fieldType":"text"},{"@type":"d","faker":"internet.userName","name":"reported_by","id":5,"fieldType":"text"},{"@type":"d","faker":"commerce.department","name":"department","id":6,"fieldType":"text"},{"@type":"d","faker":"date.past","name":"occured","id":7,"fieldType":"date"},{"@type":"d","faker":"date.past","name":"reported","id":8,"fieldType":"date"},{"fieldType":"crossReference","direction":"both","applicationId":"#11:81","name":"computer"}], acronym = "IN", @rid = #11:80, @version = 1\nEncountered " <RECORD_ATTRIBUTE> "@type "" at line 1, column 19.\r\nWas expecting one of:\r\n    <TO> ...\r\n    <VALUES> ...\r\n    <SET> ...\r\n    <ADD> ...\r\n    <PUT> ...\r\n    <MERGE> ...\r\n    <CONTENT> ...\r\n    <REMOVE> ...\r\n    <ORDER> ...\r\n    <GROUP> ...\r\n    <OFFSET> ...\r\n    <RECORD> ...\r\n    <LUCENE> ...\r\n    <NEAR> ...\r\n    <WITHIN> ...\r\n    <EXCEPTION> ...\r\n    <IN> ...\r\n    <KEY> ...\r\n    <IDENTIFIER> ...\r\n    <QUOTED_IDENTIFIER> ...\r\n    ',
  data: {},
  previous: [],
  id: 1,
  type: 'com.orientechnologies.orient.core.sql.OCommandSQLParsingException',
  hasMore: 0 } OrientDB.RequestError: Error on parsing command at position #0: Error parsing query: 
UPDATE #11:80 SET @type = "d", @class = "Application", name = "Incident", description = "Security incident reported by IT", fields = [{"@type":"d","faker":"hacker.abbreviation","name":"attack","id":1,"fieldType":"text"},{"@type":"d","faker":"hacker.phrase","name":"attackDescription","id":2,"fieldType":"text"},{"@type":"d","faker":"random.arrayElement(['a','b','c','d'])","name":"severity","id":3,"fieldType":"text"},{"@type":"d","faker":"company.companyName","name":"source","id":4,"fieldType":"text"},{"@type":"d","faker":"internet.userName","name":"reported_by","id":5,"fieldType":"text"},{"@type":"d","faker":"commerce.department","name":"department","id":6,"fieldType":"text"},{"@type":"d","faker":"date.past","name":"occured","id":7,"fieldType":"date"},{"@type":"d","faker":"date.past","name":"reported","id":8,"fieldType":"date"},{"fieldType":"crossReference","direction":"both","applicationId":"#11:81","name":"computer"}], acronym = "IN", @rid = #11:80, @version = 1
Encountered " <RECORD_ATTRIBUTE> "@type "" at line 1, column 19.
Was expecting one of:
    <TO> ...
    <VALUES> ...

**Comment by maggiolo00** [comment]
hi @dmikov 

yes you cannot set property with @ 

The parser will fail. You should delete those property before save

**Comment by maggiolo00** [comment]
@dmikov 

did you try to remove the properties with @?

**Comment by maggiolo00** [comment]
if you want to save it directly with the record object you should use the API

`db.record`

like 

```JAVASCRIPT
this.db.record.update(record);
```
