### ISSUE TITLE
Problems with some characters in batch

### ISSUE THREAD

**Issue by Ndrou** [orientechnologies/orientjs#133]
**OrientDB** : 2.1.6
**OrientJS** : 2.1.0

When I build a batch with OrientJS, and i want to write in one of the vertex : `test " test )` for example, i have this message : 

```
Found invalid ) character at position 81 of text LET myVertex = CREATE vertex MyVertex SET msg = "test " test )", dc = sysdate(), uid = UUID(). Ensure it is opened and closed correctly.
```

Below a part of my batch, the example below should fail too : 

```sql
BEGIN
 LET myVertex = CREATE vertex MyVertex SET msg = "test \" test )", dc = sysdate(), uid = UUID()
 
COMMIT 
 RETURN $myVertex
```

Test case : 

```js
db
    .let('test', function (s) {
        s.create('vertex', 'V')
            .set({
                msg: 'test " test )'
            })
    })
    .commit()
    .all()
    .then(function (result) {
        console.log(result);
    })
    .catch(function (err) {
        console.log(err);
    });
```
Please an hotfix !

**Comment by Ndrou** [comment]
This seems related to the same bug, right ?
https://github.com/orientechnologies/orientdb/issues/5416

**Comment by Ndrou** [comment]
And another question, do you think it's an OrientJS or OrientDB bug ?
Because we can't upgrade our OrientDB version due to other new bugs that appears in versions > 2.1.6

**Comment by maggiolo00** [comment]
hi @Ndrou 

i think it is an OrientDB bug in batch script parsing.

If you execute only 

```SQL
CREATE vertex MyVertex SET msg = "test \" test )", dc = sysdate(), uid = UUID()
```

as single query it works.

Inside a batch script gives that error.

**Comment by Ndrou** [comment]
Yes, but we can't change all our queries, we have a social network in production with OrientDB, our developer support starts this month. 

We will therefore be obliged to migrate to the version 2.1.9, but if this version, such as 2.1.8, brings us new problems, this will be even more problematic... We recently tested it and got new bugs.

We have not had time to trace them yet because we have not clearly identified the problem as it was not a regular bug.

**Comment by luigidellaquila** [comment]
Hi @Ndrou 

your GitHub account is not linked to a support contract, could you please send an email to support-at-orientdb-dot-com so that we can fix this quickly?

Thanks

Luigi

**Comment by Ndrou** [comment]
Hi @luigidellaquila,

My github account is now linked to the support. 

Is it possible to have this fix in the next release ? 

I come back next week for the other bugs we have when we migrate on version > 2.1.6

**Comment by luigidellaquila** [comment]
Hi @Ndrou 

we are still working on it, I'll give you as soon as it's fixed

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @Ndrou 

I just pushed a fix in 2.1.x branch (the problem was there, not in the Node driver). The fix will be released with 2.1.10, that is planned for tomorrow

Thanks

Luigi

**Comment by ycxq** [comment]
How to get 2.1.10, I have the same problem here:
```
var value = "\")')";
statement = statement.let("1", "INSERT INTO TEST SET Test=\"1" + value + "\"");
statement = statement.let("2", "INSERT INTO TEST SET Test='2" + value + "'");
statement = statement.let("3", 'INSERT INTO TEST SET Test="3' + value + '"');
statement = statement.let("4", 'INSERT INTO TEST SET Test=\'4' + value + '\'');
statement.commit().return("$1").all().then(function (result) {
    console.log(result);
}).catch(function (e) {
    console.log(e);
}).done();
```

**Comment by luigidellaquila** [comment]
Hi @ycxq 

2.1.10 is not released yet, you can build it from sources, branch 2.1.x

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @Ndrou 

2.1.10 was released yesterday with a fix for this issue, you can download it from the website

http://orientdb.com/download/

I'm closing this issue, please reopen in case you experience any problems

Thanks
