### ISSUE TITLE
Emoticone encoding problem 

### ISSUE THREAD

**Issue by MathildeLemee** [orientechnologies/orientjs#134]
I have some encoding problem.

If I use simple emoticon as ♬ it's working.

For emoji like 😃💬 :

If I use OrientDB Console, no problem for me to update some rows with emoticone characters.

If I use OrientJs, I can't make it work : 😃💬' is transformed into ���� (so each emoticone seems to be encoded in two parts).

If it helps I'm using db.update('Card').set(card)... or db.insert('Card').set(card)...

What shall I change in the config to make it work ? How can I change the way the data is serialized ?

Thanks !

Version : 2.1.0

**Comment by maggiolo00** [comment]
hi @MathildeLemee 

are you using java 8 ?

**Comment by MathildeLemee** [comment]
Thanks, it's working well now :+1:

**Comment by eafzali** [comment]
This fixes writing to the database for me but I still receive ���� when query emojis from db. Using node v5.5.0 and OrientDB v2.1.2. I can see that CI tests with node v4 is also failing.
