### ISSUE TITLE
Binary connection over SSL 

### ISSUE THREAD

**Issue by majordo** [orientechnologies/orientjs#136]
hello,
is it possible to using SSL to connect to server?

**Comment by lvca** [comment]
http://orientdb.com/docs/last/Using-SSL-with-OrientDB.html

**Comment by majordo** [comment]
Hi lvca,
actually I red the manual about configuring the db over SSL, but what I wonder is if I can use orientjs to connect over SSL, and if YES how, because I didn't see anything about it in orients's docs...
I didn't specify "via orientjs" because I post my question in orientj's Github page, I though it was obvious, sorry about that.
Next time I will be more accurate.

**Comment by lvca** [comment]
@majordo got it. @maggiolo00 do you have any hint about this config in orientjs?

**Comment by majordo** [comment]
@mahhiolo00 not really, just how to ;)

**Comment by maggiolo00** [comment]
@majordo it is not supported yet in orientjs

**Comment by nicolasembleton** [comment]
Hi, is it still not supported?

**Comment by maggiolo00** [comment]
hi @nicolasembleton 

this has been merged in master

https://github.com/orientechnologies/orientjs/pull/237

It will be available in the next release of  orientjs that should be this week

**Comment by lvca** [comment]
Already supported.

**Comment by nicolasembleton** [comment]
Great. Thanks.
