### ISSUE TITLE
how to add a callback or Promise on Server.use()

### ISSUE THREAD

**Issue by bytebrahma** [orientechnologies/orientjs#137]
HI,

When I write the below code, how can I make the program wait till the use() is completed? I m worried in case the orient server is busy or _the dbName is incorrect_, it may take time to latch on to a database and meanwhile, *return* would get executed returning an empty object.
```
openDb=function(dbName){
db =server.use(dbName)
return db;
}
```
I tried .```then()``` but it throws an error and seems it is not a Promise. Any help is greatly appreciated!

Thanks in advance..

**Comment by maggiolo00** [comment]
hi @bytebrahma 

server.use is not behind a Promise since it only create the Db object with configuration.
If you want to do that you should call db.open.
Try this

openDb=function(dbName){
 db =server.use(dbName)
 return db.open();
}

**Comment by bytebrahma** [comment]
Thanks @maggiolo00! Got your point. As server.use() is a non-blocking function and hence would not need a Promise/callback.

However to execute sqls and queries, do I need to always do ```db.open()``` ?

**Comment by maggiolo00** [comment]
hi @bytebrahma 
The query api should check that for you.

**Comment by bytebrahma** [comment]
Sorry I meant  - is ```db.open()``` needed before ```db.query()``` ?

**Comment by maggiolo00** [comment]
@bytebrahma 
i meant if you call `db.query` without open the api will check if the db is opened. 
If not will open for you.

**Comment by bytebrahma** [comment]
Oh..thats cool. Thanks!
