### ISSUE TITLE
how can I get database's timezone?

### ISSUE THREAD

**Issue by Ivanov-Yuriy** [orientechnologies/orientjs#138]
Hi, I use node.js + orient.js

I need to know the time zone of my database and dateTime format.
How can I do it?
Thank you.

**Comment by maggiolo00** [comment]
hi @Ivanov-Yuriy 

db metadata are placed in record `#0:0`

but they are in a special format

to retrieve them you could do

assuming that you have the db instance

```
db.open().then(function(){
	return db.record.get('#0:0');
}).then(function(doc){
	console.log(doc.value.toString('UTF-8').split("|")[8]);
})
```

this is for dateTime format

i think Timezone are in 5,6,7

you can check them with 


```
console.log(doc.value.toString('UTF-8').split("|"))
```

**Comment by Ivanov-Yuriy** [comment]
@maggiolo00 thanks, you helped me a lot.
