### ISSUE TITLE
Failure to retrieve records: function+property+expand with OrientDB 2.2

### ISSUE THREAD

**Issue by sinfex** [orientechnologies/orientjs#147]
Take two vertices connected by a single non-lightweight edge Alice -> Edge -> Bob.

```
CREATE VERTEX V SET name = 'Alice'
CREATE VERTEX V SET name = 'Bob'
CREATE EDGE E FROM (SELECT FROM V WHERE name = 'Alice') TO (SELECT FROM V WHERE name = 'Bob')
```

Let's retrieve any vertices any outgoing edges from Alice are pointing to.
This can be done using `out()` instead of `outE().in`, but mind a scenario when we need to work with both the edge and target vertex.

In Console:

```
orientdb {db=test}> SELECT EXPAND(outE().in) FROM V WHERE name = 'Alice'

----+----+------+----+--------
#   |@RID|@CLASS|name|in_
----+----+------+----+--------
0   |#9:1|V     |Bob |[size=1]
----+----+------+----+--------
```

Same query using **OrientJS 2.1.0** with **OrientDB 2.1.9**:

```
DB.query(`SELECT EXPAND(outE().in) FROM V WHERE name = 'Alice'`).then(r => console.log(r));

> [ { '@type': 'd',
    '@class': 'V',
    name: 'Bob',
    in_:
     Bag {
       serialized: 'AQAAAAEACgAAAAAAAAAAAAAAAAAAAAAAAA==',
       uuid: null,
       _content: [],
       _buffer: null,
       _type: null,
       _offset: 0,
       _current: -1,
       _size: null,
       _prefetchedRecords: [Object] },
    '@rid': { [String: '#9:1'] cluster: 9, position: 1 },
    '@version': 2 } ]
```

Same query using **OrientJS 2.1.0** with **OrientDB 2.2-SNAPSHOT**:

```
DB.query(`SELECT EXPAND(outE().in) FROM V WHERE name = 'Alice'`).then(r => console.log(r));

> [ { '@rid': { [String: '#9:1'] cluster: 9, position: 1 },
    '@version': undefined } ]
```

Only the RID is retrieved, all other record properties are either missing or, in the case of `@version`, set to `undefined`. Not sure if this can be reproduced with a simpler example.

**Comment by maggiolo00** [comment]
hi @sinfex 

tested now with today compiled version of OrientDB 2.2-snapshot and orientjs 2.1.0 and works fine.

Which snapshot version did you use of ODB?

**Comment by sinfex** [comment]
@maggiolo00 this is tested with the snapshot version currently linked at the [Download page of OrientDB](http://orientdb.com/download/) under the link to [OrientDB 2.2-alpha](http://orientdb.com/download.php?email=unknown@unknown.com&file=orientdb-community-2.2-alpha.tar.gz&os=linux)

**Comment by maggiolo00** [comment]
hi @sinfex 
i think the problem is that this version is old and was an experimental alpha version. 
We are releasing in the next days OrientDB 2.2.beta.
Meanwhile you could try one of these recently snapshot or you can compile it from the code branch develop

**Comment by maggiolo00** [comment]
You can find the snapshot releases here

https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.2.0-SNAPSHOT/

**Comment by sinfex** [comment]
@maggiolo00 just tested `orientdb-community-2.2.0-20160115.215558-38-distribution`, problem seems to be resolved. Cheers.
