### ISSUE TITLE
Creating an edge  - using db.exec() or db.create() - Which one is faster?

### ISSUE THREAD

**Issue by bytebrahma** [orientechnologies/orientjs#149]
Hi,

I am currently using db.exec() by passing a sql like below. And this iterates for 400K rows to create edges between the vertices created earlier by our program. However this taking around 19 minutes. I am wondering if I can reduce this further. Because I have more such edges to be created around 200K for each class. Is db.create() any faster that exec()?

```
var edgeSql="create edge "+edge+" from (SELECT FROM "+sourceClass+" where "+sourceCol+"= :sourceVal) to (SELECT FROM "+targetClass+" WHERE "+targetCol+" = :targetVal) "
						edgeSql += " content "+ JSON.stringify(contentObj)

/*in another function*/

db.exec(sql,paramObj)
		.then(function(val){
			resolve(val);
		})
```

**Comment by maggiolo00** [comment]
hi @bytebrahma 

db.create it is only a way to create the query with fluent api. 
Underlying it will call db.exec once the query is created.

**Comment by bytebrahma** [comment]
That means process the raw query would be any day faster. Thanks!
