### ISSUE TITLE
Update on NPM

### ISSUE THREAD

**Issue by jarno-steeman** [orientechnologies/orientjs#150]
Current version on NPM is 2.1.0 while there's a 2.1.9 version in the 2.1.x branch. Could npm be updated?

**Comment by maggiolo00** [comment]
hi @jarno-steeman 
yes it will be released tomorrow

**Comment by maggiolo00** [comment]
hi @jarno-steeman 
just uploaded on npm orientjs 2.1.11

**Comment by jarno-steeman** [comment]
awesome! thanks
