### ISSUE TITLE
db.record.get([..records], options) broken for multiple records

### ISSUE THREAD

**Issue by jpstrikesback** [orientechnologies/orientjs#151]
The method called `records.map(this.record.read, this)` is perhaps from oriento? No matter, it doesn't exist :) PR on the way.

**Comment by maggiolo00** [comment]
hi @jpstrikesback 
which error do you get?

**Comment by maggiolo00** [comment]
Cool for the PR :D

**Comment by jpstrikesback** [comment]
:)

Error:  `TypeError: this.record.read is not a function`
Upon sorting that out with the correct function name and added tests I found that the options/fetch plan wasn't passed for an array of items.

**Comment by maggiolo00** [comment]
Merged
