### ISSUE TITLE
Build failing!

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientjs#153]
The red button on the repo site indicates that some tests are failed. What is the status and who checks this? This gives me a feeling of a broken release.

**Comment by maggiolo00** [comment]
hi @StarpTech 

i'm on it. 

Test against 2.1.11 works. 
We recently added node v4/v5 in testing and there we still have some issue with emoji. I'm trying to figure out why. Btw with the new binary serialization coming in 2.2 this is resolved.

**Comment by lvca** [comment]
Closing because no answer after months. In case please reopen/comment this.

**Comment by StarpTech** [comment]
Reopen as long as the red button are shinning :dancers:

**Comment by lvca** [comment]
@maggiolo00 what's the reason why Travis says RED?

**Comment by maggiolo00** [comment]
The reason is emoj with 2.1.x

**Comment by lvca** [comment]
So how can we resolve this? Are they supported with 2.1? If not, please remove the test

**Comment by maggiolo00** [comment]
Green again

https://travis-ci.org/orientechnologies/orientjs/builds/156813618

**Comment by lvca** [comment]
Awesome.

**Comment by StarpTech** [comment]
Nice
