### ISSUE TITLE
Can I express any kind of query with the fluent api ?

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientjs#163]
The answer is essential for me beause it decides whether I use orientjs or I my own query builder.
Transactions are a powerful feature. Is it possible to create any kind of query with the fluent api?

E.g
- Traversing
- Nested select statements (which are usual in orientdb)

E.g
```sql
SELECT COUNT(*) FROM (TRAVERSE OUT('BroughtIntoLeft', 'BroughtIntoRight') FROM (SELECT OUT('BroughtIntoRight') FROM ? )) WHERE BinaryQualified = true AND SponsoredBy = ?
```

**Comment by maggiolo00** [comment]
hi @StarpTech 

Any kind i don't know but you can build nested statements

for your E.g you can do something like this.

```JAVASCRIPT
	var query = db.select("count(*)").from(function(e){  
			return e.traverse("OUT('BroughtIntoLeft', 'BroughtIntoRight')").from(function(f){
				return f.select("OUT('BroughtIntoRight')").from('#9:1')
			})	
		})
	.where({ "BinaryQualified" :  true, "SponsoredBy" : "#10:1" });
	console.log(query.buildStatement());
	query.all().then(console.log);
```

**Comment by StarpTech** [comment]
@maggiolo00 thanks I will try this approach. I think it would be good to add this to the docs.

**Comment by StarpTech** [comment]
@maggiolo00 the new orientjs implementation in C will it have the same api?

**Comment by maggiolo00** [comment]
@StarpTech 
yes some api needs more docs and examples

**Comment by maggiolo00** [comment]
@StarpTech 
yes
the api will be the same

**Comment by StarpTech** [comment]
@thanks

**Comment by maggiolo00** [comment]
@StarpTech 
What changes is only the serializer/deserializer that in 2.2.x will be native if supported
