### ISSUE TITLE
Question: How to use let variable in next js function

### ISSUE THREAD

**Issue by Cowby** [orientechnologies/orientjs#166]
Hi there, 

I'm new to orientjs and orientdb and facing a small problem. I want to use the result of a select statement in the next part to do an update. I thought of something like that, but it seemed not to be working, it only safes something like '_NOT_PARSED'. Here is my code snippet:

`var script = 'begin;';`
`script += "let old = SELECT FROM element WHERE NAME = 'test';";`
`script += "let new = UPDATE element SET property = {propstate : $old[0].propstate} WHERE NAME = 'test';";`
`script += "commit retry 100;";`
`script += "return $new;";`
`       con.query(script, {class: 's'})`
`                .then(function (res) {`
`                    console.log(res);`
`               });`

I also tried the querybuilder but that seems to be not working for me at all, because nothing is updated. Anybody an idea how to achieve something like that?  

Regards, Cowby

**Comment by Cowby** [comment]
And yes, i tried it with something like that:

[follow me](http://stackoverflow.com/questions/30690967/orientdb-how-to-update-column-using-select-query)

**Comment by luigidellaquila** [comment]
Hi @Cowby 

I think I found the problem and I should have a fix. I'm running the tests now, I'll keep you posted

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Hi @Cowby 

I just pushed a fix to 2.1.x branch, now I'm porting it to develop

The fix will be available in 2.1.16 and 2.2 RC1

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Ok, fixed on develop branch as well. Closing.

Please reopen if you see any other related problems

Thanks

Luigi
