### ISSUE TITLE
Asynchronous queries

### ISSUE THREAD

**Issue by Silur** [orientechnologies/orientjs#167]
The documentation does not mention how to use [Async queries](http://orientdb.com/docs/last/Document-Database.html#asynchronous-query) in javascript, yet this is the **MOST** important feature since nodeJS is an async language and you promise that you support big data.

**Comment by DarkKnight1992** [comment]
is there a way to use async queries ?

**Comment by maggiolo00** [comment]
Hi @DarkKnight1992 

it will be available in OrientDB 3.0 with the new streaming protocol and in OrientJS 3.0 with Observable

Thanks

**Comment by DarkKnight1992** [comment]
thanks for the quick response.

Is there a estimated release month ?

**Comment by wolf4ood** [comment]
Streaming support is available in OrientJS 3.0.x

https://orientdb.com/docs/3.0.x/orientjs/Session.html#streaming
