### ISSUE TITLE
Db.Exec is not returning all edge arrays (unlike in orientdb studio)

### ISSUE THREAD

**Issue by bytebrahma** [orientechnologies/orientjs#171]
Hi,

My application uses orientjs library in the middleware. But I have noticed that the same query's output does not have all the edges in the JSON object returned by ```db.exec``` whereas, in the raw output of Orientdb studio, they are correctly present.

The query is:
```select * from ( TRAVERSE bothE(), bothV() from (SELECT * FROM records  WHERE  recname = 'JOB' ) while $depth <= 5 strategy DEPTH_FIRST ) LIMIT 500```

HTTP request's JSON response from the browser console

![image](https://cloud.githubusercontent.com/assets/16473286/14942985/2430b1d0-0feb-11e6-8af4-941a70e32d8a.png)

The same query run in the OrientDb  studio (you can see that the very first vertex #13:6000 has the *out_record_fields* which is missing from the JSON output. However the *out_subrecords* edge array is also present in the studio raw output correctly):
 
![image](https://cloud.githubusercontent.com/assets/16473286/14943005/d5c2e274-0feb-11e6-9938-fed95f8119fb.png)

Any pointers would be of great help!

Thanks in advance.
Rao

**Comment by bytebrahma** [comment]
Another observation is that there is a difference in the JSON output/response for db.exec and calling HTTP API of http://<server>:<port>/command/db/sql/<sql>.

The latter seems to be returned a neat JSON objects with all edges as arrays and also includes fieldtypes. But the former, db.exec seems to be bundling the edges as 'bag' objects. Not sure why but while I process the JSON, some edge arrays are missing.

I had to opt the db.exec as I have written the middleware to handle the multiple requests for different databases. Can we make the db.exec also to return similar output?

**Comment by maggiolo00** [comment]
hi @bytebrahma 
that is because the protocol is different. OrientJS uses the binary protocol by default instead of the http protocol.

**Comment by maggiolo00** [comment]
Hi @bytebrahma 
You should increase this settings in order to make that work. 

http://orientdb.com/docs/last/OrientJS.html#bonsai-structure

The Tree RidBag are not supported yet in OrientJS
https://github.com/orientechnologies/orientjs/issues/29

Thanks 
Enrico
