### ISSUE TITLE
Executing function will output collection of RIDs

### ISSUE THREAD

**Issue by warapitiya** [orientechnologies/orientjs#176]
I tried executing a function from orientjs 2.1.11 & 2.2.0-beta2. But I end up only having list of RIDs.
Anyway OrientDB Studio gives me the result I wanted. Tried adding a **fetchplan**, no luck I guess.

**app.js**
```js
db
  .query('select google()', {})
  .then(function(_records) {
    console.log(`records ${_records.length}`);
    return response
      .status(200)
      .json(_records)
      .end()
  }, function(_error) {
    console.error(_error);
    return response
      .status(400)
      .json({
        error: _error
      })
      .end()
  });

``` 

**Orientdb Function**
```js
var a = db.query("SELECT * FROM Record");
return a;
```

**OrientDB Studio output**
```json
[
  {
    "@type": "d",
    "@rid": "#10:5",
    "@version": 6,
    "@class": "Record",
    "name": "Record-1"
  },
  {
    "@type": "d",
    "@rid": "#10:6",
    "@version": 9,
    "@class": "Record",
    "name": "Record-2"
  }
]
```

**NodeJS output**
```json
[{"@type":"d","google":["#10:5","#10:6","#10:7","#10:8","#10:9","#10:10","#10:11","#10:12","#10:13","#10:14","#10:15","#10:16","#10:17","#10:18","#10:19","#10:20","#10:21","#10:22","#10:23","#10:24","#10:25","#10:26","#10:27","#10:28","#10:29","#10:30","#10:31","#10:32","#10:33","#10:34"],"@rid":"#-2:1","@version":0}]
```

```
OrientJS : 2.1.11
OrientDB : 2.1.9
NodeJS : v4.4.0
```

**Comment by maggiolo00** [comment]
hi @warapitiya 

is the studio output from the function panel?

if you run  

```select google()```

from Browse tab of studio you should get the same result as orientjs.

Try 
```
select expand(google())
```

**Comment by warapitiya** [comment]
Yes it worked. Can you explain why this is happening?

Thanks @maggiolo00 👍

**Comment by maggiolo00** [comment]
hi @warapitiya 

this is how functions works used in SQL. Like Graph Functions in() out() Both() ...

they just return the record ids. Then you can decide if you want to expand that rids or not.

If you call directly that function over rest api instead you will get the result set of of the query in json format.

**Comment by warapitiya** [comment]
@maggiolo00 Thanks, You can close this issue.
