### ISSUE TITLE
Transaction pool

### ISSUE THREAD

**Issue by facelessTT** [orientechnologies/orientjs#180]
Hello there... Is there a way to create multi-database transaction commits?
for example: I have connection1 and connection2, to servers which are not in cluster. I need to execute 2 separate transactions to both databases, and if one of them fail, rollback both...
Is it possible with orientjs?
Are there workarounds if no?
Are there plans to support such functionality?

Thank you!

**Comment by laa** [comment]
@facelessTT there is such way but it is not in public API yet. Will you use it ?

**Comment by laa** [comment]
If you wish you may fill issue and we add public support in 3.0 version.

**Comment by facelessTT** [comment]
I would really like to have this functionality.... asap.
I have couple of hot features to implement, which require multi-database transactions. 
How can I request it?

**Comment by laa** [comment]
@facelessTT could you work with given case using stored procedure or you need remote access ?

**Comment by facelessTT** [comment]
remote.... servers can be geo distributed (i.e. its not same server, different databases. its two completely different servers with different IPs)

**Comment by laa** [comment]
@facelessTT well in such case, it will be distributed 2p commit. We may provide this feature only for 3.0 version. Sorry.

**Comment by facelessTT** [comment]
When is it planned?

**Comment by laa** [comment]
@facelessTT the end of 2016

**Comment by facelessTT** [comment]
Iaa, is there a way to start transaction using stored procedure, with one remote call, and then commit or rollback it with another?

**Comment by maggiolo00** [comment]
Remote transactions are not supported yet in OrientDB. 
Once they are supported 3.0 and supported also in orientjs you could achieve that behaviour.

**Comment by facelessTT** [comment]
Ok then. Thank you!

**Comment by lvca** [comment]
Supported in v3.0.
