### ISSUE TITLE
Increment by 0 defaults to incrementing by 1

### ISSUE THREAD

**Issue by EricLin2004** [orientechnologies/orientjs#182]
Pretty small issue: I had some code where I needed to increment from 0-4 at a time and the end result wasn't matching what I was expecting. I noticed that when I increment by 0 via `.increment('field', 0)` it was still incrementing by 1. This doesn't happen in the OrientDB Console.

This line here:
https://github.com/orientechnologies/orientjs/blob/master/lib/db/statement.js#L126

I believe is causing the problem, since `0 || 1` is `1`

**Comment by maggiolo00** [comment]
Thanks 
@EricLin2004 

I will fix it for the next release

**Comment by maggiolo00** [comment]
Hi @EricLin2004 
Fixed
