### ISSUE TITLE
[Documentation & Readme] Typescript definition file for orientjs , orientjs.d.ts available now 

### ISSUE THREAD

**Issue by saeedtabrizi** [orientechnologies/orientjs#184]
Hi 
after two years working on some projects with typescript and nodejs with orientdb  , i produce a definition file for orientjs and its availabale in PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9813#event-703728856 now.
so the nodejs typescript developers can use orientjs definition file in their projects easily .
for using typings in your projects 
1. execute `npm install -g typings`
2. execute `typings search orientjs`
3. execute `typings install dt~orientjs --global`

**Note** : if you have error on bluebird dependency you can run `typings install dt~bluebird --global` and  `typings install dt~node --global` . 
you can find more info at [http://definitelytyped.org/](http://definitelytyped.org/) .

**EDIT**
In the newer version of npm  and according to [https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/) you can easily install definition files from npm repository by following command :
  execute in Terminal : `npm install orientjs @types/orientjs --save` in your project path . 

Welcome to your comments .

Regards
Saeed Tabrizi

**Comment by saeedtabrizi** [comment]
Hi @maggiolo00 
there is a new simple way to install definition files now . and i edit my procedure .
**EDIT**
In the newer version of npm  and according to [https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/) you can easily install definition files from npm repository by following command :
  execute in Terminal : `npm install orientjs @types/orientjs --save` in your project path .

Thanks .

**Comment by saeedtabrizi** [comment]
Hi @maggiolo00 
there is a new simple way to install definition files now . and i edit my procedure .
**EDIT**
In the newer version of npm  and according to [https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/) you can easily install definition files from npm repository by following command :
  execute in Terminal : `npm install orientjs @types/orientjs --save` in your project path .

Thanks .

**Comment by saeedtabrizi** [comment]
Hi @maggiolo00  , the new orientjs features in #234 , #233 , #232 needs to be update documentation . 
Already i pushed the new definition file fot type script in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14425 .

**Comment by lvca** [comment]
@saeedtabrizi what is missing in this issue?

**Comment by saeedtabrizi** [comment]
@lvca it's about documentation for added features to orientjs. 
- if not exist options in  schema operations.
- supporting sequences.
- using raw expression .

**Comment by saeedtabrizi** [comment]
@lvca i recently update typescript .d.ts definition file for the latest orientjs features.  
It is available in npm repository via following command :
'npm install @types/orientjs --save-dev '
This command can be documented for typescript users .

**Comment by andy-ms** [comment]
Why not [bundle](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) types with the package so they won't have to be copied to DefinitelyTyped and installed separately?

**Comment by saeedtabrizi** [comment]
@andy-ms It's good idea for ease of use in typescript . but for integration with `bluebird `and `nodejs` .d.ts files , i prefer to use  DefinitelyTyped packages .

**Comment by andy-ms** [comment]
You should be able to `npm install --save @types/node @types/bluebird` in your package to get those dependencies.

**Comment by saeedtabrizi** [comment]
@andy-ms I agree with you completely . If @maggiolo00 inform to me about updating definition for v3.0.0 , so  i can update package.json to use the bundled definition file for typescript users .
Thanks.

**Comment by saeedtabrizi** [comment]
Hi @wolf4ood , may i know your plan for publish v3 release date ? I want to update typescript definition file as we discussed here . 
Thanks
Saeed

**Comment by wolf4ood** [comment]
Hi @saeedtabrizi 

we are doing  bunch of beta releases. I think the final release will come the next week.

Do you need help with the typescript definition for the new APIs?

Thanks

**Comment by saeedtabrizi** [comment]
Hi @wolf4ood 
So good news . 
I need to know the changes list and deprecation in v3.0 APIs exactly , so i review the code changes in main branch at the next week . 
Definitely, i will update typescript definition file after know it .

Thanks

**Comment by saeedtabrizi** [comment]
Hi @lvca , @wolf4ood 
Recently i have an update for typescript definition that available in npmjs [@types/orientjs](https://www.npmjs.com/package/@types/orientjs) .
I just update the builtin orientjs .d.ts file version  to latest definition file in PR https://github.com/orientechnologies/orientjs/pull/374
Thanks.

**Comment by saeedtabrizi** [comment]
Hi @lvca , @wolf4ood  
I have updated typescript definition file to the latest new API changes  in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38389 .

**Comment by diegonc** [comment]
Hi, @saeedtabrizi.

The typings are missing the extends relationship between ODatabaseTransaction and OTransaction located at [database-tx.js](https://github.com/orientechnologies/orientjs/blob/develop/lib/client/database/database-tx.js#L92) line 92.

Any reason why?

Thanks!

**Comment by saeedtabrizi** [comment]
Hi @diegonc 
Thanks for review , i just apply it .

**Comment by saeedtabrizi** [comment]
Just i push a new implementation ( #438 , #439 ) of typescript definition for orientjs and embed it to orientjs package.
After this push we don't need to install seprated typing package for orientjs and there is a built in typescript support for orientjs .
