### ISSUE TITLE
Emoji encoding issue

### ISSUE THREAD

**Issue by janjilek** [orientechnologies/orientjs#185]
Hello,
when I try to fetch value with emoji (😁), I always receiver ������. When I check it in the web console, everything looks good.

Is possible to fix it somehow?

Thank you
Jan

**Comment by maggiolo00** [comment]
@janjilek 

you should switch to OrientDB 2.2.x and orientjs 2.2.x. 
The issue has been resolved there

**Comment by maggiolo00** [comment]
@janjilek 

which version are you using.?

**Comment by janjilek** [comment]
I am using OrientJS v2.2.1 and OrientDB v2.1.16. I can fetch emoji right via JavaDriver, so it should be driver related, not DB related :-)

**Comment by maggiolo00** [comment]
That is because the driver uses the old csv serializer /deserializer. If you use orientjs with orientdb 2.2.x you can use the native one. But i will try to fix this in OrientDB 2.1.x.  Thanks

**Comment by janjilek** [comment]
Thank you!

**Comment by maggiolo00** [comment]
Fixed in OrientDB 2.2.x and orientjs 2.2.x
