### ISSUE TITLE
"linkedType" not getting while making "MyClass.property.list()" call

### ISSUE THREAD

**Issue by apriyadarshi38** [orientechnologies/orientjs#186]
hello,
  when i am trying to get all property of class but not getting "LinkedType"

MyClass.property.list()
.then(function (properties) {
  console.log('The class has the following properties:', properties);
});

is it possible to get all property details including "LinkedType" and "LinkedClass"

thank you
Abhishek

**Comment by maggiolo00** [comment]
hi @apriyadarshi38 
you should get the linkedClass information

just run this script and i got the linkedClass info

```
var ODatabase = require('orientjs').ODatabase;
var db = new ODatabase({
	 	host: 'localhost', 
		port: 2424, 
		username : 'admin', 
		password : 'admin', 
		name : 'GratefulDeadConcerts'});


db.open()
.then(function(){
	return db.class.get('OUser');
})
.then(function(cls){
	return cls.property.list()
})
.then(function(properties){

	console.log(properties.filter(function(p){
		return p.name == 'roles';
	}));

	db.close();
})

```

**Comment by maggiolo00** [comment]
@apriyadarshi38 

did you try it?

**Comment by apriyadarshi38** [comment]
thank you for reply
yes ,
i have tried and getting "linkedClass" but not getting "linkedId" so i did query like this and getting result.


var getAllProperties = function (databaseName, sourceClass) {
  var db = dbServices.useDatabse(databaseName)
  db.query('select expand(properties) from (select expand(classes) from metadata:schema) where name =:name', {
    params: {
      name: sourceClass
    }
  }).then(function (results) {
    console.log(results)
  }, function (err) {
    console.log(err)
   
  })
}
