### ISSUE TITLE
How to  use orientdb functions as a params value 

### ISSUE THREAD

**Issue by saeedtabrizi** [orientechnologies/orientjs#189]
Hi 
I have a problem with orientjs  processing the statement and params .
when  i want to use sequence function for a parameter in insert statement my param render as string , for example : 
```
.......
let content =  {
                TableID: "sequence('Table_Seq').next()", // this part of code must be a sequence  function
                Notes:""
            };
....
            db.insert().into("BgmTable").set(content) // and execute statements .
```
how we can use sequence function in insert or update api ?

Thanks 
Saeed Tabrizi

**Comment by saeedtabrizi** [comment]
I use a trick to handle this issue when i writing the raw expression in parameters by following steps :

in db.js :

```
function RawExpression (value,db) {
  this.value = value;
  this.db = value;
}
RawExpression.extend = utils.extend;
RawExpression.prototype.toString = function () {
  return this.value;
}

/**
 * Create a raw expression.
 *
 * @return {RawExpression} The raw expression instance.
 */
Db.prototype.rawExpression = function (value) {
  return new RawExpression(value,this);
};
```
and some change on objectToSet in statement function for  detect RawExpression :

```
Statement.prototype._objectToSet = function (obj) {
  var expressions = [],
      params = {},
      keys = Object.keys(obj),
      total = keys.length,
      key, i, paramName, value;
  for (i = 0; i < total; i++) {
    key = keys[i];
    value = obj[key];
    if (typeof value === 'function') {
      var child = new Statement(this.db);
      child._state.paramIndex = this._state.paramIndex;
      value(child);
      expressions.push(key + ' = (' + child.toString() + ')');
    }
    else if (value instanceof Statement) {
      expressions.push(key + ' = (' + value.toString() + ')');
    }
    else if (value instanceof RID) {
      expressions.push(key + ' = ' + value);
    }
    else if (value && value.__proto__ &&
        value.__proto__.constructor &&
        value.__proto__.constructor.name === "RawExpression") {
      expressions.push(key + ' = ' + value.toString() + '');
    }
    else if (value !== undefined) {
      paramName = 'param' + paramify(key) + (this._state.paramIndex++);
      expressions.push(key + ' = :' + paramName);
      this.addParam(paramName, value);
    }
  }

  if (expressions.length === 0) {
    return false;
  }
  else {
    return expressions.join(', ');
  }
};
```
finally i can write a raw expression in param and using in set statement  :

   .......
let content =  {
                TableID:  db.rawExpression( "sequence('Table_Seq').next()") ; //  the db object now support rawExpression method.
                Notes:""
            };
....
            db.insert().into("BgmTable").set(content) // and execute statements .

so the sequence function renders truely in set statement . 
Welcome to your comments . 

Regards
Saeed Tabrizi

**Comment by saeedtabrizi** [comment]
Hi @maggiolo00 
whats your idea ?

**Comment by maggiolo00** [comment]
hi @saeedtabrizi 

seems god.

**Comment by maggiolo00** [comment]
Hi @saeedtabrizi 

i'm closing this since https://github.com/orientechnologies/orientjs/pull/190 has been merged

Thanks

**Comment by nvtin** [comment]
@saeedtabrizi This is awesome. I got the same issue and thank God, you was here with solution. Good job.
