### ISSUE TITLE
Windows 8.1 npm install / build error

### ISSUE THREAD

**Issue by patricksevat** [orientechnologies/orientjs#193]
Hi all,

I'm new to Orient and I'm trying to set up my Node environment but I keep running into problems with the build process. After running npm install I get the error posted in screenshot.

I have searched for this error a long time, but can't seem to find anything other than some old issues with node-gyp. So I updated Node \ NPM \ node-gyp to see if that helped but it didn't. I guess it has to do with my local env as I was able to install OrientJS on c9.io without errors (besides there not running any OrientDB serv ofcourse ;)).

Also, I found it weird that some methods were unavailable. For example the promise on server.list worked normal, but the promises on server.use or db.create.list gave a 'is not a function'. Same with classname.create.

Orientjs CLI does not seem to be installed either, I have also tried running npm install with an Administrator Command Prompt.

I really would like to continue with Orient, could you perhaps help me?

Running Windows 8.1
OrientDB 2.2.6
OrientJS 2.2.1
Node 4.4.7
Node-gyp 3.4.0

If you want to know anything else let me know!
![orientjs error](https://cloud.githubusercontent.com/assets/16444755/17273866/8a5eefe0-56c6-11e6-866d-e483d9bb7ed2.png)

**Comment by maggiolo00** [comment]
hi @patricksevat 

Can you install  this

http://landinghub.visualstudio.com/visual-cpp-build-tools

and retry?

Thanks

**Comment by patricksevat** [comment]
hi @maggiolo00 ,
Thanks for your reply

Visual C++ Build tools is already installed as part of https://github.com/felixrieseberg/windows-build-tools which is a prerequisite for https://github.com/nodejs/node-gyp .

To test if it's working I've tried installing several packages listed here without problems:
https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#verify-everythings-working

Any other suggestions?
Thanks in advance

**Comment by maggiolo00** [comment]
@patricksevat 

btw the install of orientjs should continue. You will not only use the orientjs-native extension

**Comment by maggiolo00** [comment]
Btw i'm still investigating this issue

https://ci.appveyor.com/project/maggiolo00/orientjs-native

**Comment by StarpTech** [comment]
@maggiolo00 status?

**Comment by maggiolo00** [comment]
@StarpTech 

do you get the same error has here with 2.2.2 of OrientJS ?

https://ci.appveyor.com/project/maggiolo00/orientjs-native

The Win compilation problem are solved on our side.

**Comment by maggiolo00** [comment]
Seems that the problem is with Nan exception.

Can you confirm that you get the same error?

**Comment by StarpTech** [comment]
@maggiolo00 As a i know all build are failed.

**Comment by maggiolo00** [comment]
@StarpTech 

which build?

**Comment by StarpTech** [comment]
@maggiolo00 All build are Red.

**Comment by maggiolo00** [comment]
which build ?

OrientJS?

**Comment by StarpTech** [comment]
Yes, orientjs. https://ci.appveyor.com/project/maggiolo00/orientjs-native

**Comment by maggiolo00** [comment]
@StarpTech 

we were able to build it
https://ci.appveyor.com/project/maggiolo00/orientjs-native

it should work now

**Comment by maggiolo00** [comment]
@patricksevat 
can you test if this works also for you?
Thanks

**Comment by patricksevat** [comment]
@maggiolo00 confirmed, no errors on `npm install orientjs@2.2.2`
Thank you!

**Comment by maggiolo00** [comment]
@StarpTech 

is it working for you?

**Comment by StarpTech** [comment]
yes, it works. Thanky you.

**Comment by Raj-esh** [comment]
Facing exactly same issue..
Running Windows 8.1
OrientDB 2.2.10
OrientJS 2.2.2
Node 6.7
Node-gyp 3.4.0

Should I raise a new issue ?

**Comment by maggiolo00** [comment]
hi @Raj-esh 

which error do you get?

**Comment by Raj-esh** [comment]
Attaching the issues - Warnings about Deserializer
![capture](https://cloud.githubusercontent.com/assets/7304651/19012390/dc2caa56-87d1-11e6-8b31-306c90dbfd16.PNG)
![2](https://cloud.githubusercontent.com/assets/7304651/19012391/e195ce8c-87d1-11e6-9d6b-1943bb3ee000.PNG)

**Comment by tglman** [comment]
hi @Raj-esh,

This seems just warnings, they should not stop your build.
does the install fail ? it seems that after this it should go smoothly.

**Comment by Raj-esh** [comment]
The install was successful with the above warnings. As @tglman mentioned now its working fine. Thanks

**Comment by Raj-esh** [comment]
Actually I am facing the issue when I use node 6.7 I guess.

When I install orientDB with node version as 6.7 I get the issue as in attached:

Somehow its the installation is looking for node-gyp 3.3.1 instead of 3.4, though I have 3.4 installed.

Can you please help me here? 

![image](https://cloud.githubusercontent.com/assets/7304651/19106361/8ad23c62-8b04-11e6-9c9b-1543a704e9f4.png)

**Comment by Raj-esh** [comment]
I identified the problem.

Node.js 6.7 is packed with npm 3.10.3 version, which uses node-gyp 3.3.1. Whereas, npm that is part of node 4.6 uses node-gyp 3.4. Strange..!

And I replaced the node-gyp 3.3.1 with 3.4 and my orientsjs build got successful.
