### ISSUE TITLE
transaction.delete([String|RID|Object] records) should return single value (this)

### ISSUE THREAD

**Issue by agthenbo** [orientechnologies/orientjs#195]
I want to delete related records (e.g. in a LINKLIST) and update the containing record in a single transaction.
Using `transaction.delete` with an array parameter returns a (possibly empty) array with `transaction` (this) in all elements.
This is unexpected (or problematic (or useless)) for chaining transaction commands, e.g.

    var transaction = database.begin()
        .delete(deletedRecord.links)
        .update(deletedRecord)
        .commit();

I would suggest to `reduce` the array parameter to `this`.

**Comment by maggiolo00** [comment]
Why is it problematic?

**Comment by agthenbo** [comment]
If `deletedRecord.links` is never empty, I would need to write

var transaction = database.begin()
    .delete(deletedRecord.links)[0]
    .update(deletedRecord)
    .commit;    

If `deletedRecord.links` may be empty, the resulting array is empty and the chain fails. So a check is required that I don't know how to write in fluent style (please advise).

**Comment by maggiolo00** [comment]
Sure, 

you are right, i didn't see the code.

**Comment by agthenbo** [comment]
Nevermind.

It is the wrong approach anyway. `transaction.delete` with linklist arrays fails with

> {
  "name": "OrientDB.RequestError",
  "message": "Cannot DELETE the record #17:8 because the version is not the latest. Probably you are deleting an old record or it has been modified by another user (db=v1 your=v0)",
  "data": {},
  "previous": [],
  "id": 1,
  "type": "com.orientechnologies.orient.core.exception.OConcurrentModificationException",
  "hasMore": 0
}

The right `@version` cannot be added as `transaction.delete` does only carry forward the RID.
