### ISSUE TITLE
Query reject

### ISSUE THREAD

**Issue by facelessTT** [orientechnologies/orientjs#198]
Hello
subj does not always occures.
In some reasons, If I have 5 connections in pool, and one of them getting wrong syntax query, It gets freezed... so all the following queries are placed to the queue, and not getting executed. So in few hours we have our servers working slower and slower(because more and more connections are getting freezed), and only help is restart services.

```
return self.getQueryString(command, filter)
		    .then(function (queryData) {
			    var queryAsString = stringFormat(queryData.selectStatement, queryData.queryParams);
				var maxQueue = _.max(self.db.server.transport.pool.connections, function(connection) { return connection.queue.length }).queue.length;
			    if (maxQueue) {
				    console.log('waiting for queries: ' + maxQueue);// here is the place we have uncontrolled growth sometimes
			    }
			    return self.db.query(queryData.selectStatement, {
				    params: queryData.queryParams
			    })
			    .then(function (data) {
			        var q = queryAsString;
				    var total = (filter.offset ? filter.offset : 0) + data.length;
				    return Promise.resolve(data);
			    })
			    .catch(function (err) {
return Promise.reject(err);//we newer hit this place during last month or so....
			    })

```

In case if it does matter, we also have event, which seems to fire (when error occures)

	this.db.on("endQuery", function (obj) {
		if (obj.err)
			console.error(obj.err);

		var queryPerformance = obj && obj.perf && obj.perf.query ? obj.perf.query : -1;
		console.log('query performance:' + queryPerformance, 'query-performance');
	});

**Comment by maggiolo00** [comment]
@facelessTT 

do you have some snippet or test to reproduce this issue?

**Comment by facelessTT** [comment]
you can just put any buggy query like 'sdfdfsd select * from v', or 'select from sometable where like "%a%"', and as for me, I dont hit catch in these cases.

**Comment by facelessTT** [comment]
hm.... whats interesting, is sometimes I can reproduce it with just adding 'sdfdsfkjdsfjksdf' to the beginning of query, and sometimes I cant... Yesterday I did, and now I cant...
I'll try to rewrite this place to log first query in queue when growth happens... you can close this issue by now, and I'll come back when I'll get exact steps to reproduce this problem.

**Comment by maggiolo00** [comment]
hi @facelessTT 

i've reproduced the issue.
Seems to be working if you activate the token also with the connection pool

```
 useToken: true,
      pool: {
        max: 5
      }
```

**Comment by maggiolo00** [comment]
@facelessTT 

i'm checking why does it stuck without token

**Comment by facelessTT** [comment]
Oh...thats great... I'll try to add useToken today and see if it'll help.
I was not able to find exact scenario to reproduce this issue... Its just happens with different regular queries.... nothing unusual.... I've started to think about how to handle it..... But I need some help to do it right.
Here is what on my mind, but I need help with implementation: If query is timed out in N seconds, where N is parameter (99,9% of my queries should return in 30 seconds), I wish to reassign quene to another connection (if it is possible, or just forget about them if it is not possible), and close and reopen current connection.
Something like
return db.query(statement, parameters).timeout(N).then(....).catch(Promise.TimeoutError, function(e) {
    PLACEWHEREINEEDHELPWITHHANDLINGITRIGHT
})

**Comment by facelessTT** [comment]
useToken: true helped us. thank you..... but as I understand, its only workaround

**Comment by maggiolo00** [comment]
@facelessTT 

it's not only a  workaround. OrientDB live query works only with token from 2.2.x.

**Comment by maggiolo00** [comment]
@facelessTT 

i've raised that issue that will make the token default for 3.0 version.
https://github.com/orientechnologies/orientjs/issues/213
