### ISSUE TITLE
[FEATURE] Transaction IF & ROLLBACK ,  Sequence  statement support needed. 

### ISSUE THREAD

**Issue by saeedtabrizi** [orientechnologies/orientjs#210]
Is there any sample or documentation for transaction `IF` and `ROLLBACK`  statement support in orientjs ?

**Comment by saeedtabrizi** [comment]
Hi @luigidellaquila 
If there is no any implementation for IF and Rollback or Sequence statements , i'm ready to develop it .

Regards 
Saeed

**Comment by maggiolo00** [comment]
hi @saeedtabrizi 

there is no support for if/rollback and Sequence statements. 
It would be super cool if you can develop it, i can help you that

Thanks
Enrico

**Comment by saeedtabrizi** [comment]
@maggiolo00  Okay. i start a new challenge that i love it.

**Comment by maggiolo00** [comment]
Cool @saeedtabrizi 

ping me if you need help!

**Comment by lvca** [comment]
@saeedtabrizi did you send any PR we missed?

**Comment by saeedtabrizi** [comment]
@lvca already merged as we discussed in https://github.com/orientechnologies/orientjs/issues/232 . this issue can be close but it need to documentation in orientjs . 
I add some test case for supporting 'IF' statement in transaction statements.
