### ISSUE TITLE
[Proposal] Remove the bluebird dependency and use the ES6 promise mechanism for async methods .

### ISSUE THREAD

**Issue by saeedtabrizi** [orientechnologies/orientjs#211]
I think if you remove bluebird dependency and use the builtin ES6 promises we can achieve more performance . 
is there any idea ? welcome to your comments .

**Comment by maggiolo00** [comment]
@saeedtabrizi 

It's a major refactor i think, but it would be nice to switch to ES6 for the next major version of 
OrientJS like 3.0.

**Comment by a-unite** [comment]
Does V8 internal implementation already became faster, than Bluebird?

Because what I see is that http://programmers.stackexchange.com/questions/278778/why-are-native-es6-promises-slower-and-more-memory-intensive-than-bluebird question is still actual.

**Comment by dotmilk** [comment]
Contrary to popular belief bluebird is more than a polyfill-esque choice, it is the fastest of the promise libraries and as mentioned above more lightweight and faster than native promises. I feel the performance of this codebase would suffer if you removed this dependency.
