### ISSUE TITLE
`db.exec` with invalid query stucks.

### ISSUE THREAD

**Issue by Strate** [orientechnologies/orientjs#216]
Try to write some sql, which produce an error:
```
let promise = db.exec("invalid sql is here");
```
that promise will never be rejected or resolved, it become pending to forever.
Am i missed some?

**Comment by Strate** [comment]
*!N.B* This happens only if server connect is pooled!

**Comment by maggiolo00** [comment]
hi @Strate 

try to use the token. It's the current workaround for pooled connection.
In 3.0 it will be enable by default

https://github.com/orientechnologies/orientjs/issues/213

```
const OrientJS = require('orientjs'),
server = OrientJS({ host: 'localhost', port: 2424,  pool : { max : 2}, useToken : true }),
```

**Comment by maggiolo00** [comment]
@Strate 

did you have the change to try the token?

Thanks

**Comment by Strate** [comment]
Yes, thanks!
