### ISSUE TITLE
orientJS and ionic framework

### ISSUE THREAD

**Issue by DThink** [orientechnologies/orientjs#220]
hi, i use the ionic framework to develop my client side app. my question is if orientjs work on the browser side or only in the server side? .
and, if orientjs is not compatible with the client side what is the best solution to comunicate with my server throught javascript by client side?

**Comment by maggiolo00** [comment]
hi @DThink 

orientjs works only in the server side. If you want to communicate with ODB server you can use the HTTP api

http://orientdb.com/docs/2.2/OrientDB-REST.html

**Comment by DThink** [comment]
i read in the orientDB site that for security reason is better to not connect directly a client with the server. now im a bit confused. i think that if i communicate with the server  throught a orientjs script, i have a more slow performance but i see also that i not can authenticate a client by orientjs script.

i not understand well what is the best way to use both (client side and orientjs) to communicate with orientDB

**Comment by maggiolo00** [comment]
@DThink 
usually you don't expose directly ODB server, that could lead to security issues.

The canonical approach is 

Client -> API (node + orientjs) -> ODB

**Comment by maggiolo00** [comment]
Hi @DThink 
i'm closing this since it's not relevant to orientjs
