### ISSUE TITLE
can I use a filter with the query builder?

### ISSUE THREAD

**Issue by grimace** [orientechnologies/orientjs#223]
I'm currently porting from mongo sails where I'm using a filter ( filter is built from a number of optional parameters that come in the request ).  The filter can vary in number of fields and values but is well formed json object.  I'm thinking some thing like this:

var filter = { age:30, hairColor: brown, height:65 };

 var query = this.db.select().from('Person').where(filter);

I haven't found a good example.  Is this possible?

**Comment by grimace** [comment]
yes I can!

var query = db.select().from('Person').where(filter);

totally works!

**Comment by lvca** [comment]
Cool you found it by your own.
