### ISSUE TITLE
Is it possible to use a trigger or Hooks on a DB event

### ISSUE THREAD

**Issue by grimace** [orientechnologies/orientjs#225]
like in this document:

http://orientdb.com/docs/2.2/Hook.html

**Comment by maggiolo00** [comment]
hi @grimace 

those are hooks on the Server. You can write them in java, or use Dynamic hooks
as explained here.

http://orientdb.com/docs/2.2/Dynamic-Hooks.html
From OrientJS are not supported. 

If you want to watch for create/update/delete event you could use live query

http://orientdb.com/docs/2.2/Live-Query.html#livequery-in-nodejs
