### ISSUE TITLE
No option to filter by vertex/class in the API db.record.get

### ISSUE THREAD

**Issue by royalpinto** [orientechnologies/orientjs#229]
No option to filter by vertex/class in the API db.record.get

I could not find any documentation on the second parameter of db.record.get but looking at the [code, I could see an additional parameter to pass options](https://github.com/orientechnologies/orientjs/blob/master/lib/db/record.js#L76-L112). However, there is no option filter by a class name while fetching the record.

Something like this:
`db.record.find('#12:34', {class: users})`

**Comment by maggiolo00** [comment]
hi @royalpinto 

when you have the record id there is not need for filtering with class.
#12:34 identify a record in the database with a specific class

**Comment by royalpinto** [comment]
Hi @maggiolo00,

An example usage in my application: User is trying to access user record by RID using a rest API end point /users/<rid>/. Now in the application, I would like to query the record(with fetch plans), but if suppose given RID is of some other class, how can I prevent it from sending wrong class record.

Sorry, new to OrientDB, may be some other API I should consider using for this use case.

**Comment by maggiolo00** [comment]
hi @royalpinto 

i get your point. If you want to do that you could so something like this

```
db.select().from('#25:0').where({ '@class' : 'Person'}).one().then(function(res){
	console.log(res);
}).catch(function(err){
	console.log(err);	
});
```

**Comment by royalpinto** [comment]
aah okay, will try this one.

Thank you :-)
