### ISSUE TITLE
Support Index engine in orientjs , IF statement , Rollback , IF EXIST , IF Not Exist keywords in statements , Update Typescript definition file (orientjs.d.ts)

### ISSUE THREAD

**Issue by saeedtabrizi** [orientechnologies/orientjs#232]
According to This [doc ](http://orientdb.com/docs/2.0/orientdb.wiki/Custom-Index-Engine.html) we must have a property to define the index engine in orientjs .

is there any implementation ?

**Comment by maggiolo00** [comment]
@saeedtabrizi 

what do you mean by supporting index engine in orientjs?

**Comment by saeedtabrizi** [comment]
@maggiolo00 in orientjs we don't have any access to define  engine name in index create function . 
i'm working on and i add it now .

**Comment by saeedtabrizi** [comment]
@lvca , @luigidellaquila  , @maggiolo00 I'm working on set of feature that we discussed in #210  and **Typescript definition file ( orientjs.d.ts )** compatibility and some enhancement issues on orientjs . in the coming hours i push it , exactly .

-  index , config support engine in create config
-  support for [`if not exist `](https://github.com/orientechnologies/orientdb/issues/3597)    
- `if()` statement in` let` statements for transaction . 
- `rollback` support in transaction  
-  sequence : `create`,`alter`,`drop`
- `spatial` functions and ready types

**Comment by maggiolo00** [comment]
Cool @saeedtabrizi

**Comment by saeedtabrizi** [comment]
@maggiolo00 **it's done**, i test it and everything works fine . i guess this feature be useful for most of developers .  
I planned to add more `sqlfunctions` and `spatial` functions to orientjs and also i will put `MoveVertex` and `CreateLink` features to orientjs in the next week  .

**Comment by lvca** [comment]
@saeedtabrizi wow, it's a lot of stuff. Guys, when can we merge it?

**Comment by saeedtabrizi** [comment]
@lvca We are working locally with the new features that i made by `npm pack`  and our team really happy working with it .

**Comment by lvca** [comment]
Wow, @saeedtabrizi you're becoming the top contributors of the month!

**Comment by maggiolo00** [comment]
Cool @saeedtabrizi 
i will review it now

About observables i think for some feature like live query and the new streaming protocol 
could be the best choice

**Comment by maggiolo00** [comment]
hi @saeedtabrizi 

can we close this?

**Comment by saeedtabrizi** [comment]
Hi @maggiolo00 
certainly yes .
