### ISSUE TITLE
no error thrown on invalid port for connection

### ISSUE THREAD

**Issue by creisle** [orientechnologies/orientjs#238]
orientdb version: 2.2.17
OS: centos6
orientjs version: 2.2.3

I was trying to connect to the orientdb server I had running. Following the example in the documentation I input

    var server = OrientDB({
       host:     'localhost',
       port:     2424,
       username: 'root',
       password: 'root'
    });

then I tried to list the databases 
    
    var dbs = server.list()
        .then(
             function(list){
             console.log('Databases on Server:', list.length);
        });

but nothing print to the console so I assumed there was a connection error and added 

    var dbs = server.list()
        .then(
             function(list){
             console.log('Databases on Server:', list.length);
        }).catch(function(err){
            console.log('error' + err);
        });

but still nothing was printing out. 

I was able to fix this by

    var server = OrientDB({
       host:     'localhost',
       HTTPport:     2424,
       username: 'root',
       password: 'root'
    });

but shouldn't this throw an error??

**Comment by maggiolo00** [comment]
hi @creisle 

do you have some firewall or something that could block the connection?

this one works for me

```js



var OrientDB = require("orientjs");

var server = OrientDB({
 host: 'localhost',
 port: 2424,
 username: 'root',
 password: 'root'
});

server.list().then(function(db){
	console.log(db.length);
}).catch(function(err){
	console.log(err);
})

```

orientjs 2.2.3

OrientDB 2.2.17

**Comment by creisle** [comment]
It is possible. If a firewall were blocking the connection and the connection fails is there a way to check that? (the server isn't a promise object, so I can't do a then/catch)

**Comment by maggiolo00** [comment]
hi @creisle 

were you able to figure out the connection problem?

Thanks

**Comment by creisle** [comment]
I can get it to work with the fix I put in the initial comment (HTTPport v port). However I still can't figure out how to test if I actually succeeded in connecting as it failed silently (did not throw and error when I called OrientDB) when I was using port

**Comment by creisle** [comment]
This works in v3.0.0+
