### ISSUE TITLE
All live queries are triggered even when the select statements refers to different nodes

### ISSUE THREAD

**Issue by RubenVermeulen** [orientechnologies/orientjs#243]
Hello

I'm working with the liveQuery function of orientjs. I noticed that all my live queries are triggered even when the select statement should be monitoring other nodes.

For example

```
db.liveQuery('SELECT FROM User').on('live-update', (res) => { ... });
db.liveQuery('SELECT FROM Animals').on('live-update', (res) => { ... });
```
When I update a user's description I expect the first live query should catch the update and the second live query shouldn't. The first live query does catch the update, but the second live query also catches the update. Is this normal behaviour?

**Comment by maggiolo00** [comment]
Hi @RubenVermeulen 

no it's not normal. 
I saw the code and the signal is dispatched on the db object, so you catch both live update.
In OrientJS 3.0 this has been target since live query are handled now with Observable.
In 2.2x i will provide a fix

Thanks

**Comment by RubenVermeulen** [comment]
Thanks for the quick reply @maggiolo00 

Am I correct that OrientJS 3.0 is still in development? Do you have a timeframe when the next hotfix(es) will be available for 2.2.x?

**Comment by maggiolo00** [comment]
hi @RubenVermeulen 

yes 3.0 it's still in development and it will be out with OrientDB 3.0
For 2.2.x i think this it should be available this week

Thanks

**Comment by maggiolo00** [comment]
Hi @RubenVermeulen 

OrientJS 2.2.5 is out on npm

Thanks

**Comment by RubenVermeulen** [comment]
Thanks @maggiolo00 for the quick bug fix!
