### ISSUE TITLE
IN operator is not working with @rids list

### ISSUE THREAD

**Issue by nomi-ramzan** [orientechnologies/orientjs#246]
Hi I am trying to run this query using orientjs 
> SELECT * FROM items WHERE link_id IN ['#12:1','#12:2','#12:3']`

I am getting empty result But when I am removing quotes from array 
> SELECT * FROM items WHERE link_id IN [ #12:1, #12:2, #12:3 ]

Then its working fine.

Here is my code
```
db.select().from('items')
  .where('link_id IN [:param0,:param1,:param2]')
  .addParams({ param0: '#12:1', param1: '#12:2', param2: '#12:3' })
  .all().then(console.log, console.log)
```
I also checked orientjs is sending these ides with quotes.
How can I solve this problem ?
Thank you

**Comment by maggiolo00** [comment]
hi @nomi-ramzan 

record ids are not strings, that is why that query is not working. In  order to use Record ids with params you can use RecordId object.

```js
const RID = require('orientjs').RID;
...

db.select().from('items')
  .where('link_id IN [:param0,:param1,:param2]')
  .addParams({ param0: new RID('#12:1'), param1: new RID('#12:2'), param2: new RID('#12:3') })
  .all().then(console.log, console.log)

```

Let me know if it helps you
Thanks

**Comment by nomi-ramzan** [comment]
@maggiolo00 Thank you. I will inform you if i will face any problem.
