### ISSUE TITLE
using let variables in transactions outside of from/to/return

### ISSUE THREAD

**Issue by creisle** [orientechnologies/orientjs#247]
OS: centos06
node version: v6.10.0
orientjs version: 2.2.3
orientdb version: orientdb-community-2.2.17

I am trying to build the following (simplified for the purposes of this question) command using the transaction builder

```
BEGIN;
 LET startPos = CREATE vertex v SET  pos = 1;
 LET endPos = CREATE vertex v SET pos = 2;
 LET range = CREATE vertex range SET  start = $startPos, end = $endPos;
 
COMMIT
```
where range is a class with two "link" type attributes (it is expecting @rids as strings). This works when I run it in the orientdb console

my attempt in orientjs
```
this.dbClass.db
                .let('startPos', (tx) => {
                    // create the start position
                    return tx.create('vertex', 'v').set({pos: 1});
                }).let('endPos', (tx) => {
                    // create the end position 
                    return tx.create('vertex', 'v').set({pos: 2});
                }).let('range', (tx) => {
                    //connect the nodes
                    return tx.create('vertex', 'range').set({start: "$startPos", end: "$endPos"});
                }).commit().return('$range').one();
```

this builds the query
```
BEGIN;
 LET startPos = CREATE vertex v SET  pos = 1;
 LET endPos = CREATE vertex v SET pos = 2;
 LET range = CREATE vertex range SET  start = "$startPos", end = "$endPos";
 
COMMIT
```

the quotes on the start and end stop it from working so this is probably not the way to do this (using the set function) but i couldn't find any other ways documented (or from looking at the tests). 

is there a proper way to do such a thing? or should this work?

**Comment by maggiolo00** [comment]
hi @creisle 

you pass start, end as string so they are quoted.

you should not use json object in this case but a custom set  like this

```
return tx.create('vertex', 'range').set("start = $startPos , end = $endPos");
```

That should give you

```
BEGIN
 LET startPos = CREATE vertex v SET pos = 1
 LET endPos = CREATE vertex v SET pos = 2
 LET range = CREATE vertex range SET start = $startPos , end = $endPos
 
COMMIT 
 RETURN $range
```

Thanks

**Comment by creisle** [comment]
great! thank you :)
