### ISSUE TITLE
Nested responses are unavoidable if a record references another record by RID (string or embedded)

### ISSUE THREAD

**Issue by jpstrikesback** [orientechnologies/orientjs#254]
ODB 2.2.18
OJS 2.2.5

The issue is that any record that references another record in the result with a RID property (embedded or string) will return that record as a nested document instead of the RID in that property.

So I am unable to obtain a flat response from any query such a MATCH query that returns a $pathElements list of distinct vertices of different classes (fetch plans may also return multiple vertices and so can be affected).

pretend data:
```python
class post extends V:
  # schemaless props:
  content = string
  author = string # OR embedded when it's a list of authors (when schemaless ODB determines type)
class user extends V:
  # schemaless props:
  name = string
class author extends E:
  # schemaless props:
  timestamp = int
```

pretend query:

```sql
SELECT FROM (
  MATCH {
    class: post,
    as: posts
  } -author-> {
    class: user,
    as: users
  }
  RETURN $pathElements
)

```

what I expect since studio shows a flat list (notice the property author):

``` json
[
  {
    "@rid": "#12:3",
    "@class": "post",
    "content": "Such a great a post",
    "author": "#45:6",
    "out_author": "#34:1"    
  },
  {
    "@rid": "#45:6",
    "@class": "user",
    "name": "Happy",
    "in_author": "#34:1"
  },
  {
    "@rid": "#12:4",
    "@class": "post",
    "content": "Meh post",
    "author": "#45:7",
    "out_author": "#34:2"
  },
  {
    "@rid": "#45:7",
    "@class": "user",
    "name": "Grumpy ",
    "in_author": "#34:2"
  }
]
```

what I get (notice the property author):

``` json
[
  {
    "@rid": "#12:3",
    "@class": "post",
    "content": "Such a great a post",
    "author": {
      "@rid": "#45:6",
      "@class": "user",
      "name": "Happy",
      "in_author": "#34:1"
    },
    "out_author": "#34:1"
  },
  {
    "@rid": "#45:6",
    "@class": "user",
    "name": "Happy",
    "in_author": "#34:1"
  },
  {
    "@rid": "#12:4",
    "@class": "post",
    "content": "Meh post",
    "author": {
      "@rid": "#45:7",
      "@class": "user",
      "name": "Grumpy ",
      "in_author": "#34:2"
    },
    "out_author": "#34:2"
  },
  {
    "@rid": "#45:7",
    "@class": "user",
    "name": "Grumpy ",
    "in_author": "#34:2"
  }
]
```

This may not seem like the biggest deal in this trivial example but in a large graph what we encounter fairly quickly is circular references, which we can remove of course...but that typically leaves deeply nested objects in the first places they were encountered and then a reference to those everywhere else creating unpredictable response formats. that look kinda like a pickaxe.

Because of this fetch plans that return data with references to a RID also cause response formats to become entirely unpredictable.

Yes we could remove string references to other records but that seems a bit silly. It would be far more preferable to actually return what a query requests rather than hydrate any RID with the full record if it's in the result except when a fetch plan indicates that something at some depth should be returned (or excluded for that matter).

**Comment by maggiolo00** [comment]
hi @jpstrikesback 
yes now automatically hydrate any RID. I did open [#219](https://github.com/orientechnologies/orientjs/issues/219) for optionally avoid this. 
I will try to implement this for 2.2.x

**Comment by jpstrikesback** [comment]
Making it optional would be amazing!

**Comment by jpstrikesback** [comment]
Any updates on this?

**Comment by maggiolo00** [comment]
Implemented in the PR
