### ISSUE TITLE
liveQuery: index out of range

### ISSUE THREAD

**Issue by RubenVermeulen** [orientechnologies/orientjs#259]
Hi

I've been experiencing this issue for some time now and I assuming it's a bug in either the driver or in OrientDB itself. 

I'm using the "liveQuery" function in orientjs and on random occasions I get an **index out of range** exception. It's not limited to a single class. It's enough to trigger the problem with a live query without any validation. For example just use following code.

```javascript
db.liveQuery('LIVE SELECT FROM User')
  .on('live-update', res => {console.log('updated');});
```

The exception is as follows:
```
RangeError: index out of range
    at checkOffset (buffer.js:622:11)
    at Buffer.readUInt8 (buffer.js:660:5)
    at Operation.consume (/home/besports/gold-mine-js-web-socket/node_modules/orientjs/lib/transport/binary/protocol33/operation.js:383:34)
    at Connection.process (/home/besports/gold-mine-js-web-socket/node_modules/orientjs/lib/transport/binary/connection.js:390:17)
    at Connection.handleSocketData (/home/besports/gold-mine-js-web-socket/node_modules/orientjs/lib/transport/binary/connection.js:301:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```
On further investigation I found that when the offset in `orientjs/lib/transport/binary/protocol33/operation.js:383:34` reaches the value of 10 the exception gets thrown. 

**Versions**
OrientDB: 2.2.20 (community edition)
OrientJS: 2.2.5

**Comment by maggiolo00** [comment]
Hi @RubenVermeulen 

let me try to replicate it

Thanks

**Comment by maggiolo00** [comment]
Can you paste here your connection configuration?

do you use pool with token?

**Comment by RubenVermeulen** [comment]
```
{
    host: 'localhost',
    port: 2424,
    name: 'my-database',
    username: 'admin',
    password: 'admin',
    useToken: true
}
```

**Comment by maggiolo00** [comment]
Do you use directly the ODatabase Api?

do you have a script or a way to reproduce it?

**Comment by RubenVermeulen** [comment]
Yes, I use the ODatabase.

```
import orientdb from 'orientjs';
import Config from '../config';

export default new orientdb.ODatabase(Object.assign({useToken: true}, Config.database));
```
The object assign return the following:
```
{
    host: 'localhost',
    port: 2424,
    name: 'my-database',
    username: 'admin',
    password: 'admin',
    useToken: true
}
```

**Comment by RubenVermeulen** [comment]
Did you manage to reproduce the exception and find a solution?

**Comment by maggiolo00** [comment]
Hi @RubenVermeulen 

i may have been able to reproduce it.  I have to confirm it yet. 
But i think there is a bug in some case in buffer handling. 
I will work on it ASAP, and let you know

Thanks

**Comment by RubenVermeulen** [comment]
Thanks for the update!

**Comment by maggiolo00** [comment]
hi @RubenVermeulen 

just a quick update. I'm working on a fix.
It should be done for Monday. I will keep you posted

Thanks

**Comment by maggiolo00** [comment]
Hi @RubenVermeulen 
it should be fixed. I'm running some intensive tests. If all goes well 
i will publish the new version tomorrow.

Thanks

**Comment by RubenVermeulen** [comment]
Thanks for the update. I appreciate the effort you're putting into this.

**Comment by Neglexis** [comment]
Hey @maggiolo00, @cuvelierm and me have taken over @RubenVermeulen's project at our company. I went ahead and pulled the package from git to see if it was solved for our case, and haven't had any crashes so far, so can confirm that the update solved our issues!

**Comment by maggiolo00** [comment]
hi @Neglexis 

thanks for the updates. I will publish the new package then
