### ISSUE TITLE
query() - create cluster using params

### ISSUE THREAD

**Issue by cityy** [orientechnologies/orientjs#260]
Hey folks,
I was wondering if it is possible to create a cluster using query() with a parameter.

Example:
```
db.query('create cluster :mycluster', 
  {
   params:{
        mycluster: 'someText'
   }
  }
);
```
Results in the following sql query:
`create cluster "someText"`

Now "someText" is a string literal and orientdb wants something that looks like:
`create cluster someText`

Is this just not possible or am I missing some knowledge here? I haven't found a solution investigating so far unfortunately.

**Comment by cityy** [comment]
Any chance? Sorry for bugging and being impatient. I would really appreciate a short feedback whether it's a limitation of the api or what direction I need to look in to get an idea about how to solve this.

**Comment by cityy** [comment]
I think I eventually figured I was just approaching it the wrong way.

```
let query = 'create cluster " + 'someText';
db.query(query);
```

This seems to be working. Sorry for bloating the issues list.

**Comment by maggiolo00** [comment]
Hi @cityy 

sorry for the late response. You were doing it right but the current version of the driver has some limitation on  params handling. This is resolved in the development version that will be OrientJS 3.0.

I will try to backport it to 2.2.x

**Comment by maggiolo00** [comment]
The current workaround yes it's this

```
let query = 'create cluster " + 'someText';
db.query(query);
```

**Comment by cityy** [comment]
Thanks for getting back to me though!
