### ISSUE TITLE
Assertion `next > 0' failed

### ISSUE THREAD

**Issue by RubenVermeulen** [orientechnologies/orientjs#261]
Hi

When performing updates on collection which are monitored with the `liveQuery` method I get following exception.

```
node: ../lib/native/helpers.cpp:22: void Orient::ContentBuffer::prepare(int): Assertion `next > 0' failed.
```
I'm connecting to a remote OrientDB server.

**Versions**
OrientDB: 2.2.20 (community edition)
OrientJS: 2.2.5

**Comment by maggiolo00** [comment]
Hi @RubenVermeulen 

i think it could be related to

https://github.com/orientechnologies/orientjs/issues/259

**Comment by RubenVermeulen** [comment]
Could be yes, I'm just making sure you get an overview of all the exceptions related to the live queries.

**Comment by cuvelierm** [comment]
Just tested the new release you made for fixing this error. The error is still showing up, although it moved from the console to a C++ error dialog.


![image](https://user-images.githubusercontent.com/8874455/27830982-10894f72-60c9-11e7-8610-5dbacb26ad7f.png)

Any further help on fixing this would be greatly appreciated.

**Comment by maggiolo00** [comment]
hi @cuvelierm 

i was not able to reproduce this with the fix. If you have an hint on how to reproduce it it would help me a a lot for fixing it

Thanks

**Comment by maggiolo00** [comment]
Do you have also the JS stack?

**Comment by maggiolo00** [comment]
Does this happen on live query or normal query?

**Comment by cuvelierm** [comment]
Node version 8.1.1 
On live queries
No, I do not have a JS stack, somehow I got a C++ Error box showing up.

**Comment by maggiolo00** [comment]
Let me try with that node version

**Comment by maggiolo00** [comment]
Do you have more less the content of that kind of records?

How many live query are you doing with a single db instance?

**Comment by cuvelierm** [comment]
the single instance is doing approximately 50 livequeries

**Comment by maggiolo00** [comment]
Ok on different entity ?

**Comment by cuvelierm** [comment]
There is one livequery for each collection, the routing of updates, inserts and deletes is what my server currently should be doing.

**Comment by maggiolo00** [comment]
Ok Thanks

**Comment by maggiolo00** [comment]
@cuvelierm 

how often do you get this exception? Is it easily reproducible in your environment?

**Comment by cuvelierm** [comment]
about once every 2 minutes, so yeah pretty easily

**Comment by Neglexis** [comment]
As an update, I've now also connected to the same server with @cuvelierm's package, and I'm seeing the updates without my server crashing

**Comment by maggiolo00** [comment]
@Neglexis 

so it's not crashing for you with the fix?

@cuvelierm 
that would be awesome. Let me try some other intensive test  first then if i'm not able to reproduce it

**Comment by Neglexis** [comment]
Correct!

**Comment by maggiolo00** [comment]
That is strange. same node version?

what about OS?

**Comment by cuvelierm** [comment]
I'm on Windows 10, @Neglexis uses mac OSX.
Both on Node 8.1.1 and npm 5.0.4

**Comment by cuvelierm** [comment]
It just stopped happening after a restart, also redid all npm modules and now it seems to work. Sorry for the hassle.

**Comment by maggiolo00** [comment]
Ok keep me updated if you see it again

Thanks

**Comment by maggiolo00** [comment]
Hi @cuvelierm 

if you can confirm that you are not getting this error anymore, i will publish
the new version of the driver

Thanks

**Comment by cuvelierm** [comment]
Yes I do can confirm, did not get any further errors yesterday nor today.
Thank you for the quick response.

**Comment by maggiolo00** [comment]
@cuvelierm 

Thanks
