### ISSUE TITLE
libc++abi.dylib: terminating with uncaught exception of type Orient::parse_exception

### ISSUE THREAD

**Issue by RubenVermeulen** [orientechnologies/orientjs#262]
Hi

When performing updates on collection which are monitored with the liveQuery method I get following exception.

```
libc++abi.dylib: terminating with uncaught exception of type Orient::parse_exception
```
I'm connecting to a remote OrientDB server.

**Versions**
OrientDB: 2.2.20 (community edition)
OrientJS: 2.2.5

**Comment by maggiolo00** [comment]
Also here it should be related to

https://github.com/orientechnologies/orientjs/issues/259
