### ISSUE TITLE
Query Builder: create() Cluster support?

### ISSUE THREAD

**Issue by cityy** [orientechnologies/orientjs#263]
As far as I can see it is currently not possiblet to `create()` an edge in a specifiec cluster. For vertices you can use `insert()` as an alternative but for edges there doesn't seem to be one?

**Comment by maggiolo00** [comment]
Hi @cityy 

there is no direct support for cluster with fluent api but you can do this.

```
db.create('EDGE',"E CLUSTER e_1").from("#9:0").to("#9:1").one().then(function(result){
		console.log(result);
});
```

**Comment by cityy** [comment]
Cool, thanks!
