### ISSUE TITLE
Setting attributes to query result records/objects.

### ISSUE THREAD

**Issue by royalpinto** [orientechnologies/orientjs#265]
What would be the best way of traversing the result object, processing and adding additional information to the query result records.
#### Scenario:
I have songs(Vertex=Song) and followers(Vertex=User). When follower follows a song, I need to store followed date information too in the edge. Something like
```
Song(Name=Bob)-> FollowedBy(Date=2017-07-10)->Song(Name=Cinderella) 
```
The Test Data:
```
User: John Song: Cinderella Date { Date: 2017-07-20T00:00:00.000Z }
User: John Song: Fairy Tale Song Date { Date: 2017-07-25T00:00:00.000Z }
User: Bob Song: Fairy Tale Song Date { Date: 2017-07-10T00:00:00.000Z }
User: Bob Song: Cinderella Date { Date: 2017-07-15T00:00:00.000Z }
```
Now, I am trying to query these records and traverse them and put them in to a list. While processing each user, I want to update a new property `followedSongs` as an array (each item should be a song with an additional property `followedDetails`) of songs user followed.

Here is my code snippet:
```
.then((users) => {
    let result = users.map((user) => {
        if (user.in_FollowedBy) {
            user.followedSongs = user.in_FollowedBy.all().map((edge) => {
                let song = edge.out;
                song.followDetails = {
                    'Date': edge.Date,
                };
                // Here I get the proper information printed
                console.log('User:', user.Name, 'Song:', song.Name, 'Date', song.followDetails);
                return song;
            });
        }
        return user;
    });
    console.log('After Transforming...')
    result.forEach((user) => {
        console.log('User===> ', user.Name);
        user.followedSongs.forEach((song) => {
            // Here followDetails will always be the last edge of a particular song...
            console.log('Song:', song.Name, ', Date:', song.followDetails.Date);
        });
    });
})
```

Output:
```sh
User: John Song: Cinderella Date { Date: 2017-07-20T00:00:00.000Z }
User: John Song: Fairy Tale Song Date { Date: 2017-07-25T00:00:00.000Z }
User: Bob Song: Fairy Tale Song Date { Date: 2017-07-10T00:00:00.000Z }
User: Bob Song: Cinderella Date { Date: 2017-07-15T00:00:00.000Z }
After Transforming...
User===>  John
Song: Cinderella , Date: 2017-07-15T00:00:00.000Z # SHOULD HAVE BEEN 2017-07-20...
Song: Fairy Tale Song , Date: 2017-07-10T00:00:00.000Z # SHOULD HAVE BEEN 2017-07-25..
User===>  Bob
Song: Fairy Tale Song , Date: 2017-07-10T00:00:00.000Z
Song: Cinderella , Date: 2017-07-15T00:00:00.000Z
```

What could be the issue here ? I can create a new object and copy all the objects rather than assigning to the query records, but that would be painful as I have many fields.

Here is the complete code script:
https://gist.github.com/royalpinto/d6793279340e5b1a41b6bb5e684460a9

The DB export: 
[circular.gz](https://github.com/orientechnologies/orientjs/files/1139962/circular.gz)

**Comment by maggiolo00** [comment]
hi @royalpinto 

 OrientJS resolve records in result set in order to rebuild in memory relationships between objects. That means that if you modify the song instance associated to `Bob` you will also modify the instance associated to Bob. To avoid that you can create a new Song Object

in map like this

```JS
 let song = Object.assign({},edge.out,{
                    followDetails : {
                        'Date': edge.Date,
                    }
                });
```

**Comment by royalpinto** [comment]
Hi @maggiolo00 ,

Thanks for your suggestion. Will do a quick test and come back to you on this.

**Comment by royalpinto** [comment]
Hi @maggiolo00 ,

Your suggestion worked. Thanks again!
