### ISSUE TITLE
Unable to handle maximum number of concurrent connections Error/Warning.

### ISSUE THREAD

**Issue by royalpinto** [orientechnologies/orientjs#266]
Hi,

Problem:
When maximum connections to the db server has reached and is not allowing any allowing any new connections, `orientjs` simply exits the process with exit code `0`. How do we handle this error ?

Script:
```js
#!/usr/bin/env node
let SERVER_HOSTNAME = 'localhost';
let SERVER_PORT = 2424;
let SERVER_USERNAME = 'admin';
let SERVER_PASSWORD = 'admin';
let DATABASE_NAME = 'mydb';
let DATABASE_USERNAME = 'root';
let DATABASE_PASSWORD = 'password';
const QUERY = `SELECT * FROM V LIMIT 1`;


const orientjs = require('orientjs');
const server = orientjs({
    host: SERVER_HOSTNAME,
    port: SERVER_PORT,
    username: SERVER_USERNAME,
    password: SERVER_PASSWORD,
});

const db = server.use({
     name: DATABASE_NAME,
     username: DATABASE_USERNAME,
     password: DATABASE_PASSWORD,
});

let test = () => {
    return db
    .query(QUERY)
    .then((data) => {
        console.log('Query Result:', data);
    })
    ;
};

test()
.then(() => {
    console.log('OK');
    server.close();
})
.catch((err) => {
    console.error(err.message || err);
    server.close();
})
;
```

This script silently exists without any error message when maximum connections limit is reached.
I can see error from orientdb log file:
```bash
WARNI Reached maximum number of concurrent connections (max=1000, current=1000), reject incoming connection from /127.0.0.1:55705 [OServerNetworkListener]
```

**Comment by royalpinto** [comment]
Ideally should have printed wither `OK` in success case or printed an error in case of failure. But nothing get's printed.
I also tried adding an error event listener to server but no luck:
```js
server.transport.connection.on("error", function(err){
    logger.error(err);
});
```

**Comment by maggiolo00** [comment]
hi @royalpinto 

how do you pass the 1000 sessions limit?

Do you have an app running and the run this script?

**Comment by maggiolo00** [comment]
@royalpinto 

let me try to reproduce it. I will keep you updated

Thanks

**Comment by maggiolo00** [comment]
Hi @royalpinto 

i've reproduced. I'm working on a fix
