### ISSUE TITLE
The field 'FIELD' has been declared as EMBEDDED but an incompatible type is used

### ISSUE THREAD

**Issue by royalpinto** [orientechnologies/orientjs#268]
OreintDB Version: `2.2.21`

With OrientJS `2.2.6`, unable to insert record with object as a property. It throws an error message:
`message: 'The field \'User.info\' has been declared as EMBEDDED but an incompatible type is used. Value: {}\r\n\tDB name="embeddedtest"'`

It was working fine with OrientJS `2.1.11`.

The complete script:
```js
let SERVER_HOSTNAME = 'localhost';
let SERVER_PORT = 2424;
let SERVER_USERNAME = 'admin';
let SERVER_PASSWORD = 'admin';
let DATABASE_NAME = 'embeddedtest';
let DATABASE_USERNAME = 'root';
let DATABASE_PASSWORD = 'password';

const orientjs = require('orientjs');

const server = orientjs({
    host: SERVER_HOSTNAME,
    port: SERVER_PORT,
    username: SERVER_USERNAME,
    password: SERVER_PASSWORD,
});

const db = server.use({
     name: DATABASE_NAME,
     username: DATABASE_USERNAME,
     password: DATABASE_PASSWORD,
});


let User;
db.class.create('User', 'V')
.then((klass) => {
    User = klass;
    return User.property.create([{
       name: 'name',
       type: 'string',
    }, {
       name: 'info',
       type: 'embedded',
    }]);
})
.then(() => {
    return User.create({
       name: 'Bob',
       info: {},
    });
})
.then((user) => {
    console.info('Created one user:', user);
})
.catch(console.error)
;
```

May be EMBEDDED is not the suitable type for JS Object ?

**Comment by maggiolo00** [comment]
hi @royalpinto 

let me check

**Comment by maggiolo00** [comment]
Hi @royalpinto 

`EMBEDDED` are supported but they means "Embedded Document"  usually with a class

if you want to use them you should use this syntax

```
return User.create({
       name: 'Bob',
       info: { "@type" : "d"},
    });
```

Otherwise you can just use "EMBEDDEDMAP" instead of "EMBEDDED"

**Comment by royalpinto** [comment]
@maggiolo00 Thanks for the suggestion.

I think `EMBEDDEDMAP` will be easier for my scenario.

However, a quick question regarding the first option:
// data with an additional property '@type' ?
```js
return User.create({
       name: 'Bob',
       info: {
           // actual data
           // .
           // .
           gender: "male", // example
           "@type" : "d",
       },
    });
```

**Comment by maggiolo00** [comment]
@royalpinto 

yes

**Comment by royalpinto** [comment]
Thanks @maggiolo00
