### ISSUE TITLE
[FEATURE,TYPESCRIPT,DOCUMENTATION] An update for orientjs typescript definition file . 

### ISSUE THREAD

**Issue by saeedtabrizi** [orientechnologies/orientjs#269]
Hi dear **OrientDB** and **Orientjs** users .

I'm pleased to say a new update for **orientjs** definition type has been published in **npm** repository  by the following address  : [@types/orientjs v3.0.0](https://www.npmjs.com/package/@types/orientjs).
for using the latest orientjs definition type file you can use the following command in your typescript project .

- `npm install @types/orientjs --save-dev` .

Notes : some functionalities like the `Sequences` and `IF` in **transaction** has been accessible in the next orientjs release . (I guess in orientjs version 3.0.0) .

I have update orientjs.d.ts file in pull request #270 . 

Good luck .
Saeed Tabrizi .

**Comment by maggiolo00** [comment]
hi @saeedtabrizi 
thanks
I've just merged the PR
