### ISSUE TITLE
nativeDeserializer.deserialize is not a function

### ISSUE THREAD

**Issue by leonliang33** [orientechnologies/orientjs#274]
Trying to use the OrientJS on an electron-redux-react project but I keep getting this error. The code works when copy and pasting into the electron console but not through react?

 
   var server = OrientDB({
      host:       'localhost',
      port:       2424,
      username:   'root',
      password:   'root'
    });

    var db = server.use({
      name:     'WebResults',
      username: 'admin',
      password: 'admin'
    });

    db.query('SELECT from Results').then((res)=>{
         console.log(res);
    })

deserializer-binary.js:52 
Uncaught TypeError: Cannot read property '@class' of null
deserialize @ deserializer-binary.js:52
(anonymous function) @ operation.js:784
Operation.parseBytes @ operation.js:685
Operation.consume @ operation.js:487
Connection.process @ connection.js:410
Connection.handleSocketData @ connection.js:301
emitOne @ events.js:96emit @ events.js:188
readableAddChunk @ _stream_readable.js:176
Readable.push @ _stream_readable.js:134
onread @ net.js:543

**Comment by maggiolo00** [comment]
hi @leonliang33 

if you use this in a single  file `index.js` with node does it work?

Can you check if you have installed in node_modules `orientjs-native` ?

Can you help me on the setup with `electron-redux-react` in order to reproduce this?

**Comment by leonliang33** [comment]
I just checked and I do have the orients-native installed.
It was running from a component, but I just moved it to the root index.js but I still get the same problem.

Stripping unnecessary code down the index.js is simply 
`
initialStore = {
}
const store = configureStore(initialState);
const history = syncHistoryWithStore(hashHistory, store.store);

var OrientDB = require('orientjs');
var base64 = require('base-64');

var server = OrientDB({
 host:       'localhost',
 port:       2424,
 username:   'root',
 password:   'root'
});

var db = server.use({
 name:     'WebResults',
 username: 'admin',
 password: 'admin'
});

console.log(db)
db.query('SELECT from Results').then((res)=>{
     console.log(res);
})


render(
  <Provider store={store.store} persistor={store.persistor}>
    <Router history={history} routes={routes} persistor={store.persistor}/>
  </Provider>,
  document.getElementById('root')
);
`

**Comment by maggiolo00** [comment]
Hi @leonliang33 

did you use a starter kit for `electron-redux-react`?

can you advice one so i can boot up the environment for testing?

Thanks

**Comment by leonliang33** [comment]
Yeah, I believe I used this one for boilerplate:
https://github.com/chentsulin/electron-react-boilerplate

**Comment by maggiolo00** [comment]
ok thanks

**Comment by maggiolo00** [comment]
Hi @leonliang33 

i've reproduce it.
i think the main problem is that orientjs rely on a native extension of nodejs written c++.
Let me investigate more

Thanks

**Comment by maggiolo00** [comment]
Hi @leonliang33 

i've found the solution with that boilerplate. Somehow webpack + native extension has problem. 
So the key is to declare the `orientjs` dependency in `./app/package.json`

That solves the issue. By digging i've found the solution here.

https://github.com/amilajack/erb-sqlite-example#how-it-works
