### ISSUE TITLE
[Enhancement]  Migration files not listed when using typescript tsnode tool .

### ISSUE THREAD

**Issue by saeedtabrizi** [orientechnologies/orientjs#275]
Hi , Many of typescript developers may needed to run their project via [ts-node](https://www.npmjs.com/package/ts-node) . it's a tool to making rapid development and debugging in typescript envionment . 
So when we use the **orientjs** with **ts-node** everything works fine but  there is an exception for **migration** files . 
As i traced migration files be tested in **manager.js** file with the following function :

```
MigrationManager.prototype.listAvailable = function () {
  return fs.readdirAsync(this.dir)
  .bind(this)
  .filter(function (filename) {
    return /^m(\d+)_(\d+)\_(.*)\.js$/.test(filename);
  })
  .map(function (filename) {
    return filename.slice(0, -3);
  });
};
```
And that not listed **.ts** files for ts-node environment exactly  . 

So if we change the test regex to the following style the` .js` and `.ts` files supported by **orientjs** and **tsnode**  :

```
MigrationManager.prototype.listAvailable = function () {
  return fs.readdirAsync(this.dir)
  .bind(this)
  .filter(function (filename) {
    return /^m(\d+)_(\d+)\_(.*)\.[jt]s$/.test(filename);
  })
  .map(function (filename) {
    return filename.slice(0, -3);
  });
};
```
I hope you enjoy it . 

Saeed Tabrizi.

**Comment by maggiolo00** [comment]
hi @saeedtabrizi 

do you have an open PR for this, or i can just copy your mentioned commit?

Thanks

**Comment by saeedtabrizi** [comment]
Hi @maggiolo00 
I have PR in https://github.com/orientechnologies/orientjs/pull/276 but failed to coverage . please review it . 
Thanks 
Saeed Tabrizi .

**Comment by maggiolo00** [comment]
@saeedtabrizi  PR Merged. 

Thanks
