### ISSUE TITLE
Not possible to use server after db = server.use?

### ISSUE THREAD

**Issue by maggiolo00** [orientechnologies/orientjs#279]
https://stackoverflow.com/questions/46536616/not-possible-to-use-server-after-db-server-use

**Comment by jpstrikesback** [comment]
Previously I was able to do this:

```javascript
      ... some async function
      const dbServer = require('orientjs')(connectionSettingsObjectWithEverythingNecessary)
      const dbExists = await dbServer.exists(someDataBaseName)
      ...
```

dbServer.exists now throws an exception on server credentials.

Any tips?

**Comment by maggiolo00** [comment]
Hi @jpstrikesback 

which error do you get?

Do you have this problem with the latest release of orientjs 2.2.7?

**Comment by jpstrikesback** [comment]
I'll paste the exact error here soon, but yes it is specific to v2.2.7, when I pinned to 2.2.6 there is no error.

**Comment by maggiolo00** [comment]
Ok @jpstrikesback

**Comment by jpstrikesback** [comment]
turns out this is user error... we had some wrong credentials in there, sorry to waste your time.

**Comment by Eric24** [comment]
@lvca - Wait a minute. This may have been user error on @jpstrikesback 's part, but this is a real bug that I originally reported.
