### ISSUE TITLE
Fully support the REST API

### ISSUE THREAD

**Issue by phpnode** [orientechnologies/orientjs#28]
_From @phpnode on April 30, 2014 21:24_

The beginnings of REST support were added in #31 but it's a long way from being usable. It's important that we implement a consistent API for both REST and binary transports, but unfortunately the results of REST calls for certain operations do not map 1 - 1 with the same operations in the binary protocol.

Things to do (in order):
- [ ] Implement a `process()` method in the REST and binary protocol operations which smooths over the differences between the two.
- [ ] Implement the remaining REST operations
- [ ] Documentation
- [ ] Try browserifying it

_Copied from original issue: codemix/oriento#44_

**Comment by maggiolo00** [comment]
Not valid anymore. 

In the new OrientJS version the rest api support has been dropped

https://orientdb.com/docs/last/orientjs/OrientJS-beta.html
