### ISSUE TITLE
UPDATE x ADD list = {"ddd":4} fails

### ISSUE THREAD

**Issue by Eric24** [orientechnologies/orientjs#285]
On ODB 2.2.29, a record that contains:
`list: [{"xxx":1},{"zzz":3},{"yyy":2}]`

After doing:
`UPDATE x ADD list = {"ddd":4}`

I would expect the result to be:
`list: [{"xxx":1},{"zzz":3},{"yyy":2},{"ddd":4}]`

But the result is:
`list: [{"xxx":1},{"zzz":3},{"yyy":2},4]`

**Comment by luigidellaquila** [comment]
Hi @Eric24 

It was a bug, I just pushed a fix for this. The fix will be released with 2.2.31

Thanks

Luigi
