### ISSUE TITLE
 Cannot UPDATE the record

### ISSUE THREAD

**Issue by tiagodavi** [orientechnologies/orientjs#287]
Does anyone know why it happens?

OrientDB.RequestError: Cannot UPDATE the record #87:11 because the version is
not the latest. Probably you are updating an old record or it has been modified by another
user (db=v7 your=v6)

What should I do to avoid it?

Thanks.

**Comment by luigidellaquila** [comment]
Hi @tiagodavi 

This is the typical error due to optimistic transactions and concurrent updates.
Probably you are updating the same record from two different threads/processes, so one of the two fails because it has an old version of the record.

If you could share some more details about how you are doing these updates, it would help us give you some more specific advice

Thanks

Luigi

**Comment by tiagodavi** [comment]
Javascript is single thread so it's to be more than one threads. I have been using PM2 in order to create diferent processes and that might be the problem.  but Shouldn't the database deal with concurrent processes by itself? 

Thanks

**Comment by luigidellaquila** [comment]
hi @tiagodavi 

No, the database does not automatically merge changes.  

Here you can find some docs that explain how it works:
http://orientdb.com/docs/2.2.x/Transactions.html
http://orientdb.com/docs/2.2.x/Concurrency.html

You can easily fix the problem with a commit/retry approach, at application level or using a batch script (See http://orientdb.com/docs/2.2.x/SQL-batch.html)

I hope it helps

Thanks

Luigi

**Comment by tiagodavi** [comment]
Nice. I'll check it out. Thank You.

**Comment by luigidellaquila** [comment]
Hi @tiagodavi 

Did you have a chance to check the resources I provided? Is this issue still relevant?

Thanks

Luigi

**Comment by vikram-shityalkar** [comment]
I have quick question on this thread, suppose I am connecting from two different servers to single database  which means two different connections, still the same issue will occur?

**Comment by luigidellaquila** [comment]
Hi @vikram-shityalkar 

Optimistic locking (and ConcurrentModificationException) is intended specifically to guarantee a transactional behavior when multiple applications/servers/clients connect to the same database, so yes, if you have two servers that manipulate the same data concurrently, you have to manage this kind of exceptions

I hope it helps

Thanks

Luigi
