### ISSUE TITLE
Accented characters are not correctly parsed

### ISSUE THREAD

**Issue by UltraMarco** [orientechnologies/orientjs#291]
`SELECT FROM Utente WHERE identità=:id AND attivo=true`

In OrientDB Studio this query is ok, but when executing with OrientJS with binary transport, I get this error:

`com.orientechnologies.orient.core.sql.parser.TokenMgrError: Lexical error at line 1, column 33.  Encountered: "\u00e0" (224), after : ""`

the character at column 33 is the "**à**" (\u00e0)

**Comment by UltraMarco** [comment]
OrientDB 2.2.30 and OrientJS 2.2.7

**Comment by luigidellaquila** [comment]
Hi @UltraMarco 

Special characters are allowed in indentifiers, but you have to back-tick quote them:

```
SELECT FROM Utente WHERE `identità`=:id AND attivo=true
```

I hope it helps

Thanks

Luigi

**Comment by UltraMarco** [comment]
Perfect, thanks.

Marco

Il 16 gen 2018 12:40 PM, "luigidellaquila" <notifications@github.com> ha
scritto:
