### ISSUE TITLE
Queries get's queued up and executes one after the other

### ISSUE THREAD

**Issue by royalpinto** [orientechnologies/orientjs#295]
## Expected behavior  
I am executing 2 queries from OrientJS library from a single NodeJS process. Both queries start at the same time (one after the other immediately). The first query is bit huge and takes a while to get the result. The second query is really small and should not take a long time (When being executed alone, takes < 100ms), but get's completed only after the first one, hence takes a long time.

## Actual behavior  
It takes a long time to get the second (small) query to complete and completes only after the first query completes.
I have put below log statements to see if NodeJS process get's blocked but it doesn't get's blocked. 
```
setInterval(() => {
    console.log('PING');
}, 500);
```

It seems like, either OrientDB queues up all the queries and runs one after the other, or OrientJS queues it up.

## Steps to reproduce  
Here a code snippet which reproduces the issue. The sample outputs are given in the comments.
https://gist.github.com/royalpinto/43218842a80914b04c9067f5bd8dab1c

> Not sure if it is an issue with OrientJS or OrientDB

**Comment by maggiolo00** [comment]
Duplicated here
https://github.com/orientechnologies/orientdb/issues/8079

**Comment by nmeeda** [comment]
why did we close this item? what is the solution for this, we are facing same issue, I tried creating connection each request and increased pool size  also tried usertoken, nothing worked, please let me know the solution.

**Comment by wolf4ood** [comment]
Hi @nmeeda which version of orientjs and orientdb are you using?

Thanks
