### ISSUE TITLE
Empty string values are not saved

### ISSUE THREAD

**Issue by igasparetto** [orientechnologies/orientjs#296]
In Studio I can set a string attribute to be empty or "".
OrientJS seems to be ignoring the value completely.
We have performed many tests here and it looks to be a bug in the drive.
Thanks

**Comment by maggiolo00** [comment]
Hi @igasparetto 

which api do you use for setting the value?

Thanks

**Comment by igasparetto** [comment]
Hi @maggiolo00

Not sure I understood the question.

We have our own API. We use NodeJS. OrientJS connects to the DB and runs the required actions (insert, update, etc).

In Studio, if I run this query, it updates the record:
`select from MyClass`
`{
    "result": [
        {
            "@type": "d",
            "@rid": "#262:0",
            "@version": 3,
            "@class": "MyClass",
            "a": "test",
            "b": "#37:3",
            "@fieldTypes": "b=x"
        }
    ],
    "notification": "Query executed in 0.036 sec. Returned 1 record(s)"
}`

Then update
`update #262:0 set a = ""`

Then, the select again
`{
    "result": [
        {
            "@type": "d",
            "@rid": "#262:0",
            "@version": 4,
            "@class": "MyClass",
            "a": "",
            "b": "#37:3",
            "@fieldTypes": "b=x"
        }
    ],
    "notification": "Query executed in 0.046 sec. Returned 1 record(s)"
}`

In our API, we run the same update but using the OrientJS syntax:
`db.update('#262:0')
   .set({
      a: ''
   }).one();`

And then the select...
The result of "a" is "test", but it should be an empty string "".

Class MyClass has 2 parameter with no default values. "a" is of type String, b of the type Link.
We found out that null sets the attributes to null.

Are you able to replicate it?

Thanks

**Comment by igasparetto** [comment]
Kill me.
Problem in my code.
Please close this ticket.
