### ISSUE TITLE
Active connections doesn't limit to pool.max

### ISSUE THREAD

**Issue by royalpinto** [orientechnologies/orientjs#297]
OrientDB: 2.2.31 Enterprise
Java: 1.8
OrientJS: 2.2.7, 2.1.11

With below config number of connections should be limited to 10 but they go more than that. With 100 parallel queries, I could see 100 + 1(Studio) connections.
```
const server = orientjs({
    host: SERVER_HOSTNAME,
    port: SERVER_PORT,
    username: SERVER_USERNAME,
    password: SERVER_PASSWORD,
    useToken : true,
    pool : {
        max : 10
    }
});
```

Even without using the pool like below, connections are really huge. With 100 parallel queries, I could see 100 + 1(Studio) connections but all queries get's executed and comes back with result serially.
```
const server = orientjs({
    host: SERVER_HOSTNAME,
    port: SERVER_PORT,
    username: SERVER_USERNAME,
    password: SERVER_PASSWORD,
});
```

Also, where do I set the max number of connections OrientDB can allow?

Code Snippet: https://gist.github.com/royalpinto/def7a2fe214e98cc07fa708d67c20b43

**Comment by royalpinto** [comment]
Any updates/comments on this?

**Comment by maggiolo00** [comment]
Hi @royalpinto 

let me check on that

**Comment by maggiolo00** [comment]
Hi @royalpinto 

i've just pushed a fix for session management with token.  It will solve the serialization of query issue

**Comment by royalpinto** [comment]
Hi @maggiolo00 , this doesn't seem to have resolved the issue. The active number of connections still go beyond the pool.max mentioned in the OrientJS config.

When I increase the number of parallel queries in the snippet: https://gist.github.com/royalpinto/def7a2fe214e98cc07fa708d67c20b43 to > 1000, OrientDB throws `Reached maximum number of concurrent connections`

**Comment by maggiolo00** [comment]
hi @royalpinto 

i guess the problem is in the database open. For each query it tries to acquire a session.

If you change your code with this at the bottom, you shouldn't see this problem anymore.

```

db.open().then(()=> {
	let queries = Array.from({length: 100}, (_, i) => fetchRows(5, i));
	Promise.all(queries)
	.catch(console.error)
	.then(() => {
    server.close();
	});
})
```

Let me try to fix it

Thanks
