### ISSUE TITLE
embedded Date result in _NOT_PARSED_

### ISSUE THREAD

**Issue by phpnode** [orientechnologies/orientjs#3]
_From @rmemoria on May 29, 2015 16:45_

I'm using the latest Oriento by now -> version 1.1.3.

I'm trying to insert the doc with an embedded doc using the declaration below:

```javascript
db.insert().into('Person').set({
   inf:{
     utime:new Date()
   }
}).one().then(function(user) { console.log(user); })
```
but utime is not parsed as a date type.

When I check it in OrientoDB studio I get:

```javascript
{
    "result": [
        {
            "@type": "d",
            "@rid": "#13:3",
            "@version": 1,
            "@class": "Person",
            "inf": {
                "udate": "_NOT_PARSED_"
            }
        }
    ],
    "notification": "Query executed in 0.027 sec. Returned 1 record(s)"
}
```

Is this a bug in oriento? Or the error is mine?

Thanks,
Ricardo

_Copied from original issue: codemix/oriento#321_

**Comment by phpnode** [comment]
_From @dmarcelino on May 29, 2015 16:51_

This actually seems to be an issue in OrientDB, on [stackoverflow #28778088](http://stackoverflow.com/questions/28778088/how-do-i-parse-dates-in-embedded-lists) @lvca said:

> Pass them [dates] as string, but respect the format in database (you can change it with ALTER DATABASE command. Working example:
> `insert into V set events = [{"on": "2005-09-08 04:00:00"}, {"on": "2005-09-08 04:00:00"}]`

I just came across this yesterday and it would be great if this worked out of the box...

**Comment by phpnode** [comment]
_From @lvca on June 2, 2015 12:37_

What's the format oriento passes to OrientDB?

**Comment by phpnode** [comment]
_From @dmarcelino on June 2, 2015 14:56_

@lvca, I've outputted the prepared statement from [command.js#L30](https://github.com/codemix/oriento/blob/master/lib/transport/binary/protocol28/operations/command.js#L30) to the console and the result for an embedded date was:
```
"expires":date("2015-06-02 14:51:32.239", "yyyy-MM-dd HH:mm:ss.SSS", "UTC")
```

The full statement was:
```SQL
UPDATE sessionTable SET sid = "test_set-sid", session = {"foo":"bar","baz":{"cow":"moo","chicken":"cluck"},"num":1,"cookie":{"originalMaxAge":10000,"expires":date("2015-06-02 14:51:32.239", "yyyy-MM-dd HH:mm:ss.SSS", "UTC"),"secure":true,"httpOnly":true,"domain":"cow.com","path":"\/"},"@type":"d"}, expires = date("2015-06-02 14:51:32.239", "yyyy-MM-dd HH:mm:ss.SSS", "UTC"), has_expires = true, updatedAt = date("2015-06-02 14:51:22.240", "yyyy-MM-dd HH:mm:ss.SSS", "UTC") RETURN AFTER WHERE  sid = "test_set-sid" 
```

**Comment by phpnode** [comment]
_From @rmemoria on June 9, 2015 16:43_

I've tried something like that:

create vertex person set inf={ "date": date("2015-06-02 14:51:32.239", "yyyy-MM-dd HH:mm:ss.SSS", "UTC")}

And it didn't work :(

**Comment by phpnode** [comment]
_From @lvca on June 9, 2015 17:15_

If the database datetime format is yyyy-MM-dd HH:mm:ss.SSS, then try this:

    create vertex person set inf = { "date": "2015-06-02 14:51:32.239" }

**Comment by phpnode** [comment]
_From @samuelgoldenbaum on June 10, 2015 0:58_

Had the same issue

**Comment by phpnode** [comment]
_From @rmemoria on June 10, 2015 3:57_

me too... The value is recorded as string.

Apparently the only possibility is to insert the record as string and execute an update to convert it to date.

**Comment by phpnode** [comment]
_From @dmarcelino on June 10, 2015 10:31_

@lvca, back in [stackoverflow #29404173](http://stackoverflow.com/a/29404173/4249576) you said:
> This will be supported in 3.0 (we're already working on that). When 3.0 will be available? Around September 2015.

Is there any github issue we can track? Any chance we can have this fixed sooner? :)

**Comment by phpnode** [comment]
_From @luigidellaquila on June 11, 2015 14:54_

Hi @dmarcelino 

this is the issue on OrientDB issue tracker
https://github.com/orientechnologies/orientdb/issues/3675

I'm working on it (actually it's fixed but not pushed, because I have another test case failing...)

**Comment by phpnode** [comment]
_From @dmarcelino on June 11, 2015 14:55_

Thanks @luigidellaquila, I'll subscribe that.

**Comment by phpnode** [comment]
_From @luigidellaquila on June 11, 2015 16:27_

The issue on OrientDB is fixed in develop branch

Luigi

**Comment by phpnode** [comment]
_From @dmarcelino on June 11, 2015 16:28_

Thank you @luigidellaquila!

**Comment by maggiolo00** [comment]
Closing this issue. 
Has been fixed here
https://github.com/orientechnologies/orientdb/issues/3675
