### ISSUE TITLE
suggestion to add .save and .delete method on record object

### ISSUE THREAD

**Issue by yujinlim** [orientechnologies/orientjs#30]
Hi,

I was wondering to extend record object to include `.save()` and `.delete()` method.

eg
```JS
db.select().from('OUser').where({status: 'ACTIVE'}).one()
.then(function (user) {
   user.status = 'deactivated';
   return user.save();
});
```

what do you think?

**Comment by seeden** [comment]
Response from this method is pure JSON. You can use transformation method and to add some logic. Or you can use existing abstraction layer like sails-orientdb or livia-orientdb

**Comment by maggiolo00** [comment]
hi @yujinlim 

i'm closing this, since you can achieve that with sails-orientdb/livia-orientdb or your custom logic
