### ISSUE TITLE
what's code for select limit of records?

### ISSUE THREAD

**Issue by hosseinGanjyar** [orientechnologies/orientjs#300]
I searched into your documentation and not found any code for select by orientjs with limit!

> select from table limit 10

**Comment by cuvelierm** [comment]
Limits are some of the easier functions to use.

```

SELECT FROM `myTable` ORDER BY 'createdAt' DESC LIMIT 10

```

This will retrieve the 10 last records from `myTable` ordered descending by `createdAt`

Part of the documentation can be found [here](https://orientdb.com/docs/last/Pagination.html) and other parts [here](https://orientdb.com/docs/last/SQL-Query.html). Look for `limit`

**Comment by hosseinGanjyar** [comment]
Thanks for answer. I'll check it.
