### ISSUE TITLE
Are nested projections available in OrientJS?

### ISSUE THREAD

**Issue by UltraMarco** [orientechnologies/orientjs#303]
I'm using OrientJS 2.9 and OrientDB v3.00-RC2.
The problem is that my nested projections work only in Studio, not if I use `odb.query()`.
`MATCH / return` workaround works, but any `SELECT <projection>: { <nested> } FROM <anything>` is not hydrating projections.
Am I missing something obvious?
Grazie,

Marco

**Comment by maggiolo00** [comment]
Hi @UltraMarco 

OrientJS works with 3.0RC2 but uses the old protocol and the old executor that does not support nested projection. We are planned the support in OrientJS for the new protocol. Some work is there but it's not released yet. It will be available after OrientDB 3.0 is out i guess.

Thanks

**Comment by UltraMarco** [comment]
Ok, thank you

Marco

**Comment by UltraMarco** [comment]
Great! Thanks for the update

**Comment by wolf4ood** [comment]
Hi @UltraMarco 

i'm closing this. The version of OrientJS 3.0 has been released with the support for the new protocol and  nested projection

Thanks

**Comment by UltraMarco** [comment]
Great!

Il mar 23 ott 2018, 14:07 Enrico Risa <notifications@github.com> ha scritto:
