### ISSUE TITLE
pagination in big vertice

### ISSUE THREAD

**Issue by hosseinGanjyar** [orientechnologies/orientjs#305]
I have tow queries:

```
db.select('x', 'y')
            .from(node)
            .skip(20)
            .limit(5)
            .all()
            .then(function (results) {
                 // do any things
            });
```
This take ~**2 seconds**,
but below query take ~**10 seconds**:
```
db.select('x', 'y')
            .from(node)
            .skip(200000)
            .limit(5)
            .all()
            .then(function (results) {
                // do any things
            });
```
1- This is not efficient for big than it query, for exp vertice with 10,000,000 records.
2- Is there pagination with index in orientjs? like this: https://orientdb.com/docs/2.2.x/Pagination.html#usage-of-indexes

**Comment by saeedtabrizi** [comment]
Hi @hosseinGanjyar 
why you don't use `db.query(...)`  to write custom query against the **index** or **cluster** or `class`?
I think you should optimize your'e data and using the clusters or indexes for increasing `CRUD` efficiency .

**Comment by hosseinGanjyar** [comment]
Hi @saeedtabrizi ,
Thanks for answer, I used from `db.query(...)`  but this is not my problem. I want using skip for paging. How I optimize my data?
I had indexing for any property in every nodes.
Please show me a solution with sample.
thanks

**Comment by wolf4ood** [comment]
@hosseinGanjyar 

the new protocol supports pagination and also OrientJS v3

https://orientdb.com/docs/3.0.x/orientjs/Session.html#streaming

Thanks
