### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by VitalyKovalev** [orientechnologies/orientjs#31]
db.select().from('Foo').all().then or .map ends with maximum call stack error. Vertex 'Foo' is 143.000 records. With .limit(121398 +/-) working fine. How can I avoid this limit?

**Comment by seeden** [comment]
This library has no support for streams yet.

**Comment by iw2rmb** [comment]
Was my misunderstanding of Promise.
Can be done via Promise.each.

**Comment by lvca** [comment]
Ok guys, I'm going to close this issue.

**Comment by zero-** [comment]
I think my problem might be related to this. I'm using `db.query(q).then(...)` and also getting `maximum call stack size exceeded` with 139644 records. I didn't find anything in the documentation about using `.each()` so a quick example would be greatly appreciated :+1:
