### ISSUE TITLE
Question/Help wanted: User authentication / password comparison

### ISSUE THREAD

**Issue by loopmode** [orientechnologies/orientjs#311]
Hi

Having a class `AppUser` that extends from `OUser`, when creating a new entry via
```
INSERT INTO AppUser SET name = '${req.body.username}', password = '${req.body.password}', status = 'ACTIVE', roles = (SELECT FROM ORole WHERE name = 'reader')
```
the password is automatically encrypted.

When the user attempts to log in and sends a plain password, how can we check whether it matches the encrypted password in the database?

**Comment by loopmode** [comment]
I found some workarounds, but I'm not it's the right way. Seems I am missing something possible with orientjs only.

Instead of extending from `OUser`, I use a generic class `AppUser` so that the password does not get encrypted by orientjs.

Instead, I use `bcrypt` to manually encrypt the password and store it:

```
import bcrypt from 'bcrypt';
import config from '../config/server.config';

export default async function register(db, req, res, next) {
    try {
        const username = req.body.username;
        const password = await bcrypt.hash(req.body.password, config.passwordSaltRounds);

        const result = await db.query(
            `INSERT INTO AppUser SET name = '${req.body.username}', password = '${req.body.password}', status = 'ACTIVE', roles = (SELECT FROM ORole WHERE name = 'reader')`
        );

        if (result.length > 0) {
            const { password, ...user } = { ...result[0] };
            res.send(JSON.stringify(user));
        } else {
            res.sendStatus(400);
        }
    } catch (error) {
        next(error);
    }
}
```

Then, at login, I fetch the user by name and use `bcrypt.compare` to validate the password:
```
import bcrypt from 'bcrypt';

export default async function login(db, req, res, next) {
    try {
        const users = await db.query(`SELECT FROM AppUser WHERE name="${req.body.username}"`);
        if (users.length !== 1) {
            return res.sendStatus(401);
        }

        const { password, ...user } = users[0];
        if (await bcrypt.compare(req.body.password, password)) {
            res.setHeader('Content-Type', 'application/json');
            res.send(JSON.stringify(user));
        } else {
            res.sendStatus(401);
        }
    } catch (error) {
        next(error);
    }
}
```

It works..but it feels weird.
Is this an anti-pattern? Feels like re-inventing some wheel...

**Comment by smolinari** [comment]
@loopmode - That is actually the proper way to do it. As I understand ODB, the OUser Class is there for ODB's internal user access system and really shouldn't be messed with. 

Scott

**Comment by loopmode** [comment]
Alright thanks. I got used to it by now, and it performs well.
