### ISSUE TITLE
Where is other comparison operators like >= and <= in query builder?

### ISSUE THREAD

**Issue by vslinko** [orientechnologies/orientjs#32]

**Comment by lvca** [comment]
Thanks for your PR. We're evaluating it right now.

**Comment by vslinko** [comment]
I think we should provide more clean api than `db.select().from('User').gt({age: 10})`
Where causes should be more compossible, like this:
```js
db
  .select()
  .from('User')
  .where(w =>
    w.and(w.gt('age', 10), w.eq('name', 'John'))
  )
  .limit(1)
  .one()
```

What are you think?

**Comment by lvca** [comment]
I like this proposal. Would you like to contribute with this optional syntax? The goal is be compatible with previous releases.

**Comment by lvca** [comment]
I'm closing this issue, because I merged the PR. Feel free to open a new issue with your proposal. Thanks.
