### ISSUE TITLE
Unable to clone or do npm install

### ISSUE THREAD

**Issue by HariKiran9** [orientechnologies/orientjs#322]
while trying to do npm install orientjs, getting the following error
npm install orientjs
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/orientjs failed, reason: connect ETIMEDOUT
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     <userdir>\AppData\Roaming\npm-cache\_logs\2018-07-12T09_09_11_405Z-debug.log

in Log file I am able to see the following statement
silly fetchPackageMetaData error for orientjs@latest request to https://registry.npmjs.org/orientjs failed, reason: connect ETIMEDOUT 104.18.94.96:443
[2018-07-12T09_09_11_405Z-debug.log](https://github.com/orientechnologies/orientjs/files/2187944/2018-07-12T09_09_11_405Z-debug.log)

**Comment by maggiolo00** [comment]
Hi @HariKiran9 

did you solve it?

**Comment by HariKiran9** [comment]
No, the issue is still persistent.

**Comment by mindnuts** [comment]
@HariKiran9 Does not seems to be orientjs specific issue. Try switching your DNS to google DNS (8.8.8.8) and try again.

**Comment by wolf4ood** [comment]
Closing this, since it's not related to OrientJS
