### ISSUE TITLE
return after $current.field1, $current.field2 returns error

### ISSUE THREAD

**Issue by freeart** [orientechnologies/orientjs#323]
But in OrientDB Studio it works and documentation says it is valid sql

**Comment by maggiolo00** [comment]
H @freeart 

which version of OrientDB are you using?

**Comment by freeart** [comment]
Hi, v3.0.4
But the problem in nodejs driver because it works via http api

**Comment by maggiolo00** [comment]
Hi @freeart 

i was asking because the OrientJS 2.x does not support the new binary protocol and query engine of OrientDB 3.0.

We did release the first OrientJS 3.0 beta version that supports it

You can find the documentation of the APIs here

https://orientdb.com/docs/last/orientjs/OrientJS-beta.html

And install it with 

```
npm install orientjs@beta
```

**Comment by freeart** [comment]
It returns the same error
```
Error on parsing command: Invalid keyword $CURRENT.COUNTRY_ID.CODE. Use UPDATE <class>|cluster:<cluster>> [SET|ADD|PUT|REMOVE|INCREMENT|CONTENT {<JSON>}|MERGE {<JSON>}] [[,] <field-name> = <expression>|<sub-command>]* [LOCK <NONE|RECORD>] [UPSERT] [RETURN <COUNT|BEFORE|AFTER>] [WHERE <conditions>]
Command: UPDATE TReferrer SET content = "string", date = "2017-07-21 17:32:28", financing_status_code = #25:0, pregnancy_week = 1, reason_code = #27:0, service_code = #29:0, short_history = "string", urgency = true RETURN AFTER $current.content, $current.country_id.code AS country_id, $current.date, $current.diagnoses.code.code AS diagnoses, $current.diagnoses.type.code AS diagnosesType, $current.doctor_id, $current.financing_status_code.code AS financing_status_code, $current.hospital_id, $current.id, $current.internal_date, $current.patient_id, $current.pregnancy_week, $current.reason_code.code AS reason_code, $current.sender_institution, $current.service_code.code AS service_code, $current.short_history, $current.status_code.code AS status_code, $current.urgency WHERE id = "111"
```

**Comment by maggiolo00** [comment]
Hi @freeart 

did you use the new APIs as documented here

https://orientdb.com/docs/last/orientjs/OrientJS-beta.html

If you use the old api it will not use the new Protocol and Query Engine

**Comment by freeart** [comment]
I use query raw method
https://orientdb.com/docs/last/orientjs/OrientJS-beta.html#query
What is it "Query Engine"?

**Comment by maggiolo00** [comment]
@freeart 

do you have a snippet to reproduce this issue?

It's the new SQL query parser/ executor in 3.0

**Comment by maggiolo00** [comment]
hi @freeart 

Works for me with these steps

Create a `test` database and execute  those statements

```
create class ATable extends V
create property ATable.id LONG
create property ATable.content STRING
insert into ATable set id = 1
```

Then from OrientJS 3.0-beta with this script

```JS
const OrientDBClient = require("orientjs").OrientDBClient;

async function run() {
  const client = await OrientDBClient.connect({
    host: "localhost",
    port: 2424,
    pool: { max: 10 }
  });

  const session = await client.session({
    name: "test",
    username: "admin",
    password: "admin"
  });
  const results = await session
    .command(
      `UPDATE ATable 
            SET
	        content = ""
        RETURN AFTER 
	        $current.id as id, 
	        $current.content as content
        WHERE id = 1;`
    )
    .all();

  console.log(results);
  await session.close();

  await client.close();
}

run();
```


I get 

```JSON
[ { id: 1, content: '' } ]
```

**Comment by freeart** [comment]
Hmm.. What the different between .query and .command?

**Comment by maggiolo00** [comment]
@freeart 

query is for idempotent statement like `select`

Command is for `insert` `update` ... statement that changes the state of the databases

if you run query for `insert` or `update`  you will get an exception from the database

**Comment by freeart** [comment]
Ok, command works fine!
I used ``query`` because old driver hasn't ``command`` method, only ``query``.
Thanks for your help!

**Comment by maggiolo00** [comment]
Yes we did change the APIs in order to support new protocol feature such as Streaming and Stateful Sessions for Server Transactions.
