### ISSUE TITLE
How to contribute to documentation

### ISSUE THREAD

**Issue by creisle** [orientechnologies/orientjs#325]
I have been looking through the tests and noticing there is quite a bit of functionality that is undocumented in the user manual. I would like to help out and contribute to the user manual but I'm not 100% sure how to go about it. Is that something that is possible? It doesn't look like the user manual sources is in this repo

**Comment by careerscale** [comment]
@creisle  https://github.com/orientechnologies/orientdb-docs is the repo for the documentation. FYI

**Comment by creisle** [comment]
ok great! thanks
