### ISSUE TITLE
Query result is different with orientdb studio

### ISSUE THREAD

**Issue by Leeingnyo** [orientechnologies/orientjs#327]
OrientDB version 3.0.4
orientjs version 3.0.0 beta 0

The result of below query is correct with what I expected, the rows of name that all different.

```sql
SELECT distinct(name) FROM (select [name.ko, name.ja, name.latin, name.hangul] AS name FROM Item WHERE type <> "track" ORDER BY id UNWIND name) WHERE name IS NOT null
```

But with `db.query()` in orientjs, The result is

```js
{
  ~
  distinct: '_NOT_PARSED_'
}
```

So I did 'distinct' job programmatically with js `Set`.
Is nested query not supported yet?

**Comment by maggiolo00** [comment]
Hi @Leeingnyo 

yes nested query should be supported by using orientjs 3.0.0 beta 0.

Which APIs are you using?

Are you using the new APIs documented here ?

https://orientdb.com/docs/last/orientjs/OrientJS-beta.html

**Comment by Leeingnyo** [comment]
Ah.. Thank you! I used the old API...
