### ISSUE TITLE
UPDATE ... SET || Operator Not Supported

### ISSUE THREAD

**Issue by big213** [orientechnologies/orientjs#331]
OrientDB 3.0+ changed the UPDATE ADD feature and replaced it with the `||` operator, as stated here: https://orientdb.com/docs/3.0.x/release/3.0/Upgrading-to-OrientDB-3.0.html#update-add

While it works fine on the studio interface, the `||` operator does not work when sent through OrientJS@beta, which is supposed to support OrientDB 3.0+ features. I get the following error:

`Error on parsing command: Invalid keyword ||. Use UPDATE <class>|cluster:<cluster>> [SET|ADD|PUT|REMOVE|INCREMENT|CONTENT {<JSON>}|MERGE {<JSON>}] [[,] <field-name> = <expression>|<sub-command>]* [LOCK <NONE|RECORD>] [UPSERT] [RETURN <COUNT|BEFORE|AFTER>] [WHERE <conditions>]\nCommand: UPDATE #123:1 SET date= DATE(), images = images || [\"abc\"]\n------------------------------------------------------------------^\r\n\tDB name=\"db_01\"`

**Comment by luigidellaquila** [comment]
Hi @big213 

Which exact OrientDB version are you using? I just tried this from Studio on v 3.0.7 and it seems to work fine

```
insert into V set name = 'a';
UPDATE #9:0 SET date= DATE(), images = images || ["abc"];
```


Any clue on how to reproduce the problem?

Thanks

Luigi

**Comment by big213** [comment]
Hi @luigidellaquila , thanks for checking into this issue. I am using OrientDB v3.0.7 and the studio works fine for the `||` operator, but the problem is when I try to run the command from my app using the orientjs@3.0.0-beta1. It gives me the error described above. I think it might be an issue with orientjs not recognizing the `||` operator properly.

**Comment by wolf4ood** [comment]
Hi @big213 

when using orientjs@3.0.0-beta1, are you using the new APIs?

https://orientdb.com/docs/3.0.x/orientjs/OrientJS-beta.html

Thanks

**Comment by big213** [comment]
@wolf4ood , my mistake, I upgraded from an older orientjs to orientjs@3.0.0-beta1 and I assumed that the API would work the same way. It appears that the API is completely different for 3.0.0. I will try again later today and report back with any issues.

**Comment by wolf4ood** [comment]
Hi @big213 

yes
in order to support OrientDB 3.0 features the API are changed.

The old api are there for backward compatibility, but they still use the old protocol

Thanks

**Comment by big213** [comment]
Have just tested it with the new API, all appears to be working well. Thanks for the help and apologies for the false alarm.
