### ISSUE TITLE
Link Maps Unsupported (Field Type 16)

### ISSUE THREAD

**Issue by big213** [orientechnologies/orientjs#332]
OrientJS Version: 3.0.0-beta1
OrientDB Version: 3.0.7

I am attempting to `SELECT` a field from a record, and the field is a link map. When I select the field, I get this error: `Error: Unsupported field type 16 for field someField`

Steps to reproduce (with valid rids):
`INSERT INTO V SET someField = { "foo": #1:1 }`
`SELECT someField FROM #2:0`

**Comment by wolf4ood** [comment]
Hi @big213 

thank you for raising this issue. Let me check

**Comment by wolf4ood** [comment]
Hi @big213 

i've just pushed a fix for LinkMap. Let wait for the CI then we can release 

`3.0.0-beta2` with the fix

Thanks

**Comment by wolf4ood** [comment]
Hi @big213 

i've just published `3.0.0-beta2` on NPM. Can you confirm that is fixed?

Thanks

**Comment by big213** [comment]
Hi @wolf4ood 

Thanks for the quick fix. That fieldtype seems to be working now, but when I run my query, I'm getting another error:

`Error: Unsupported field type 21 for field undefined`

I am not sure which type that is, I have many different fields and field types for that record. Maybe you could look into field type 21?

**Comment by big213** [comment]
Also, just a general question... I am using pooled sessions with orientjs 3.0, it works a bit different from v2.2. Is it common practice to acquire a session from the pool to run a query, and then close the session immediately after the query is complete? Let's say I have 10 queries to run in a single action, I guess I should `pool.acquire()` and `session.close()` for each of those queries?

**Comment by wolf4ood** [comment]
Hi @big213 
Let me check it should be decimal field. 

let me fix this

**Comment by wolf4ood** [comment]
hi @big213 

yes it is a common practice to acquire a session, do the work and the release.

Depends on the use case, but if you want to run them in true parallelism yes.

With 1 session you can spawn more queries but they will be enqueued on server side since they have the same `sessionId` associated with the session. If you want to run them in parallel you should use more sessions

**Comment by wolf4ood** [comment]
Hi @big213 

i've just pushed a fix for decimal type in develop

**Comment by big213** [comment]
@wolf4ood Thanks very much for that, I am away from the computer but I will try it soon and get back to you. It looks like a new version was not pushed, should I wait for the new version to update or just update the relevant node_modules file to test it?

**Comment by wolf4ood** [comment]
Hi @big213 

let me update the package on npm

Thanks

**Comment by wolf4ood** [comment]
@big213 

just published `orientjs@3.0.0-beta.3`

Thanks

**Comment by big213** [comment]
All good now, thanks very much!
