### ISSUE TITLE
v3.0.0: DELETE EDGE #9:1 Syntax Not Working

### ISSUE THREAD

**Issue by big213** [orientechnologies/orientjs#338]
OrientJS Version: 3.0.0
OrientDB Version: 3.0.8

Steps to reproduce error:
`session.command("DELETE EDGE :foo", { params: { foo: "#9:1" } })`

Results in this error:
`Encountered " ":" ": "" at line 1, column 13.
Was expecting one of: ...`

**Comment by luigidellaquila** [comment]
Hi @big213 

A parameter (`:foo` in this case) as a target for DELETE EDGE is currently not supported.
I'm marking this as an enhancement, it will likely be supported soon.

In the meantime, you have to use a different syntax like

```
"DELETE EDGE E WHERE @rid = :foo"
```

Just make sure to pass the parameter as a RID object (not as a string), or use `convert()` method, ie `:foo.convert("LINK")`

Thanks

Luigi

**Comment by big213** [comment]
@luigidellaquila Alright, thank you. I hope it can be supported soon, but the proposed syntax will suffice in the meantime. However, the `DELETE EDGE :foo` syntax does work fine on the OrientDB 3.0.8 Studio.
