### ISSUE TITLE
.all() does not returns full data for ":{*}"

### ISSUE THREAD

**Issue by petervavro** [orientechnologies/orientjs#339]
The query is e.g. `SELECT in("ConnectedClass"):{*} AS fieldName FROM ExampleVertexClass`

`.all()` is not returning the object with record data, just `@rid` instead.

I wish to get embed full record data. Is this a bug ? How to do this please ?

Thanks

**Comment by luigidellaquila** [comment]
Hi @petervavro 

I think the following will help:

```
SELECT in("ConnectedClass"):{*, @rid, @class, @version} AS fieldName FROM ExampleVertexClass
```

Thanks

Luigi

**Comment by luigidellaquila** [comment]
Please do not use `.all()`, use nested projections instead

**Comment by petervavro** [comment]
> SELECT in("ConnectedClass"):{*, @rid, @class, @version} AS fieldName FROM ExampleVertexClass

Thank you Luigi but this does not work with `.all()` .. Do you have another idea please ?

BTW, that query works perfectly in OrientDB Studio.

**Comment by petervavro** [comment]
> Please do not use `.all()`, use nested projections instead

Could you please be more specific about this ? How to ? Thank you

**Comment by luigidellaquila** [comment]
Hi @petervavro 

I'm afraid I'm not getting your point...
Which is your exact query?

Thanks

Luigi

**Comment by petervavro** [comment]
Query : 
`SELECT in("ConnectedClass"):{*, @Rid, @Class, @Version} AS fieldName FROM ExampleVertexClass`

1. For this query `.all()` is not getting `@Class, @Version` returning `@Rid` only. So, it does not work for me.
2. You wrote : 

> Please do not use .all(), use nested projections instead.

 So how to use nested projections ? Could you please be more specific about this ? Thank you

**Comment by wolf4ood** [comment]
Hi @petervavro 

do you have an example that fails?

I've got this example 

```
create class ExampleVertexClass extends V
create class ConnectedClass extends E
create edge ConnectedClass from (insert into ExampleVertexClass set name = 'foo') to (insert into ExampleVertexClass set name = 'bar')

SELECT in("ConnectedClass"):{*} AS fieldName FROM ExampleVertexClass
```

And i get the same result Studio/OrientJS

Which version of OrientDB and OrientJS do you have?

**Comment by petervavro** [comment]
The example works in Studio but OrientJS does not return the same result. In other words it seem like OrientJS does not support "Nested projections".

OrientDB version : 3.0.8
OrientJS version : 3.0.0

Thanks.

**Comment by petervavro** [comment]
The issue was caused by the way I used OrientJS.

Before, I have used approach described here : https://orientdb.org/docs/3.0.x/orientjs/OrientJS-Server.html

The problem was solved when I use it the way described here :
https://orientdb.org/docs/3.0.x/orientjs/OrientJS.html#connect-to-orientdb

Thank you !
