### ISSUE TITLE
Nested projections not working as in studio

### ISSUE THREAD

**Issue by dargolith** [orientechnologies/orientjs#340]
Nested projections are not working as described in the documentation or as in studio, or I am using the driver in the wrong way.

**orientjs v3.0.0
orientDB v3.0.10**

Init:
`CREATE VERTEX V SET a = {key1: "val1", key2: "val2"}, b = 2, c = 3`

**Studio**
```
SELECT *:{b} FROM V
"result": [
  {
    "b": 2
  }
]

SELECT *:{!b} FROM V
"result": [
  {
    "a": {
      "key1": "val1",
      "key2": "val2"
    },
    "c": 3,
    "@rid": "#10:1",
    "@version": 1,
    "@class": "V"
  }
]

SELECT b, a:{key2} as key2 from V
"result": [
  {
    "b": 2,
    "key2": {
      "key2": "val2"
    }
  }
]
```
**orientjs:**
```
> db.query('SELECT *:{b} FROM V').then(r => console.log(r))
> [ { '@class': 'V',
    '@type': 'd',
    a: { key1: 'val1', key2: 'val2' },
    b: 2,
    c: 3,
    '@rid': RecordID { cluster: 10, position: 1 },
    '@version': 1 } ]

> db.query('SELECT *:{!b} FROM V').then(r => console.log(r))
> [ { '@class': 'V',
    '@type': 'd',
    a: { key1: 'val1', key2: 'val2' },
    b: 2,
    c: 3,
    '@rid': RecordID { cluster: 10, position: 1 },
    '@version': 1 } ]

> db.query('SELECT b as bnew, a:{key2} as key2 from V').then(r => console.log(r))
> [ { '@type': 'd',
    bnew: 2,
    a: { key1: 'val1', key2: 'val2' },
    '@rid': RecordID { cluster: -2, position: 0 },
    '@version': 0 } ]
```
The first output, from studio, is the expected one.

Seems everything including and after ":" in projections is just simply ignored by orientjs.

Perhaps this is another question, but I'm also wondering: When I'm specifying a projection, why do I still automatically get @rid, @version, @type in the result? How can I only get what I ask for without having to do post filtering myself?

Example:
```
> db.query('SELECT b from #10:1').then(r => console.log(r))
> [ { '@type': 'd',
    b: 2,
    '@rid': RecordID { cluster: -2, position: 0 },
    '@version': 0 } ]

Expected / desired:
> [ { b: 2 } ]
```

**Comment by wolf4ood** [comment]
Hi @dargolith 

can you share the code on how you get the db instance?

Thanks

**Comment by dargolith** [comment]
@wolf4ood 

Sure!

I tried both:
```
const ODatabase = require('orientjs').ODatabase;
const db = new ODatabase({
  host: 'localhost',
  port: 2424,
  username: 'root',
  password: 'root',
  name: 'test'
});
```
and
```
const OrientDB = require('orientjs');
const server = OrientDB({
  host: 'localhost',
  port: 2424,
  username: 'root',
  password: 'root',
})
const db = server.use('test');
```

I also tried both using:
`db.select(['*:{b}']).from('V').all().then(r => console.log(r));`

and

`db.query('SELECT *:{b} FROM V').then(r => console.log(r));`

Which should be the same thing, except the first gets passed through buildStatement() and then into .query().

**Comment by wolf4ood** [comment]
Hi @dargolith 

that could be the problem. Try to use the newest APIs documented here.

https://orientdb.org/docs/3.0.x/orientjs/OrientJS.html

They make use of the new 3.0 protocol and should work with nested projections

Let me know if it helps
Thanks

**Comment by dargolith** [comment]
@wolf4ood 

Thanks for the solution! It definitely works using the provided instructions.

For anyone wondering, I use this code now (using async/await atm, but pure .then works fine as well of course):
```
import { OrientDBClient } from 'orientjs';
const client = await OrientDBClient.connect(dbConnectionData);
const session = await client.session(dbData);
const query = session.select(['*:{b}']).from('V');
console.log(await query.all());
```

Thanks again! :)
