### ISSUE TITLE
Docs: async/await in examples?

### ISSUE THREAD

**Issue by ghost** [orientechnologies/orientjs#347]
The current examples use `.then()` for working with Promises.  `async`/`await` support has been in Node since v4, and is a significantly simpler way of working with Promises that's gaining wide adoption.

For example, the Record API (in 3.1): 
```js
db.record.get('#5:0')
    .then(function(record){
      record.surname = 'updated'
      db.record.update(record)
         .then(function(){
          console.log("Updated");
      })
   })
```
Using `async`/`await`, this becomes a lot nicer:
```js
// in async function
let record = await db.record.get('#5:0')
record.surname = 'updated'
await db.record.update(record)
console.log("Updated")
```

A possible stumbling block might be that `await` can only be used inside an `async` function, and not at top level (although [that might change](https://github.com/tc39/proposal-top-level-await)). If the DB code needs to be at top-level, a simple, common work-around is to wrap it in an async function, then call that function:

```js
let do_database_ops = async function(){
 // connect to DB, perform operations, etc. using await
} 
do_database_ops()
```

With `async`/`await` likely becoming the new default way to work with Promises, does updating the docs (or at least adding these as an alternative) make sense?

**Comment by wolf4ood** [comment]
Hi @milaniliev 

we have started the work on the new docs with `async/await`

see here
https://orientdb.com/docs/3.0.x/orientjs/OrientJS.html

We will reflect this on all the docs of OrientJS 3.0.x

Thanks

**Comment by ghost** [comment]
Yup, I see it. Awesome!
