### ISSUE TITLE
Error: No query with id <..> found probably expired session

### ISSUE THREAD

**Issue by lightningthought** [orientechnologies/orientjs#350]
We receive the following error when attempting to run an `INSERT INTO ... FROM SELECT ... ` using the new Client/Session APIs:

`No query with id <..> found probably expired session`

We've created a small reproduction program at:
https://gist.github.com/milaniliev/6d4c5411c6b9469830d9aa705d0831d1

This causes the error reproducibly when ran against the default Docker image for `3.0.10` using the example command:
`$ docker run -d --name orientdb -p 2424:2424 -p 2480:2480 -e ORIENTDB_ROOT_PASSWORD=rootpwd orientdb`

Using the old Server/Database APIs does not cause the error.

**Comment by wolf4ood** [comment]
Hi @lightningthought 

i've reproduced it. Seems more a problem of the server that closes the running queries.
Let me check more and get back to you

Thanks

**Comment by lightningthought** [comment]
Okay, thank you!

**Comment by wolf4ood** [comment]
Hi @lightningthought 

@tglman  found and fixed the issue on the server.

https://github.com/orientechnologies/orientdb/commit/5633a65daa63bbfcdc9e45c0efa3dcfea48878a0

It will be available in the next OrientDB 3.0.x release

**Comment by lightningthought** [comment]
That's great news! Thank you very much for the quick response and fix.
