### ISSUE TITLE
"pool.close()" is missing in async/await example.

### ISSUE THREAD

**Issue by petervavro** [orientechnologies/orientjs#360]
Hi there,

I am really thankful to @wolf4ood for async/await example : [https://github.com/orientechnologies/orientjs-example](https://github.com/orientechnologies/orientjs-example)

I have an additional question about that : 
Could you add `pool.close()` to the example please ?

Thanks

**Comment by wolf4ood** [comment]
hi @petervavro 

in this case i think it's not needed. In general the sessions pool should be closed at app shutdown or when you are done with the pool. For example when testing.

**Comment by petervavro** [comment]
Thank you for the quick reply. It is pity that you will not add it there because at least for me would be really helpful. I would understand better its intention of usage in an example case.

But on the other side, I understand it might make the example more complex and less understandable, so for that reason, I agree with you.
