### ISSUE TITLE
Queries with multiple selectors do not work in OrientJS

### ISSUE THREAD

**Issue by quantpioneer** [orientechnologies/orientjs#362]
### Issue: Queries with multiple selectors (e.g. `select *, inE().name`) do not work in OrientJS v3.0.4 (see query example below)

OrientDB version: 3.0.6
OrientJS version: 3.0.4
OS: Windows 10

## Steps to reproduce 

**SQL**

    insert into V set name = 'a';
    insert into V set name = 'b';
    create edge from (select from V where name = 'a') to (select from V where name = 'b') set name = 'test';

**Javascript**
    

    // Load OrientDB client
    const OrientDBClient = require("orientjs").OrientDBClient;
    const to = require('await-to-js').default;

    // Connect to Database.
    [err,client] = await to(OrientDBClient.connect({
      host:   ORIENTDB_HOST,
      port:   ORIENTDB_PORT
    }));
    [err,session] = await to(client.session({ 
      name:       ORIENTDB_DB, 
      username:   ORIENTDB_NAME, 
      password:   ORIENTDB_PASS
    }));

The following works both in studio and orient-js: `select * from ...`

    const result = await session.query(`SELECT * FROM (TRAVERSE out() FROM (select from V where name = 'a') WHILE $depth < 2)`).all();

This also works both in studio and orient-js: `select inE().name as name from ...`

    const result = await session.query(`SELECT inE().name as name FROM (TRAVERSE out() FROM (select from V where name = 'a') WHILE $depth < 2)`).all();

**But the following only works in studio but not in orient-js:** `select *, inE().name as name from ...`

    const result = await session.query(`SELECT *, inE().name FROM (TRAVERSE out() FROM (select from V where name = 'a') WHILE $depth < 2)`).all();

It seems that this query gets stuck in an infinite loop because I never get a response from the server (no errors are thrown).

In studio this query works fine:
![Studio example](https://i.imgur.com/5t2cqaO.png)

**Comment by quantpioneer** [comment]
Just noted that this also doesn't work with `batch()`.

This works:

    let batch = `begin;
        let x = TRAVERSE out() FROM (select from V where name = 'a') WHILE $depth < 2;
        let y = select * from (select expand($x));
        commit;
        return $y;`;
    const result = await session.batch(batch).all();

But this doesn't:

    let batch = `begin;
        let x = TRAVERSE out() FROM (select from V where name = 'a') WHILE $depth < 2;
        let y = select *, inE().name as name from (select expand($x));
        commit;
        return $y;`;
    const result = await session.batch(batch).all();

**Comment by quantpioneer** [comment]
This issue seems to be fixed in OrientDB 3.0.15 GA Community Edition

**Comment by wolf4ood** [comment]
@JeanPaulvB 

ok so the problem was actually in OrientDB and not OrientJS.

Thanks @JeanPaulvB
