### ISSUE TITLE
How to use limit with v3.X

### ISSUE THREAD

**Issue by creisle** [orientechnologies/orientjs#364]
orientjs version: 3.0.4
orientdb version: 3.0.14
OS version: centos07

With v2.X the query limit was given the same as the params and not part of the query string. Has that changed? When I am running a query

```js
const results = await session.query('SELECT * FROM SomeTableName', {limit: 1}).all();
```

results is returning more than 1 record

**Comment by wolf4ood** [comment]
Hi @creisle 

`limit`  in 2.2.x was part of the protocol. And thus was serialized as parameters.

From 3.0.x the limit should be expressed in the query itself

```js
const results = await session.query('SELECT * FROM SomeTableName limit 1').all();
```

**Comment by wolf4ood** [comment]
Hi @creisle 

did it solve the issue?

can we close this?

Thanks

**Comment by creisle** [comment]
Yes I am able to run the query
