### ISSUE TITLE
Available session in the pool ?

### ISSUE THREAD

**Issue by petervavro** [orientechnologies/orientjs#365]
My objective is to control whether all the session are closed. For this purpose I would like to get information the number of open and available session. How can I accomplish that ?

I figured, there are some description props in pool object for this purpose. Where can I find a documentation for that please ?

Thank you !

**Comment by wolf4ood** [comment]
Hi @petervavro 

there is no documentation about that. But you can accomplish that with this methods

https://github.com/orientechnologies/orientjs/blob/develop/lib/client/pool/index.js#L66

Which wrap the underlying pool library.

Under the hood we use generic pool, you can refer here for the documentation

https://github.com/coopernurse/node-pool#pool-info


Let me know if you need other info

Thanks

**Comment by wolf4ood** [comment]
Hi @petervavro 

did you check on this?

Can we close it?

Thanks

**Comment by wolf4ood** [comment]
Hi @petervavro 

i'm closing this. The APIs above should answer your question.

Let me know if you need other infos

Thanks
