### ISSUE TITLE
Fetch plan for link type

### ISSUE THREAD

**Issue by nomi-ramzan** [orientechnologies/orientjs#366]
Hi I am using
version 3.0.17
schema:
```
{
  prop1: string
  link1:  link -> schema2.@rid
}

```
Query:
```
SELECT * FROM schema FETCHPLAN *:1 LIMIT -1
// OR
db.select().from('schema').fetch({ '*': 2 })
```

it is still not expanding any linked record. Can you please correct my query.
Thank you

**Comment by wolf4ood** [comment]
Hi @nomi-ramzan 

are you using the new APIs with 3.0.x of OrientJS?

**Comment by nomi-ramzan** [comment]
Yes I am using all latest versions orientdb( 3.0.17 ) orientjs ( 3.0.4 )

**Comment by wolf4ood** [comment]
Are you using the API with client and sessions described here right?

https://orientdb.com/docs/3.0.x/orientjs/OrientJS.html

**Comment by nomi-ramzan** [comment]
Ye I am sure. and following this [example](https://github.com/orientechnologies/orientjs-example/blob/master/orientjs-chat-example-async-await/index.js)
OrientDB: 3.0.17
Orientjs: 3.0.4
Node: v8.12.0

**Comment by wolf4ood** [comment]
Ok, because fetch plan with the new APIs are deprecated. You should use nested projection

for fetching linked objects

https://orientdb.com/docs/3.0.x/sql/SQL-Projections.html

**Comment by nomi-ramzan** [comment]
OK Thank you. Let me check that.

**Comment by wolf4ood** [comment]
Hi @nomi-ramzan 

was the link helpful ?
can we close this issue?

Thanks

**Comment by wolf4ood** [comment]
Hi @nomi-ramzan 

Let me know if you need other info. 
Meanwhile i'm closing this

Thanks
