### ISSUE TITLE
"$parent.$current" does not work in .let

### ISSUE THREAD

**Issue by petervavro** [orientechnologies/orientjs#368]
```
var r = session.select(`$testVar`).from('TableA').let(`$testVar`,`$parent.$current.someField`)
```
In all lines **$testVar = null** except the first one.

`console.log(r.toString())` = `SELECT $testVar FROM TableA LET $testVar = $parent.$current.someField`

In Studio : $testVar = `"its value"` for every record.

What do I do wrong, please?

**Comment by wolf4ood** [comment]
Hi @petervavro 

let me check. Seems more related OrientDB. Let me try to repoduce this 

Thanks

**Comment by wolf4ood** [comment]
Hi @petervavro 

i've checked. It was an OrientDB but. It has already been fixed.

It will be relased in the next ODB GA version 3.0.19. Thanks

https://github.com/orientechnologies/orientdb/commit/b72e51a86b2d0cab710d2cad29efc78a2184622a
