### ISSUE TITLE
Ambiguous query format at .exec(query) or bug

### ISSUE THREAD

**Issue by bondden** [orientechnologies/orientjs#37]
# OrientDB.RequestError: Cannot find a command executor for the command request: sql.begin

## Environment
|Component           |Deployed Instance          |
|---                 |---                        |
|Machine             |Oracle VM VirtualBox, 2 x Intel Core i7-3517U 1.9 GHz, 2 GB RAM    |
|OS                  |Linux Mint 17.2 Mate 64-bit|
|OrientDB            |Community-2.1-rc5          |
|NodeJs              |v.0.12.6                   |
|OrientJs            |v.2.0.0                    |
|OrientDB prtotocol  | plocal (28)               |

### 1. Running code, including:

```js
//...

//trying different query formats:
q='begin;create class Tmp1 extends V;create class Tmp2 extends V;commit retry 10;';
// or
q='begin\ncreate class Tmp1 extends V\ncreate class Tmp2 extends V\ncommit retry 10';

db.exec(q).then(function(r){

	//...

}).catch(function(e){

	//...

});
```

### 2. Getting result, including:

```log
OrientDB.RequestError: Cannot find a command executor for the command request: sql.begin
create class Tmp1 extends V
create class Tmp2 extends V
commit retry 10
    at Operation.parseError (/web/dmn/esf4.loc/node_modules/uto/node_modules/orientjs/lib/transport/binary/protocol28/operation.js:879:13)
    at Operation.consume (/web/dmn/esf4.loc/node_modules/uto/node_modules/orientjs/lib/transport/binary/protocol28/operation.js:469:35)
    at Connection.process (/web/dmn/esf4.loc/node_modules/uto/node_modules/orientjs/lib/transport/binary/connection.js:380:17)
    at Connection.handleSocketData (/web/dmn/esf4.loc/node_modules/uto/node_modules/orientjs/lib/transport/binary/connection.js:281:17)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

**Comment by lvca** [comment]
You are trying to execute a script. Please look at the documentation about executing SQL scripts.

**Comment by lvca** [comment]
You are trying to execute a script, but I'm not sure if OrientJS supports it.

**Comment by maggiolo00** [comment]
@bondden  
try this

```
db.exec(q,{class: "s"}).then(function(r){

    //...

}).catch(function(e){

    //...

});
```
to execute a script

**Comment by bondden** [comment]
Thanks you very much! It works. The second parameter is required.

**Comment by adrianblynch** [comment]
@maggiolo00 - Could you explain the relevance of `{ class: 's' }` in that example?

My fixed code:
```
return db
	.exec(
		`BEGIN
			LET group = CREATE VERTEX Group SET id = 'xxx', name = 'yyy'
			LET otherGroup = CREATE VERTEX Group SET id = 'abc', name = 'def'
			LET edge = CREATE EDGE BelongsTo FROM $group TO $otherGroup
		COMMIT
		RETURN [$group, $otherGroup, $edge]`,
		{ class: "s" } // Why is this needed???
	)
	.then((result) => {
		console.log("RESULT:", result)
		return result
	})
	.catch(err => {
		console.log("ERROR:", err)
		throw err
	})
```
Looking at the docs, the only `.exec` example is this:

```
db.exec('select from OUser where name=:name', {
    params: {
        name: 'Radu'
    }
}).then(function (response){
    console.log(response.results);
});
```

Is it anything to do with being in batch mode? :anguished:

**Comment by gajjargaurav** [comment]
https://orientdb.com/docs/last/Network-Binary-Protocol.html#request-command explains that,

- s - stands for "script" (for server-side scripting using languages like JavaScript). It's like passing com.orientechnologies.orient.core.command.script.OCommandScript.

@StarpTech mentioned it in https://github.com/orientechnologies/orientjs/issues/68
