### ISSUE TITLE
Question: how to navigate a big graph with studio

### ISSUE THREAD

**Issue by Eomm** [orientechnologies/orientjs#371]
Hello,
I'm trying to execute some queries but all of these fails badly (the Studio tab go in out-of memory):

![image](https://user-images.githubusercontent.com/11404065/55788219-34555280-5ab8-11e9-8f3f-fdc552ae7642.png)

```
SELECT FROM (TRAVERSE out("Access") FROM (SELECT FROM Client where myId = 30543) MAXDEPTH 1) WHERE @class = 'Segment'

// '#37:18' = myId = 30543
g.V('#37:18').out('Access')

g.V('#37:18').out('Access').limit(10)

select from `Segment`
```

My graph is like [this](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFJcbiAgICBQKChQdWJsaXNoZXIpKS0tPnxTZWxsfFMoKFNlZ21lbnQpKVxuICAgIEMoKENsaWVudCkpLS0-fEFjY2Vzc3xTXG4gICAgUy0tPnxDb250YWlufFUoKENvbnRhY3QpKVxuICAgIEMtLT58SGF2ZXxVXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ)

![image](https://user-images.githubusercontent.com/11404065/55787809-64502600-5ab7-11e9-93ab-555719c7955d.png)

I notice that when I walk in the Segment vertex all is stuck.
Now, the segments are 13 and they share 14,871,406 contacts
I create 2 indexs, one on the `myId` and another one in Contact vertex and no more.

I don't find how I can navigate the graph without break the UI, also the "graph" tab don't load the Segment vertex.

Maybe Orient is trying to get all che `Contact` attached to the `Segment`?
If you have any suggestions I appreciate it

Thank you very much

**Comment by wolf4ood** [comment]
Hi @Eomm 

Studio is not designed for displaying big graphs. It uses svg under the hood.

The typical limit is 500 nodes and 1000 edges.

If you need to display a bigger graphs you could use external tools 

You could try this for example which was recently open sourced

https://github.com/ArcadeAnalytics/arcadeanalytics

Thanks

**Comment by Eomm** [comment]
Thank you for the explanation, I will give it a try 👍
