### ISSUE TITLE
Error on parsing query parameter

### ISSUE THREAD

**Issue by alexmm11** [orientechnologies/orientjs#387]
I'm trying this query:

```javascript
session
  .query(
    'select name from Category where types contains(:type)',
    { 
      params: {
        type: "Place"
      }
    }
  );
```

but i'm getting this error:

![Captura de pantalla de 2019-08-20 01-58-37](https://user-images.githubusercontent.com/521303/63324700-32b15c00-c2ee-11e9-812b-434629d955b7.png)

only works in this way:
```javascript
session
  .query(
   `select name from Category where types contains("${type}")`,
  );
```

The **":"** is supposed to set the variable value in the params object, but it does nothing.

**Comment by wolf4ood** [comment]
Hi @alexmm11 

did you try

```js
session
  .query(
    'select name from Category where types contains :type',
    { 
      params: {
        type: "Place"
      }
    }
  );
```

**Comment by alexmm11** [comment]
Thanks Enrico, It works perfectly!! :ok_hand:

**Comment by wolf4ood** [comment]
👍
