### ISSUE TITLE
Maximum call stack size exceeded when using select *

### ISSUE THREAD

**Issue by adriancoca** [orientechnologies/orientjs#392]
If the next query is used i get the error from image

select  *,
    $task.key as status,
    $task.@rid as subtask,
    $contact as contact,
    $agent.username as agent,
    in('IS_A')[0].tojson() as task from Offer
     LET $task= last(in('IS_A').in('PART_OF')),
      $contact=out('FOR')[0],
       $agent=$task.in('WORKS_ON')[0]

![image](https://user-images.githubusercontent.com/7643185/65754813-8481a900-e11a-11e9-9762-447dd7e9dedb.png)

But if i use the select bellow it runs fine.
select
    @rid as rid,client,
    inE('IS_A') as in_IS_A,
    $task.key as status,
    $task.@rid as subtask,
    $contact as contact,
    $agent.username as agent,
    in('IS_A')[0].tojson() as task from Offer
     LET $task= last(in('IS_A').in('PART_OF')),
      $contact=out('FOR')[0],
       $agent=$task.in('WORKS_ON')[0]

I don't know if it is a orientjs problem or orientdb. It seems the problem is using *.

**Comment by wolf4ood** [comment]
Hi @adriancoca 

which version of OrientJS  are you using?

Do you use the new APIs?

Thanks

**Comment by adriancoca** [comment]
Hi, I am using "orientjs": "2.2.6", I also tried with "3.0.6".
Nodejs version 12.9.0 and Orient db 3.0.23.
LE: Orient db 3.0.23

LEE: I was using the old api. Switching to the new one solved my problem.
Thanks a lot.
