### ISSUE TITLE
Live query continues to run after unsubscribe

### ISSUE THREAD

**Issue by tafenton** [orientechnologies/orientjs#394]
Hi,
I can create live queries that behave as expected. When I try to unsubscribe, I get:

`"{unsubscribed:277737044,unsubscribe:true,token:277737044}"`

However, when the next update occurs, the live query triggers anyway. At the moment the only way I have to clear a live query is to restart the database.

My code is in Clojure, adapted from your Java API documentation:

`(.execute (OCommandSQL. (str "LIVE UNSUBSCRIBE " token)) (object-array []))`

**Comment by luigidellaquila** [comment]
Hi @tafenton 

If you are using v 3.0 I strongly suggest you to use the new LiveQuery API
```
(java)
OLiveQueryMonitor monitor = db.live("SELECT FROM...", listener);
...
monitor.unSubscribe();
```

I'll try to check the legacy one, but I'm not sure I'll be able to fix it in short time

Thanks

Luigi

**Comment by tafenton** [comment]
Hi Luigi,
Thanks for your extremely quick response! 

I now see that the new API is shown in the Reference section of the docs, but the [tutorial](https://orientdb.org/docs/3.1.x/java/Live-Query-Java.html) in the 3.1 docs still shows the old version.

The new API works perfectly - thank you for your help.
