### ISSUE TITLE
Create Edge query command hangs with lightweight edges

### ISSUE THREAD

**Issue by tomscreen** [orientechnologies/orientjs#395]
Using version 3.0.7 of orientjs library to interact with version 3.0.23 of OrientDB.

Problem manifests as a "hung promise" when executing a 'create edge' query on a session against the database. e.g.... (code for illustration)

`let query = CREATE EDGE rel FROM #57:0 to #49:0
return session.command(query).all().then(function(res) {
   ...
})`

The code never gets into the next 'then' function.

Problem only occurs when database is set to use lightweight edges.

**Comment by wolf4ood** [comment]
Hi @tomscreen 

i've managed to reproduce it and identify the issue. 

I'm working on a fix. Thanks

**Comment by wolf4ood** [comment]
Hi @tomscreen 

i've just pushed a fix. It will be available in the next release of OrientJS

Thanks
