### ISSUE TITLE
db.record.delete("#1:1") makes dirty links.

### ISSUE THREAD

**Issue by phpnode** [orientechnologies/orientjs#4]
_From @SangWoo-Maeng on May 29, 2015 12:48_

OrientDB 2.0.7

In graph mode DB, 
delete edge by rid like this.

db.record.delete('#1:1')
.then(function () {
  console.log('Record deleted');
});

The edge looks deleted but makes dirty links.
After execute that, in db console, repair database shows fixing links and docuements.

orientdb {db=test}> repair database
Repairing database...
- Fixing dirty links...Done! Fixed links: 2, modified documents: 2
  Repair database complete (0 errors)

Dirty links, docs should not be made.

Please check it.

_Copied from original issue: codemix/oriento#320_

**Comment by phpnode** [comment]
_From @StarpTech on May 29, 2015 12:54_

It seems like an orientdb issue. Please try via studio again ```DELETE VERTEX #1:1```. By the side how is your graph structure? Do you only have one vertex? Docs: `The "Delete edge" command takes care to remove all the cross references to the edge in both "in" and "out" vertices.`

**Comment by phpnode** [comment]
_From @dmarcelino on May 29, 2015 13:41_

Have you tried using a syntax closer to the README example: https://github.com/codemix/oriento#deleting-an-edge-between-vertices? Something like:

```js
db.delete('EDGE')
.where('@rid = #1:1')
.one()
.then(function (count) {
  console.log('deleted ' + count + ' edges');
});
```

**Comment by phpnode** [comment]
_From @SangWoo-Maeng on May 31, 2015 23:55_

I wanted to delete EDGE or VERTEX by RID regardless of its type.
So I tried to delete it such like this api 
db.record.delete('#1:1')

@StarpTech
I have multiple vertex and edges.
In the studio, the query specify the target type like this.
delete vertex #1:1
delete edge #2:2
These make no problem.

@dmarcelino  
From your mention, I understood that I have to use different API for each operation, deleting vertex or edge.

Thank you.

**Comment by phpnode** [comment]
_From @dmarcelino on June 1, 2015 0:0_

> I wanted to delete EDGE or VERTEX by RID regardless of its type.

That's only possible if you force it by using the keyword `UNSAFE` on the query (I don't think Oriento has the syntax for this yet). More details on orientechnologies/orientdb#3163. Please note that using `UNSAFE` can potentially leave your graph in an inconsistent state.

You're welcome.

**Comment by hilkeheremans** [comment]
To add to this, when I create two vertices with an edge in between, and I delete the vertices afterwards using db.record.delete, the edges are not always deleted. Afterwards, it become difficult to delete the edges: the edges are orphaned in the database. 

Attempting to delete the edge at that point (for example by its @rid) will cause a NullPointerException without a stack trace (I'm guessing this is an additional issue to be logged).

Now, as is implied above, I'm assuming db.record.delete should never be used to delete vertices or edges at all. That's fine, but from an orientjs viewpoint it's a little too easy for a developer to get confused by the multiple syntaxes (eg db.record.delete, db.delete('vertex')) available.

Wouldn't it be useful if we updated the docs or add some type of warning in case the developer tries to do this anyway?

(This, of course, from a developer just getting started with orientjs)

**Comment by MangelMaxime** [comment]
Is it possible to use the `UNSAFE` option for the down migration :

```js
exports.down = function (db) {
    db.class.drop('Identity')
    .then(function (Identity) {
        console.log('Class Identity deleted');
    });
    
    db.class.drop('User')
    .then(function (Identity) {
        console.log('Class User deleted');
    });
};
```

I don't know how to specify it.

**Comment by jpstrikesback** [comment]
db.record.update also exhibits this behaviour (after an update, edges are removed from the record but left in the graph). Assuming this is expected from the Record API in OrientJS, what is the best way to update the docs for this @maggiolo00 ?

**Comment by wolf4ood** [comment]
Hi, 
i've added a test case for this issue. It's not valid anymore.

It works with OrientDB 3.0.x and OrientJS 3.0.x
