### ISSUE TITLE
How to pass the clusters count when creating a class?

### ISSUE THREAD

**Issue by rohitpatil7892** [orientechnologies/orientjs#410]
I want to pass a number of the cluster when I am creating a new class.

`Let clusterNO = 10`  Custom clusters count 
`Query = CRETAE CLASS className CLUSTERS ${clusterNO} `
 How to manage this query in OreintJS create function
`Instance.DB.create(className) `How to pass the cluster count for creating a clusters of that class?

Create function of OreintJS support to set default **CLUSTER** not for creating new **CLUSTERS** is any support for creating the cluster of that class?

**Comment by wolf4ood** [comment]
Hi @rohitpatil7892 

it is not supported yet in the class API. 
You have to create by hand with SQL statement if you want to change the number of clusters.

I will mark this as enhancement, we may want to support this in the future

Thanks
