### ISSUE TITLE
npm issue with parse-function

### ISSUE THREAD

**Issue by hethcox** [orientechnologies/orientjs#412]
I just built a new app with the latest orientjs. When I started the app I got this error:
<blah blah blah>/node_modules/orientjs/lib/db/db.js:16
  parseFn = require("parse-function")();

I tracked this down to an incompatibility between orientjs and the latest parse-function (the version number in the package file is 5.5.0).  When I backed parse-function down to version 5.4.4 it fixed this issue.

**Comment by Aeonrush** [comment]
Hi
```bash
npm i parse-function@5.4.4
```
Fixes bug for me

**Comment by alancnet** [comment]
@wolf4ood Please address this issue. Consider locking parse-function to version 5.4.4, which I have done in PR #416.

**Comment by wolf4ood** [comment]
Hi @alancnet 

thanks i'm merging that PR
