### ISSUE TITLE
No drop database 

### ISSUE THREAD

**Issue by VitalyKovalev** [orientechnologies/orientjs#42]
If driver allow to create database by server.create, then it should allow to drop it same way like server.drop.

**Comment by luigidellaquila** [comment]
Hi @VitalyKovalev 

this feature is already available, but it's not documented in the main page, I'm doing it right now.
There is also a CLI command for this, see https://github.com/orientechnologies/orientjs#destroying-an-existing-database

**Comment by luigidellaquila** [comment]
Done
