### ISSUE TITLE
How can i fix Denial of Service of "mem" ?

### ISSUE THREAD

**Issue by heli-os** [orientechnologies/orientjs#423]
Low            Denial of Service
Package        mem
Patched in     >=4.0.0
Dependency of  orientjs
Path           orientjs > yargs > os-locale > mem
More info      https://npmjs.com/advisories/1084

I use the following software version.
node.js : 12.14.0
npm : 6.13.4

**Comment by FluffyLlama** [comment]
This issue was fixed in the following way.
1. npm update orientjs
2. npm-D install orientjs
