### ISSUE TITLE
In/Out reversed in Graph Traverse

### ISSUE THREAD

**Issue by hethcox** [orientechnologies/orientjs#424]
I'm traversing a graph and it appears that the in and out are reversed on edges.
```
        let query = 'TRAVERSE * FROM ' + rootRID;
        await res.locals.db.command(query).all()
            .then(function (rows) {
                dumpGraph(rows, rows[0]);
                result = rows.slice();
            });
        res.send(result);
```
In my DB I have an edge from (vertices) 37:0 to 38:0. But in the query result these are reversed.
```
{
        "@class": "HasSubheading",
        "in": "#38:0",
        "out": "#37:0",
        "@rid": "#41:0",
        "@version": 1
    }
```

Am I using this incorrectly or is it a bug?

**Comment by hethcox** [comment]
Please disregard. I'm not sure what's what. These two screenshots from Orient Studio seem to contradict each other.  I guess 'out' means the vertex that this edge comes from.

<img width="1144" alt="Screen Shot 2020-01-15 at 4 29 14 PM" src="https://user-images.githubusercontent.com/2358344/72473212-33262400-37b4-11ea-9c39-a87cd0053c57.png">

<img width="1185" alt="Screen Shot 2020-01-15 at 4 25 56 PM" src="https://user-images.githubusercontent.com/2358344/72473025-d0cd2380-37b3-11ea-8a6e-ee19cc0b2157.png">

**Comment by wolf4ood** [comment]
Hi @hethcox 

for historical reason they are called in/out which are

```
in = to
out = from
```

which basically reflect the traversal step from `Edges` eg.

```
select Id,outE("HasFriend").inV() from Profiles
```

Let me know if this helps

Thanks

**Comment by hethcox** [comment]
Thanks for the response. As longs as it's consistent I can work with it.
