### ISSUE TITLE
Query execution time difference with or without indexing

### ISSUE THREAD

**Issue by rohitpatil7892** [orientechnologies/orientjs#425]
I have 2 queries for traversing records from DB with indexing and without indexing.
I executed both queries but the execution time is the same for both.
Person table having **50000** records with **indexing on ID** property.
```
1. SELECT * FROM person WHERE ID = "abc123" LIMIT 1

2. SELECT EXPAND(rid) FROM person.ID WHERE key = 'abc123'
```

**1. Can both query use indexing to traverse?
2. Which one will execute faster and why?**

**Comment by wolf4ood** [comment]
Hi @rohitpatil7892 


can you provide the explain of those queries?

Thanks

**Comment by VikramShityalkar** [comment]
Hi @wolf4ood 

We went through [SQL Optimization](https://orientdb.com/docs/last/SQL-Query-Optimization.html) again. By looking at explain, we found that it is using index in # 1 query. Please let me know if you have any other documentation that we can refer for optimization. 

This issue can be closed.

**Comment by VikramShityalkar** [comment]
There is following comment available on page:

> V 3.0 has a completely new execution planner, so none of these tips can be considered valid on that version.
