### ISSUE TITLE
Alter property query return java.lang.NullPointerException

### ISSUE THREAD

**Issue by rohitpatil7892** [orientechnologies/orientjs#426]
I am updating the new orientdb version v3.0.15 and try to alter object class property using following query
### `ALTER PROPERTY object.propertyName TYPE LINK`
but it throws the exception like java.lang.NullPointerException
This query is working fine in an older version that is v3.0.1

In another case, this query is working fine is this bug or new update in orientdb

**Comment by luigidellaquila** [comment]
Hi @rohitpatil7892 

In general you are not allowed to change property types, but you should have a much more explicit message (not an exception).
Can you please post a SQL script to reproduce the problem?

Thanks

Luigi
