### ISSUE TITLE
Drop method of Class "Cannot read property 'pageSize' of undefined"

### ISSUE THREAD

**Issue by shrawankher** [orientechnologies/orientjs#427]
Using Database version **3.0.28**
Using OrientJS API version **3.0.9** 
Using the class API method to drop the Class is throwing error as followed 
 
On using method **classObject.drop(CLASSNAME)**
Error thrown is as followed 
"Cannot read property 'pageSize' of undefined"
There is an issue with exec called within the drop method.
On further handling, the drop method promise break issue was seen.

**Comment by wolf4ood** [comment]
Hi @shrawankher 

thanks for reporting this. I've just pushed a fix. it will be available in the next version of OrientJS 3.,0.10

Thanks

**Comment by VikramShityalkar** [comment]
@wolf4ood When you are planning to release 3.0.10? We are in process of upgrading OrientDB as well as OrientJS. The timeline would be helpful to plan the activities.

**Comment by wolf4ood** [comment]
Hi @VikramShityalkar 

just released.

Thanks

**Comment by VikramShityalkar** [comment]
@wolf4ood Thank You.
