### ISSUE TITLE
Feature request: use access_token from HTTP api in query statements

### ISSUE THREAD

**Issue by jrylan** [orientechnologies/orientjs#44]
Since OrientDB has graph partitioning built in for multi-tenancy apps, it would be a huge benefit to allow an application client to retain only a single connection to an OrientDB instance -- and allow the application to handle passing around the user's access token.

I imagine the workflow as such:
#### 1. User authenticates via issuing a post request to /token/DB_NAME:

```
curl --data "grant_type=password&username=admin&password=admin" http://localhost:2480/token/foobar
```

The response looks something like this:

```
{
"@type": "d",
"@version": 0,
"access_token": "eyJAdHlwZSI6ImQiLCJAdmVyc2lvbiI6MCwidHlwIjoiT3JpZW50REIiLCJhbGciOiJIUzI1NiIsImtpZCI6IiJ9.eyJAdHlwZSI6ImQiLCJAdmVyc2lvbiI6MCwiaXNzIjpudWxsLCJleHAiOjE0Mzc0NDM1Nzk1OTQsImlhdCI6MTQzNzQzOTk3OTU5NCwibmJmIjoxNDM3NDM5OTc5NTk0LCJzdWIiOiJ3c3giLCJhdWQiOiJPcmllbnREQiIsImp0aSI6Ijg4Y2NiZjVkLTQ3YzktNDJhYS1hMWIzLWI5ODBmZTY4ZDkwZSIsInVpZGMiOjUsInVpZHAiOjAsImJkdHlwIjpudWxsLCJAZmllbGRUeXBlcyI6ImV4cD1sLGlhdD1sLG5iZj1sLHVpZHA9bCJ9.4Ypb81ultpLgxK0A-JsgIjhcSanTWjyz5iw7LHY63r0=",
"expires_in": 3600
}
```
#### 2. Client application retains the value of `access_token` from the response and uses it for every query related to a partitioned dataset.

```
db.select().token(access_token).from('Some_Collection')
```

If this is already possible, then it would be greatly appreciated to provide an example and documentation around it. 

I know there is the db.createUserContext method which takes a token, but even if I create a buffer from the value of `access_token` in the HTTP response, it doesn't work.

This is an absolutely critical feature for any large scale app that needs data partitioning -- in my case, separate database connections for each user will not be a realistic option when there are 5,000 to 10,000 users connected at the same time.
#### 3. Make this work with live queries.

This would allow for OrientDB to be significantly easier to integrate into real-time projects like Meteor.

**Comment by a-unite** [comment]
:+1:
