### ISSUE TITLE
Record are not fetched if used the " character into query

### ISSUE THREAD

**Issue by Nilesh-Kale-2212** [orientechnologies/orientjs#443]
I am writing the application in which I have to search the student by Address. But I am facing an OrientDB error with code 1 while getting the Students list by " character into the address field.

Node Version: v12.18.3
Orient DB Version: 3.0.29
Orient JS Version: 3.0.11

Steps to Reproduce an Issue

**Prerequisites:**
1. Create a new Database with a name like  "Test_Search_Name_Issue"
3. Open the Database into Orient DB Studio
4. Create class Student
``CREATE CLASS Student IF NOT EXISTS EXTENDS V`` 
6. Create properties Name and Address for Student Class
`CREATE PROPERTY Student.Name IF NOT EXISTS STRING`
`CREATE PROPERTY Student.Address IF NOT EXISTS STRING`
9. Create student record whose Address contains the ' and " characters
`insert into Student(Name, Address) values ("First Student", "Wing 'A', Ocean Society, Pune, India")`
`insert into Student(Name, Address) values ("Second Student", 'Wing "B", Ocean Society, Pune, India')`
12. Get all the Students to verify inserted record
`select from Student`
14. Search the students by address including special character into an address and fire the query at Orient DB Browser
`select from Student where Address like "Wing \'A\', Ocean Society, Pune, India"`
`select from Student where Address like "Wing \"B\", Ocean Society, Pune, India"`
17. The results of Students with both queries are listed.

**Issue Steps:**
Now create the small npm package and try to call the queries of search Student by Address using the Orient JS.

1. Install the npm package of "orientjs" with version 3.0.11
2. Create a simple application with filename 'node .\searchNameIssue.js' to get the Student record by Address along with a special character

```
const OrientDB = require('orientjs');

async function searchNameIssue() {

    let dbServerConfiguration = {
        "host": 'localhost',
        "port": 2424,
        "username": "root",
        "password": "root",
        "name": "Test_Search_Name_Issue",
        "Student": "root",
        "pool": { max: 50 }
    };

    console.log(`Attempting to connect to database`);
    let client = await OrientDB.OrientDBClient.connect({
        host: dbServerConfiguration.host,
        port: dbServerConfiguration.port,
        pool: dbServerConfiguration.pool
    });
    let sessions = await client.sessions(dbServerConfiguration);
    console.log('Successfully connected to Database');

    let sessionToUse = await sessions.acquire();
    let getFirstStudentDataQuery = `select from Student where Address like "Wing \'A\', Ocean Society, Pune, India"`;
    console.log(`\n\nAttempting to get First Student Data...`);
    console.log(`Query : ${getFirstStudentDataQuery}`);
    let firstStudentResult = await  sessionToUse.query(getFirstStudentDataQuery).all()
    console.log(`First Student Data Received...`);
    console.log(`${JSON.stringify(firstStudentResult)}`);
    await sessionToUse.close();


    sessionToUse = await sessions.acquire();
    let getSecondStudentDataQuery = `select from Student where Address like "Wing \"B\", Ocean Society, Pune, India"`;
    console.log(`\n\nAttempting to get Second Student Data...`);
    console.log(`Query : ${getSecondStudentDataQuery}`);
    let secondStudentResult = await  sessionToUse.query(getSecondStudentDataQuery).all()
    console.log(`Second Student Data Received...`);
    console.log(`${JSON.stringify(secondStudentResult)}`);
    await sessionToUse.close();


    await client.close();
}

searchNameIssue();
```

As we run the execution file using the command `node .\searchNameIssue.js`, the following result gets logged at the console. The first Student record gets fetched but while getting the second Student record the system throws an error 

```
PS D:\SearchNameIssue> node .\searchNameIssue.js
Attempting to connect to database
Successfully connected to Database


Attempting to get First Student Data...
Query : select from Student where Address like "Wing 'A', Ocean Society, Pune, India"
First Student Data Received...
[{"@class":"Student","Address":"Wing 'A', Ocean Society, Pune, India","Name":"First Student","@rid":"#21:0","@version":1}]


Attempting to get Second Student Data...
Query : select from Student where Address like "Wing "B", Ocean Society, Pune, India"
(node:25448) UnhandledPromiseRejectionWarning: OrientDB.RequestError: Error parsing query:
select from Student where Address like "Wing "B", Ocean Society, Pune, India"
                                              ^
Encountered " <IDENTIFIER> "B "" at line 1, column 47.
Was expecting one of:
    <EOF>
    <AND> ...
    <OR> ...
    <ORDER> ...
    <GROUP> ...
    <LIMIT> ...
    <SKIP2> ...
    <OFFSET> ...
    <TIMEOUT> ...
    <FETCHPLAN> ...
    <LOCK> ...
    <NOCACHE> ...
    <PARALLEL> ...
    <UNWIND> ...
    ";" ...
    <AND> ...
    <OR> ...
    <GROUP> ...
    <ORDER> ...
    <UNWIND> ...
    <SKIP2> ...
    <OFFSET> ...
    <LIMIT> ...
    <FETCHPLAN> ...
    <TIMEOUT> ...
    <LOCK> ...
    <PARALLEL> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...
    <NOCACHE> ...

        DB name="Test_Search_Name_Issue"
        Error Code="1"
    at child.Operation.parseError (D:\Intelinotion_Project\Exploration\SearchNameIssue\node_modules\orientjs\lib\client\network\protocol37\operation.js:1247:13)
    at child.Operation.consume (D:\Intelinotion_Project\Exploration\SearchNameIssue\node_modules\orientjs\lib\client\network\protocol37\operation.js:571:35)
    at ONetworkConnection.Connection.process (D:\Intelinotion_Project\Exploration\SearchNameIssue\node_modules\orientjs\lib\client\network\conn.js:462:17)
    at ONetworkConnection.Connection.handleSocketData (D:\Intelinotion_Project\Exploration\SearchNameIssue\node_modules\orientjs\lib\client\network\conn.js:344:20)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
(node:25448) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25448) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Please help/suggest the approach to get the Student information using an Address that has " character.
Thanks in Advanced...

**Comment by tglman** [comment]
Hi, 

Double checking this, this seems  a problem of escaping, when you write a query: 
`select from Student where Address like "Wing \"B\", Ocean Society, Pune, India"`
the escape are "consumed" by javascript, like you can see in the console.log output:

Query : select from Student where Address like "Wing "B", Ocean Society, Pune, India"

this means you are sending to the server a query with a where condition `where Address like "Wing "B", Ocean Society, Pune, India"` that contains two strings first: "Wing"  and second ", Ocean Society, Pune, India" with a  `B` in the middle that is not a valid syntax.

for resolve this case you need to do additional escaping, for example:

`select from Student where Address like "Wing \\\"B\\\", Ocean Society, Pune, India"`

Regards
