### ISSUE TITLE
Unable to create function using createFn on OrientDB 3.2.13

### ISSUE THREAD

**Issue by VikramShityalkar** [orientechnologies/orientjs#450]
I am using the createFn from old client, however it is not working with 3.2.13 because of session token issue. I have used createFn from session but it is creating function in database which not syntactically correct. 

I have attached sample function and script to create function.
[test.zip](https://github.com/orientechnologies/orientjs/files/10293297/test.zip)

Just extract the zip and do npm install and run the test.js. The demoFunction will be created but it is not usable.

**Comment by tglman** [comment]
Hi,

We did have some issue in the JS engine in earlier version of OrientDB, that have been fixed in more recent version, like this: https://github.com/orientechnologies/orientdb/issues/9690 now functions should work correctly.

Closing this, feel free to re-open if you still experience problems.
