### ISSUE TITLE
Is this project still being supported as last release on NPM was 3 years ago...

### ISSUE THREAD

**Issue by algoflows** [orientechnologies/orientjs#452]
Is this DB driver still being supported? Last release was 3 years ago on NPM...... 

Running into issues with typescript and AWS lambda, when bundling our lambdas we get the following errors.

✘ [ERROR] Could not resolve "./protocol28"
    node_modules/orientjs/lib/transport/binary/connection.js:231:32:
      231 │         this.protocol = require('./protocol28');
          ╵                                 ~~~~~~~~~~~~~~
✘ [ERROR] Could not resolve "./protocol26"
    node_modules/orientjs/lib/transport/binary/connection.js:234:32:
      234 │         this.protocol = require('./protocol26');
          ╵                                 ~~~~~~~~~~~~~~
✘ [ERROR] Could not resolve "./protocol19"
    node_modules/orientjs/lib/transport/binary/connection.js:237:32:
      237 │         this.protocol = require('./protocol19');
          ╵                                 ~~~~~~~~~~~~~~
✘ [ERROR] Could not resolve "./protocol33"
    node_modules/orientjs/lib/client/network/conn.js:213:28:
      213 │     this.protocol = require("./protocol33");
          ╵                             ~~~~~~~~~~~~~~

We are trying to use orientjs 3.xxx latest and any help would be greatly appreciated.

Thanks for the work so far, shame this is no longer being maintained.

**Comment by tglman** [comment]
Hi,

OrientDB itself is still maintained but this driver is not, this is mainly for missing skills and time to work on node based projects, in any case we are happy to accept and review contribution by third party, and when ready to release also new versions.

Regards

**Comment by algoflows** [comment]
It's a massive shame, our company rely on this and don't have the capacity to maintain a database driver on top of the product which as considering migrating as an option.

**Comment by algoflows** [comment]
Module resolution errors, looked through the code this could be a relatively easy fix for someone who knows the codebase, shame none of the core contributors will look into solving this issue.

**Comment by algoflows** [comment]
@tglman any chance we can hop on a call and you talk me through the codebase so I can resolve some of the outstanding issues, I am happy to help maintain but would be helpful to have some early assistance in getting started with the project?

**Comment by tglman** [comment]
Hi @algoflows ,

Yep I could that, what tool would you prefer ?

Regards

**Comment by algoflows** [comment]
Lets go with hangouts :) s@seanknowles.dev

**Comment by tglman** [comment]
Hi,

has I mentioned here https://github.com/orientechnologies/orientjs/issues/451#issuecomment-1792393899 we did ship a new release with compatibility fixes.
