### ISSUE TITLE
npm orientjs

### ISSUE THREAD

**Issue by Lyumih** [orientechnologies/orientjs#459]
Orientjs is alive? 
Last version is 2020 https://www.npmjs.com/package/orientjs
Download only from github develop branch (crashed on yarn).

Are there plans to update the npm version?
Is there any chat in telegram or discord?

I plan to use orientis in a number of projects
Thanks

**Comment by mathieulemieux** [comment]
Feels the same here. We're using orientjs on a critical application and we'll have to migrate to something else if we can't make the npm library works with Node 18.
Fortunately, it seems there is some recent development about it: https://github.com/orientechnologies/orientjs/commit/1d9f4894a065787aeeed8c4f69f75855409854f9

**Comment by tglman** [comment]
Hi,

refer to this: https://github.com/orientechnologies/orientjs/issues/451#issuecomment-1792393899

Regards

**Comment by mathieulemieux** [comment]
@tglman , Ty for the hard work here!
Are a merge with the master branch and a new release on npm planned in the foreseeable future?

**Comment by Lyumih** [comment]
Gracios!
