### ISSUE TITLE
@this.toJson() in query return non escaped javascript object

### ISSUE THREAD

**Issue by Lyumih** [orientechnologies/orientjs#460]
`   return this.orient.query<Repo>("select *, @this.toJson('rid,version,fetchPlan:in_*:-2 out_*:-2') as all from Hero").all()`
I have 2 problems
- charser RU localisation transfers to Unicode
- all return just string, no escaped plained javascript object

Please help

![image](https://github.com/orientechnologies/orientjs/assets/32732179/3a42a93c-73f8-443d-a83a-047615b2ee4d)
<img width="1671" alt="image" src="https://github.com/orientechnologies/orientjs/assets/32732179/6a521531-0710-46cc-8c45-e120df8d22f5">

**Comment by tglman** [comment]
Hi,

The `toJson` is made to create a string, I think what you are trying to do is to use nested projections, checkout the docs here : https://orientdb.com/docs/latest/sql/SQL-Projections.html#nested-projections

Regards

**Comment by Lyumih** [comment]
<img width="1672" alt="image" src="https://github.com/orientechnologies/orientjs/assets/32732179/4466dcb7-dbd5-4e04-8202-39340d1fbe66">
It's Excelent!!
`select *, out(HeroSkill):{*} as skills, out(HeroWeapons):{*} as weapons from hero`

I can somehow convert it straight into a simple js object, not json?)
