### ISSUE TITLE
sql order parse issue.

### ISSUE THREAD

**Issue by phpnode** [orientechnologies/orientjs#5]
_From @martingg88 on May 26, 2015 8:47_

SELECT EXPAND(rid) FROM (SELECT story.release_date AS release_date, @rid FROM resource ORDER BY (release_date DESC, ctime DESC) LIMIT 15)

can we remove the bracket for order clause because it will have sql parse issue if we include more than one field in order bracket. 

(release_date DESC, ctime DESC) 

_Copied from original issue: codemix/oriento#319_

**Comment by maggiolo00** [comment]
hi @martingg88 
is this issue valid?

If yes can you help me to reproduce it?

**Comment by martingg88** [comment]
we can use array structure for order clause as orientjs will handle it. close this issue please. thanks
