### ISSUE TITLE
Why orientjs do not support rollback function?

### ISSUE THREAD

**Issue by tampham47** [orientechnologies/orientjs#50]
I see that orientjs has support commit(), but the rollback() is not available. Could you tell me the reason for that, because I want to implement rollback() myself :smile:

**Comment by lvca** [comment]
In OrientDB the transaction stays in memory until the commit() that flushes all changes to the server. Rollbacking a transaction means do nothing on the client side, unless you want to restore objects on the previous state on the client.

**Comment by maggiolo00** [comment]
I'm closing this.
