### ISSUE TITLE
Where is the detailed API reference?

### ISSUE THREAD

**Issue by Kelvin-Ng** [orientechnologies/orientjs#60]
I have read the source code and find that there are some functions which are probably API functions for library users to call, but they are not documented in README.md or used in examples, such as the whole `Transaction` class in https://github.com/orientechnologies/orientjs/blob/master/lib/db/transaction.js.

I find that there are some comments which look very similar to JSDoc, but there are many syntax errors generated, so it is not correct JSDoc. Can anyone point out where is the detailed API reference or how to generate a document? Thank you!

**Comment by TwinTailsX** [comment]
+1 detailed documentation would be very helpful. 
Even though straightforward, functions like increment(), gt(), lt(), skip() are not known without looking at the code (I may not have even known there were more functions had this issue not existed)

**Comment by StarpTech** [comment]
@TwinTailsX @Kelvin-Ng would be nice if you update the docu and create a PR ;)

**Comment by maggiolo00** [comment]
hi Guys
we are moving the docs for editing here

https://github.com/orientechnologies/orientdb-docs/blob/master/source/OrientJS.md
We will structure the documentation in chapters with more example

In this way the final build of the documentation will go here along with OrientDB docs
http://orientdb.com/docs/last/

**Comment by luigidellaquila** [comment]
Hi guys,

The new OrientJS docs were just released, you can find them here

http://orientdb.com/docs/last/OrientJS.html

Closing, thanks

Luigi
