### ISSUE TITLE
Adding multiple properties by list doesn't work

### ISSUE THREAD

**Issue by stein321** [orientechnologies/orientjs#65]

**Comment by luigidellaquila** [comment]
Hi @stein321 

could you please provide a statement to reproduce the problem? Just to be sure we are on the same point.

**Comment by kurtcorbett** [comment]
Hello, @luigidellaquila 

```javascript
db.class.create('Page', 'V')
  .then(function (MyClass) {
    MyClass.property.create({
      name: 'name',
      type: 'String'
    }, {
      name: 'title',
      type: 'String'
    }, {
      name: 'id',
      type: 'Integer'
    })
  });
```

Only saves 'name' property and not 'title' or 'id' properties.

```javascript
db.class.create('Page', 'V')
  .then(function (MyClass) {
    MyClass.property.create([{
      name: 'name',
      type: 'String'
    }, {
      name: 'title',
      type: 'String'
    }, {
      name: 'id',
      type: 'Integer'
    }])
  });
```

Putting the property objects in an array seems to work, though that conflicts with "Adding a property to a class" part of the docs.

**Comment by luigidellaquila** [comment]
Thanks for the details

**Comment by maggiolo00** [comment]
hi @stein321
I saw that the documentation is wrong. I'm updating it.
To create multiple property you have to pass an array of object.

**Comment by maggiolo00** [comment]
updated
https://github.com/orientechnologies/orientjs
