### ISSUE TITLE
db.exec does not support transactions

### ISSUE THREAD

**Issue by tortis** [orientechnologies/orientjs#68]
I know it is possible to run a transaction with db.let(), but it would be desirable to run a SQL transaction directly. 

When I attempt this I get sql.BEGIN not defined, presumable because the query is executing as a command.

Thanks

**Comment by StarpTech** [comment]
Try `db.query(query, { class: 's' })`

from docu https://orientdb.com/docs/last/Network-Binary-Protocol.html#request_command
```
s - stands for "script" (for server-side scripting using languages like JavaScript). It's like passing com.orientechnologies.orient.core.command.script.OCommandScript
```

**Comment by tortis** [comment]
Thank you! This did the trick.

A note for future readers: I was attempting to execute a SQL transaction, had built a concatenated string like so: 
<pre>
var createCourseQuery =
    'BEGIN '+
    'let newcourse = CREATE VERTEX Course Content {name: "Name"} '+
    'let hascourse = CREATE EDGE hasCourse FROM(SELECT FROM Teacher WHERE @rid=#19:8) TO $newcourse '+
    'COMMIT '+
    'RETURN $newcourse';</pre>

This was failing with a result of null, but I modified it to use \n newlines instead of spaces and that fixed it.
I just found this unusual because if you write a SQL function in Studio, you can write a transaction without newlines and it will run fine, but not in this context.

**Comment by StarpTech** [comment]
@tortis here a simple transaction builder for my own use.
https://gist.github.com/StarpTech/ca0f923c49fd956c1c13
