### ISSUE TITLE
How to save large binary data using oriento on orientdb?

### ISSUE THREAD

**Issue by phpnode** [orientechnologies/orientjs#7]
_From @vjsrinath on May 26, 2015 1:16_

I am trying to save image and video files directly in orientdb. After doing little bit of search, I saw the following documentation [Binary Data](http://orientdb.com/docs/last/Binary-Data.html). How to save bytes data using ORecordBytes with oriento.

Any help is appreciated. Thanks in advance.

_Copied from original issue: codemix/oriento#316_

**Comment by phpnode** [comment]
_From @rmemoria on May 30, 2015 23:1_

+1... Same doubt

**Comment by maggiolo00** [comment]
PR Merged
