### ISSUE TITLE
Feature plans?

### ISSUE THREAD

**Issue by seeden** [orientechnologies/orientjs#72]
What is a current state for this library?
Are you working on new better library with full support of orientdb written in ES6?

**Comment by gyzerok** [comment]
@lvca Any plans on upcoming release date?

**Comment by wizrd** [comment]
@seeden What exactly are you asking for? Being as it's promise-based already. Are you suggesting generator based interface?

**Comment by seeden** [comment]
I read on orientdb [blog](http://orientdb.com/orientdb-performance-challenge/) month ago:

> You may wonder why we’re still slower on the “single reads” and “neighbors2” tests. Regarding the “single reads” test, we measured the OrientDB Server and it was extremely fast. However, 70% of the processing time was spent on unmarshalling the response of the OrientDB server by the Node.js driver. We found the bottleneck and the upcoming fix is already on our roadmap. Regarding the “neighbors2” test, well this use case has little value in the real world because when you do a traversal of neighbors, you’re interested in retrieving actual information about the neighbors instead of just their ID or key. - See more at: http://orientdb.com/orientdb-performance-challenge/#sthash.f7WAZojT.dpuf

I would like to know if the OrientJS driver is waiting only for pull request from contributors or orientdb team are working on improvements in the background.

**Comment by lvca** [comment]
Hi guys,
We already have 50% done the support for native code that do unmarshalling of records. This will speedup any query and object loading in orientjs. @tglman and @maggiolo00 are working on it. I hope to have something for maximum the next week ;-)

**Comment by seeden** [comment]
Thanks @lvca it sound good :+1:

**Comment by gyzerok** [comment]
@lvca I'd like to use OrientDB in production. Can tell soething about release date for this feature? It's nice if its already 50% done. But it can be done in 100% in the next summer... There is no trackable progress from commits.

**Comment by lvca** [comment]
@gyzerok I already wrote we're 50% and I hope to have something for maximum the next week. I can't say more, but I'll keep you updated in the next (working) days

**Comment by gyzerok** [comment]
@lvca Thanks! I'm now really excited about OrientDB and gonna be more with your new performant release for this driver.

**Comment by gyzerok** [comment]
@lvca Btw is there any realisation for OrientDB but for in-browser usage? In my case I use OrientDB with GraphQL on the server and GraphQL with simple cache (basically just a Map). It would be awesome to query both OrientDB and cache with the same SQL-like language.

**Comment by lvca** [comment]
@gyzerok we don't have a Browser porting of OrientJS, but it could be doable. Any volunteer in the community?

**Comment by gyzerok** [comment]
@lvca I think here is no need to some realisation for the database. Simple javascript Object for cache is ok. Really in my case I just need the ability to query it with the same SQL-language un order to make my GraphQL-schema really isomorphic.

I would try to investigate it.

**Comment by seeden** [comment]
Half of the year later without any response.

**Comment by maggiolo00** [comment]
hi @seeden 

the native marshalling/ unmarshalling is scheduled for 2.2.
Most of the work has been done, alls test pass with the native code.
 
We are now working on the packaging side.

**Comment by seeden** [comment]
Hi @maggiolo00 I can not wait. Thank you

**Comment by maggiolo00** [comment]
@seeden 
are you waiting for native serialization?
Or other features?

**Comment by seeden** [comment]
@maggiolo00 I can see a lot of CPU usage on my production server caused by orientjs driver. I would like to see next features in short term: streams and working serialisation of the embedded documents (orientechnologies/orientdb/issues/3449). Right now I am not able to use a lot of data at once because orientjs always load all records into the memory. This is the reason why I am not able to use orientjs for everything in this moment.

**Comment by seeden** [comment]
I am closing this issue because I am deleting this shitty database forever. I am not going to use it anymore never ever in my life. What a big shame and ignorance attitude

**Comment by maggiolo00** [comment]
Hid @seeden 

Did you experience some problems?
Can you elaborate more?

Thanks
Enrico

**Comment by StarpTech** [comment]
Hi @maggiolo00 I think the problem is clear. 
@seeden is not able to handle big data with orientjs.

- Serialisation
- Streaming support

This makes orientjs really unusable if you want to work with Big Data cooperate with a driver except the native java api.

**Comment by seeden** [comment]
@StarpTech I spent last 24 hours with corrupted indexes and tables. SQL queries are not working correctly. Indexes are slow or not working. After one whole year with this database I can say that it is crap in this moment. I do not want to answer anymore and therefore I am going to unsubscribe from all orientdb threads.

**Comment by StarpTech** [comment]
@seeden your vote is very important. Did you open issue with good examples? Which versions did you use?

**Comment by luigidellaquila** [comment]
Hi @seeden 

I'm really sorry to read this, as far as I can understand you invested some important effort on OrientDB, so please let us know if we can help in any way. 
Any additional detail about the version you are using, the use case, or even failing test cases or corrupted databases would help a lot in fixing things.

Thanks

Luigi
