### ISSUE TITLE
Running "MOVE vertex" query error

### ISSUE THREAD

**Issue by rajeshvaya** [orientechnologies/orientjs#74]
When I try to run a raw query for the [Move vertext](http://orientdb.com/docs/2.0/orientdb.wiki/SQL-Move-Vertex.html) command I get the following error 

"Cannot execute non idempotent command, , previous=[], id=1, type=com.orientechnologies.orient.core.exception.OCommandExecutionException, hasMore=0"

Query I try to run ```MOVE vertex #14:61 to CLASS:loyalty_deleted set deleted_date = Date(), original_rid = #14:61```

On logging the query before execution "beginQuery" below is the output 
```{"query":"MOVE vertex #14:61 to CLASS:loyalty_deleted set deleted_date = Date(), original_rid = #14:61","mode":"a","fetchPlan":"","limit":1,"class":"com.orientechnologies.orient.core.sql.query.OSQLAsynchQuery","level":"info","message":"","timestamp":"2015-08-25T04:45:47.808Z"}```

This query runs perfectly when I run through the Studio or Console

Any help in temporary fix will be greatly appreciated

**Comment by lvca** [comment]
All the non idempotent commands can't run with query but rather with exec:

```
db.exec('MOVE vertex #14:61 to CLASS:loyalty_deleted set deleted_date = Date(), original_rid = :rid', {
  params: {
    rid: "#14:61"
  }
}).then(function (response){
  console.log(response.results);
});
```

**Comment by rajeshvaya** [comment]
Thanks!

**Comment by StarpTech** [comment]
@lvca I can run all commands with `query` also the orientjs docu explains that.

**Comment by StarpTech** [comment]
@lvca I can run all commands with query also the orientjs docu explains that.

**Comment by rajeshvaya** [comment]
I was passing ```"limit: 1"``` as a parameter for both ```query``` and ```exec```

After I removed the limit flag. It was working fine for both.

**Comment by lvca** [comment]
@StarpTech You're right, my fault.

**Comment by StarpTech** [comment]
@rajeshvaya please post you exact code.

**Comment by rajeshvaya** [comment]
@StarpTech please see below

```js
       id = "#14:137";
       logger.debug("Fetching loyalty by id for : " + id);
       sql = "MOVE vertex " + id +" to CLASS:loyalty_deleted set deleted_date = Date(), original_rid = " + id;
        db.query(sql,{
             limit: 1
        })
        .then(function(data){
            logger.debug("Deleted loyalty card : %s ", id, {responseData: data});
            return callback(null, []);
        })
        .catch(function(err){
            logger.error("Could not delete the loyalty card : %s ", id, {error: err});
            return callback(err);
        });

```


The above code returns the below error

```
debug: Fetching loyalty by id for : #14:137
error: Could not delete the loyalty card : #14:137  name=OrientDB.RequestError, message=Cannot execute non idempotent command, , previous=[], id=1, type=com.orientechnologies.orient.core.exception.OCommandExecutionException, hasMore=0
```

When I enable the orientjs logging for 'beginQuery' I see the below 


```js
{"query":"MOVE vertex #14:137 to CLASS:loyalty_deleted set deleted_date = Date(), original_rid = #14:137","mode":"s","fetchPlan":"","limit":-1,"class":"com.orientechnologies.orient.core.sql.OCommandSQL","level":"info","message":"","timestamp":"2015-08-25T12:58:53.853Z"}
```

**Comment by dax0** [comment]
I'm also having this issue with the following query

			"CREATE EDGE E " +
			"FROM (CREATE VERTEX V) " +
			"TO (CREATE VERTEX V) "
