### ISSUE TITLE
Issue with migrate

### ISSUE THREAD

**Issue by gyzerok** [orientechnologies/orientjs#76]
Every time I am trying to use migrate feature nothing happens

```
gyzerok:hello gyzerok$ orientjs migrate create initial
Usage: orientjs [OPTIONS] [db|migrate]

Options:
  -d, --cwd         The working directory to use.       [default: "/Users/gyzerok/Documents/self/hello"]
  -h, --host        The server hostname or IP address.  [default: "localhost"]
  -p, --port        The server port.                    [default: 2424]
  -u, --user        The server username.                [default: "root"]
  -s, --password    The server password.              
  -n, --dbname      The name of the database to use.  
  -U, --dbuser      The database username.              [default: "admin"]
  -P, --dbpassword  The database password.              [default: "admin"]
  -?, --help        Show this help screen.            
```

```
gyzerok:hello gyzerok$ orientjs migrate list
Usage: orientjs [OPTIONS] [db|migrate]

Options:
  -d, --cwd         The working directory to use.       [default: "/Users/gyzerok/Documents/self/hello"]
  -h, --host        The server hostname or IP address.  [default: "localhost"]
  -p, --port        The server port.                    [default: 2424]
  -u, --user        The server username.                [default: "root"]
  -s, --password    The server password.              
  -n, --dbname      The name of the database to use.  
  -U, --dbuser      The database username.              [default: "admin"]
  -P, --dbpassword  The database password.              [default: "admin"]
  -?, --help        Show this help screen.            
```

**Comment by ericrav** [comment]
It seems you have to include the dbname flag. Trying adding -n <your db name>. This worked for me.
Also make sure you have a migrations directory

**Comment by gyzerok** [comment]
@ericrav is started working for me just after I've included full db credentials. But I dont understand why. How an existing database connected with my migrations? What if I have 2 dbs local for development and production. Do I have to create different migrations? It's a little confusing for me.

**Comment by cheshirecatalyst** [comment]
I'm still getting this too, even after supplying the default credentials. @gyzerok could you provide an example of your full connection string so i can make sure i didn't miss something

**Comment by gyzerok** [comment]
orientjs -h="hostname" -p=2424 -n=dbname -u=root -s="password" migrate create

**Comment by gyzerok** [comment]
As for me migrations are unusable now.

**Comment by cheshirecatalyst** [comment]
Thanks. By unusable do you mean because of your questions about 2dbs local production and dev?

**Comment by gyzerok** [comment]
I do not quite understand why should I use credentials to create migrations. There is no good documentation on how do they applies. So I'm quite scary to use them and have not enough time to dig deeper.

**Comment by cheshirecatalyst** [comment]
I think the issue is here, in regular node.js you would be loading in your credentials perhaps through an environment variable, the CLI tool has no way of knowing specifically how to connect and what db user to attempt the migration as. 

It would be nice if this tool would integrate a small library like [dotenv](https://github.com/bkeepers/dotenv) so we could keep out credentials in a .env file in a manner consistent with several PAAS and in general. So i don't have to fill my shell with so many things just to run what could be local migrations.

**Comment by gyzerok** [comment]
@cheshirecatalyst migrations creation is db agnostic. Why do you need credentials to create a migration?

**Comment by cheshirecatalyst** [comment]
because this isn't a generic adaptor for creating migrations across database solutions, these migrations are only for orientdb, as far as i understand. So this would be something completely different than say using actual orm and migration framework that is db agnostic.

**Comment by gyzerok** [comment]
@cheshirecatalyst you do not get me right :) I'm not talking about different db engines. I'm talking about different db instances in orient.

**Comment by cheshirecatalyst** [comment]
hmmm, so you are saying, why does it have to actually log in to the server to create the skeleton file for you to fill in the migration information. it should only need credentials when saying `orientjs migrate up` in which case it should know what db to connect to to actually do the migration, correct?

**Comment by kurtcorbett** [comment]
The docs are really bad for migration stuff. Not clear at all.  Here is what worked for me (though this doesn't directly answer @gyzerok 's question about multiple dbs).  Hopefully it can help others get going if they are stuck. 

### Create a file called orientjs.opts in the root directory
```
- server/
- node_modules/
- package.json
- orientjs.opts

```
### Here are the orientjs.opts file contents (based on example in docs)

```
--host=localhost
--port=2424
--password=root
```

### Create a database through the orientjs cli tool (from same directory as orientjs.opts file)

```
/path$> orientjs db create test_db graph plocal

-->Creating database with name: test_db
-->done.
```

### Add a migrations directory in the root directory

```
- server/
- node_modules/
- migrations/
- package.json
- orientjs.opts

```

### Create a migration called "first migration".   

```
$> orientjs -n=test_db migrate create first migration

-->Creating a new migration called: first migration
new migration .../migrations/m20151023_020046_first_migration.js created.
```

### Here is the result

```
- server/
- node_modules/
- migrations/
    - m20151023_020046_first_migration.js
- package.json
- orientjs.opts

```
