### ISSUE TITLE
[Bug] Queries with template strings

### ISSUE THREAD

**Issue by gyzerok** [orientechnologies/orientjs#77]
I'm highly requesting for adding correct support template strings upon queries to be able to write nice queries.

``` javascript
db.query(`
  select from Foo
  order by baz desc
`);
```

**Comment by seeden** [comment]
I think that this is a problem for orientdb and not for orientjs

**Comment by wizrd** [comment]
@gyzerok What version of node are you running? I have no issues using template strings with io.js v3.2.

Reproduce-able code, iojs-v3.2.0
```javascript
'use strict';

let orientdb = require('orientjs')
let query = `select
from
V
`

let server = orientdb({
	host: 'localhost',
	port: '2424',
	username: 'root',
	password: 'admin'
})

let db = server.use({
	name: 'GratefulDeadConcerts',
	username: 'root',
	password: 'admin'
})

db.query(query).then(function (response) {
	console.log('Response: ' + response)
})
```

**Comment by gyzerok** [comment]
@wizrd node 0.12.7 & babel 5.8

**Comment by wizrd** [comment]
What error message are you getting?

**Comment by gyzerok** [comment]
@wizrd I would try to share error tomorrow. As I remember it definitely connected with orient. Mb not with the driver directly.

**Comment by dax0** [comment]
I think it's the blank spaces/newline at the beginning of your query.  Adding a .trim() fixes my issue

**Comment by wizrd** [comment]
@dax0 That's not an issue for me though. I can add spaces and newlines as I please pre query string.
This works fine for me (vanilla io.js v3.2.0):
```javascript
let query = `  
select
from
${myClass}
limit ${10 - 9}
`
```
