### ISSUE TITLE
Issue with FetchPlan

### ISSUE THREAD

**Issue by EricLin2004** [orientechnologies/orientjs#78]
When I run
`SELECT *, out("hasAttachment") as attachments FROM #11:5 FETCHPLAN *:1`
In OrientDB Studio, I get a column called `attachments` with an array of class `Attachment` objects unwrapped with all properties.

However, when I run the same query with
`db.query('SELECT *, out("hasAttachment") as attachments FROM #11:5 FETCHPLAN *:1')`

I get the column `attachments` with an array of `@rid`s only, it's as if the fetchPlan was ignored.

I also tried to use
`db.select('*, out("hasAttachment") as attachments).from('#11:5').fetch({ "*":1 })`
to no avail, modifying the `fetch` parameters I would end up getting circular toJSON error.

Can anyone give me a hand here?

Thanks in advance.

**Comment by martingg88** [comment]
I have the same issue if i mix the query with UNIONALL. 

here is the class for both "user" and "property";

User 
 @rid name
  #1:2  tester
 
Property
 @rid name creator (linked to user class)
 #1:3  room    #1:2

1. select from #1:3 
     return me as follows
      #1:3  room    #1:2

2. SELECT EXPAND(UNIONALL($user, $property)) FROM property LET $user = (SELECT EXPAND(IN("own")[@class="user"]) FROM $current),$property = (SELECT FROM $current) WHERE @rid = #1:3
       return me as follows
       #1:3  room    {@class: 'user', @rid: #1:2, @name: tester}

       note that. i expect it return the user's @rid only that is linked to property, no the object of the user.

**Comment by martingg88** [comment]
any update? i expect the FETCHPLAN should be disabled by default, unless we specify it as we need.

**Comment by EricLin2004** [comment]
Well, I was able to get one level deep by specifying 
`db.query('SELECT *, out("hasAttachment") as attachments FROM #11:5 FETCHPLAN attachments:1')`

I'm not sure why `*:1` doesn't work.. and I can't get it to go two levels deep either.

**Comment by TwinTailsX** [comment]
+1
```
SELECT expand(in()) FROM Class FETCHPLAN out_OtherClass:0
```
works fine in the Studio but the driver doesn't seem to use the fetchplan unless you specify the field as a projection:
```
SELECT in() AS otherclassFROM Class FETCHPLAN otherclass:0
```

**Comment by StarpTech** [comment]
This seems like an orientdb issue I would create an issue there.

**Comment by TwinTailsX** [comment]
@StarpTech I'm using the query builder

**Comment by EricLin2004** [comment]
It's been awhile but I've come back to this issue again.

Anyone figure out why `fetchplan` doesn't work with `db.exec` or `db.query`?

I basically have this query:
```
SELECT *, intersect($first, $second) as connections FROM #13:7
LET $first = (SELECT FROM (TRAVERSE in('follows') FROM #13:5 WHILE $depth <= 1 STRATEGY BREADTH_FIRST) WHERE $depth = 1) , 
$second = (SELECT FROM (TRAVERSE out('follows') FROM #13:7 WHILE $depth <= 1 STRATEGY BREADTH_FIRST) WHERE $depth = 1) FETCHPLAN *:1
```
This works in OrientDB Studio / console (returns full objects for connections); however, when I try to put the same query into `db.exec` or `db.query`, it doesn't pre-fetch nodes and it just returns `@rid`s for my connections.

Any help would be greatly appreciated.

Thanks.

**Comment by EricLin2004** [comment]
Nevermind, I checked out the source code today and saw this:

https://github.com/orientechnologies/orientjs/blob/master/lib/db/index.js#L211

It's being taken in the optional param. Working when I add it in there.

**Comment by pmig** [comment]
For anyone wondering about the final solution for this problem:

```
        db.query('SELECT *, OUT("relation") as relation from node, {fetchPlan: 'relation:1'})
            .then(function (results) {
                // work with results
            });
```

**Comment by lvca** [comment]
@pmig how this solution is different? I'd like to update the docs if something is missing.

**Comment by pmig** [comment]
@lvca Updating the docs would be awesome. It probably fits best to the "Working with params" section on this page: http://orientdb.com/docs/last/OrientJS-Query.html

Because  it's not possible to use a fetchplan as part of the query itself you have to pass the parameter, which is nowhere documented

**Comment by lvca** [comment]
This is for @kennethpjdyer

**Comment by kennethpjdyer** [comment]
Thanks.  I'll get on it.
