### ISSUE TITLE
Connection Pooling in OrientJs

### ISSUE THREAD

**Issue by Vipul25** [orientechnologies/orientjs#89]
Is the connection pooling working properly in this driver?

Are the connections being closed by the driver automatically or they are supposed to be closed by the developer. I am getting error like reached maximum number of concurrent connections (1000).

**Comment by lvca** [comment]
Did you call .close() against server or database object?

**Comment by flyingrobots** [comment]
I'm also seeing unexpected connection counts when using OrientJS 2.0.0 against OrientDB 2.1.0. I create a single connection using OrientJS and the dash on OrientDB's web front-end shows 9 connections. If I terminate my app, the connection count usually drops to 3, which I assume are connections used by the web front-end. However, I've even seen the connection count mysteriously jump to 10 or 12 when there are no clients connected to the database except for me, using the web front-end to look at the dash, so who knows...

It is unfortunate that in OrientDB 2.1.0 the new perf dash no longer displays useful information about each connection. It is frustrating that it now only shows a connection count. The old dash used to display a table of connections, with information about each one, such as the transport it was using (binary VS http), the IP address, its activity, etc. Without this information, the web front-end has become less useful as a diagnostics tool when debugging connection-related issues. It is now very difficult for users to tell where each connection is coming from.

**Comment by Vipul25** [comment]
No it didnt, but if I do that i think that the whole point of connection pooling would be lost. As how to decide when to call close because calling close would close all the connections to the server.

For now i removed connection pooling from the application. Now it seems that when the application is closed the connection still persists which leads to unwanted connections at the OrientDb server

**Comment by billyxs** [comment]
I'm running into issues of high connection counts.  It appears the only way I can reliably clear up the connections is to close the server.  Calling db.close() doesn't appear to release the all the connections for a query. What do you recommend the lifecycle of an orientdb server and database connection to be when handling queries?

**Comment by urbantumbleweed** [comment]
I too am running into issues where calling db.close() does not close the connection to the OrientDB server.  I'm :+1: with @billyxs .

Also, I noticed that I can't export 'db.use()'.  I was expecting a db instance but it pure side-effect so it is undefined.  Having a db object would be helpful in abstracting the connection.

**Comment by MathildeLemee** [comment]
I have the same problem and question : "What do you recommend the lifecycle of an orientdb server and database connection to be when handling queries?"

Thanks !

**Comment by SafinRR** [comment]
Hi! I join the question:
"What do you recommend the lifecycle of an orientdb server and database connection to be when handling queries?"

**Comment by StarpTech** [comment]
Any updates?

**Comment by maggiolo00** [comment]
hi @StarpTech 

in orientjs 2.1.11 we added the pool api but is in experimental stage.

Here an example of usage.

```
var Pool = require("orientjs").Pool;

var pool = new Pool({
 host: 'localhost',
 port: 2424,
 username: 'admin',
 password: 'admin',
 name : 'GratefulDeadConcerts'
});


pool.acquire().then(function(db){
      db.query('select from v limit 1')
      .then(function(res){
         
         console.log(res);
         db.close().then(function(){
            pool.close().then(function(){
             console.log('pool closed');
            })   
         });
            
      })
   }).catch(function(error){
      console.log(error);
   })
```
By default the pool configuration is { min : 1 , max : 5}

**Comment by StarpTech** [comment]
Hi @maggiolo00 , why is it experimental. Its around 200 lines of code and lots of is reused from DB.js. What is the critical point in this implementation? I would like to use it in production.

**Comment by cloudle** [comment]
Any update on this? I'm going to use this on my project.. 
Not really sure now is already safe for us to start using Pool or not?
Thanks for any help ✌️

**Comment by mindnuts** [comment]
@maggiolo00 Would you say this feature is still experimental? 

We are keen to use this functionality and we are not sure if Orient technologies recommend the pool feature to be used in Production environments. 

Looking forward to your reply. Cheers.

**Comment by mindnuts** [comment]
@lvca Sorry to sound desperate but we are in dire need of pooling and just want a confirmation from Orient Technologies that connection pooling is stable and some other best practices around Connection Pooling.

Cheers

**Comment by maggiolo00** [comment]
Hi @mindnuts 

The available pool now is the one configured via  

```
var server = OrientDB({
   host:     'localhost',
   port:     2424,
   username: 'root',
   password: 'root_passwd',
   useToken: true,
  pool : {
      max : 10
  }
});
```

where you use one instance of `db` and for each operation a different connection will be used.

The above pool is not yet well tested
A stable version of the pool will be provided in the new version of the driver 3.0 and will be out with OrientDB 3.0, but it will have different api, for meeting the stateful transaction requirements in 3.0

If you need manual pool you can use for example an external pool like this for example

```
https://github.com/coopernurse/node-pool
```

by pooling this object

https://orientdb.com/docs/2.2/OrientJS-Database.html#using-standalone-databases

here an example.

https://gist.github.com/maggiolo00/3067b92584a7f25887e281b9a9e244bb

I can see if we can make the manual pool stable for the next release so you can use it

Thanks

Enrico

**Comment by mindnuts** [comment]
Thanks @maggiolo00 We will use the manual pool for now.

**Comment by wolf4ood** [comment]
Hi All, 

i'm closing this. The new OrientJS API provide this out of the box with sessions pool

https://orientdb.com/docs/3.0.x/orientjs/Client.html#sessions
