### ISSUE TITLE
Merge PR 330 from Oriento?

### ISSUE THREAD

**Issue by fc7** [orientechnologies/orientjs#99]
According to https://github.com/appscot/sails-orientdb/issues/124 OrientJS does not include the pull request https://github.com/codemix/oriento/pull/330 from the now deprecated Oriento driver. It is supposed to fix an issue with nested errors.

Any plans to integrate it to OrientJS? Apparently the maintainer of sails-orientdb (which is still based on Oriento) is waiting for that fix before migrating to OrientJS.

**Comment by lvca** [comment]
Sure, np. Merging manually...

**Comment by lvca** [comment]
Done.
